### ISSUE TITLE
在构建编译android项目时 报错说使用了过时的api/ English : Misuse of outdated APIs when building and compiling Android projects

### ISSUE THREAD

**Issue by mulieli** [fluttercommunity/flutter_downloader#102]
flutter_downloader-1.1.9/android/src/main/java/vn/hunghd/flutterdownloader/FlutterDownloaderPlugin.java使用或覆盖了已过时的 API

**Comment by hnvn** [comment]
I can't understand your problem, use English, please

**Comment by mulieli** [comment]
> I can't understand your problem, use English, please

flutter_downloader-1.1.9/android/src/main/java/vn/hunghd/flutterdownloader/FlutterDownloaderPlugin.java
 Use or override obsolete APIs. is that Ok?

**Comment by hnvn** [comment]
ah, it's just a warning, the plugin should work

**Comment by hnvn** [comment]
Duplicated of #89
