### ISSUE TITLE
While pause getting error 

### ISSUE THREAD

**Issue by vishnunarola** [fluttercommunity/flutter_downloader#104]
While file download is running FlutterDownloader.pause() throwing exception in Android while downloading .mp3 file.

> I/WM-WorkerWrapper( 7256): Work [ id=e50f4799-de5d-42ef-830d-62f283aed620, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ] was cancelled
I/WM-WorkerWrapper( 7256): java.util.concurrent.CancellationException: Task was cancelled.
I/WM-WorkerWrapper( 7256): 	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1184)
I/WM-WorkerWrapper( 7256): 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:514)
I/WM-WorkerWrapper( 7256): 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
I/WM-WorkerWrapper( 7256): 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:284)
I/WM-WorkerWrapper( 7256): 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:75)
I/WM-WorkerWrapper( 7256): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
I/WM-WorkerWrapper( 7256): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
I/WM-WorkerWrapper( 7256): 	at java.lang.Thread.run(Thread.java:764)
D/DownloadWorker( 7256): Download canceled

` final status = await FlutterDownloader.pause(taskId: queuedDownload.taskId);`

Device Specification

- Model Number: OnePlus3T
- Android OS: 9.0
- Oxygen OS: 9.0.4

**Comment by hnvn** [comment]
It's OK, it occurs when we call `cancelWorkById` in `WorkManager`, it is internal exception of `WorkManager`. I have no idea about it but it doesn't break our "pause" feature

**Comment by vishnunarola** [comment]
Thank you @hnvn

**Comment by shinewanna** [comment]
Hello @vishnunarola 
After paused, can u resume it??

When I paused

> Work [ id=07e7df0b-b830-400e-9661-3a1d799675f9, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ] was cancelled
I/WM-WorkerWrapper(18793): java.util.concurrent.CancellationException: Task was cancelled.
I/WM-WorkerWrapper(18793): 	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1184)
I/WM-WorkerWrapper(18793): 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:514)

After paused success, resume not work for me
When resume this log appear

> not found partial downloaded data, this task cannot be resumed
