### ISSUE TITLE
This plugin and location plugin cannot run together.

### ISSUE THREAD

**Issue by aronnelson** [fluttercommunity/flutter_downloader#106]
As soon as I try to download I get these error. Alone they work fine.

W/WM-WorkSpec( 7099): Backoff delay duration less than minimum value
E/MethodChannel#vn.hunghd/downloader( 7099): Failed to handle method call
E/MethodChannel#vn.hunghd/downloader( 7099): java.lang.IllegalStateException: WorkManager is not initialized properly.  The most likely cause is that you disabled WorkManagerInitializer in your manifest but forgot to call WorkManager#initialize in your Application#onCreate or a ContentProvider.
E/MethodChannel#vn.hunghd/downloader( 7099): 	at androidx.work.WorkManager.getInstance(WorkManager.java:161)
E/MethodChannel#vn.hunghd/downloader( 7099): 	at vn.hunghd.flutterdownloader.FlutterDownloaderPlugin.enqueue(FlutterDownloaderPlugin.java:176)
E/MethodChannel#vn.hunghd/downloader( 7099): 	at vn.hunghd.flutterdownloader.FlutterDownloaderPlugin.onMethodCall(FlutterDownloaderPlugin.java:73)
E/MethodChannel#vn.hunghd/downloader( 7099): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#vn.hunghd/downloader( 7099): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#vn.hunghd/downloader( 7099): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/MethodChannel#vn.hunghd/downloader( 7099): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#vn.hunghd/downloader( 7099): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#vn.hunghd/downloader( 7099): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#vn.hunghd/downloader( 7099): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#vn.hunghd/downloader( 7099): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#vn.hunghd/downloader( 7099): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#vn.hunghd/downloader( 7099): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/flutter ( 7099): Download task is failed with reason(WorkManager is not initialized properly.  The most likely cause is that you disabled WorkManagerInitializer in your manifest but forgot to call WorkManager#initialize in your Application#onCreate or a ContentProvider.)

**Comment by aronnelson** [comment]
I cannot add this line to manifest without error
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace" />

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugBuildConfig'.
> org.xml.sax.SAXParseException; systemId: file:/Users/aron/AndroidStudioProjects/flutter_app_onlyloc/android/app/src/main/AndroidManifest.xml; lineNumber: 36; columnNumber: 102; The prefix "tools" for attribute "tools:node" associated with an element type "uses-permission" is not bound.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by hnvn** [comment]
I believe it's fixed in v1.2.2
