### ISSUE TITLE
Support FlutterFragmentActivity

### ISSUE THREAD

**Issue by yunv** [fluttercommunity/flutter_downloader#110]
Currently the plugin only register `BroadcastReceiver` on `FlutterActivity`, but not on `FlutterFragmentActivity`. When using `FlutterFragmentActivity`, app will not receive progress updates. See [FlutterDownloaderPlugin.java](https://github.com/fluttercommunity/flutter_downloader/blob/969c94736a46e6fd8dfe5c52b7be2abbb87aa8dd/android/src/main/java/vn/hunghd/flutterdownloader/FlutterDownloaderPlugin.java#L104)

```
@Override
    public void onActivityStarted(Activity activity) {
        if (activity instanceof FlutterActivity) {
            LocalBroadcastManager.getInstance(context).registerReceiver(updateProcessEventReceiver,
                    new IntentFilter(DownloadWorker.UPDATE_PROCESS_EVENT));
        }
    }
```

**Comment by yunv** [comment]
Thank you for the update. But [FlutterDownloaderPlugin.java#L123](https://github.com/fluttercommunity/flutter_downloader/blob/master/android/src/main/java/vn/hunghd/flutterdownloader/FlutterDownloaderPlugin.java#L123) also needs this modification.

**Comment by hnvn** [comment]
yep, that's my mistake

**Comment by chtsngn** [comment]
> Thank you for the update. But [FlutterDownloaderPlugin.java#L123](https://github.com/fluttercommunity/flutter_downloader/blob/master/android/src/main/java/vn/hunghd/flutterdownloader/FlutterDownloaderPlugin.java#L123) also needs this modification.

I've same problem. How can i fix that?

**Comment by iharshb** [comment]
In android/gradle.properties, 

Add this,
```
android.enableJetifier=true
android.useAndroidX=true
```
