### ISSUE TITLE
example does not work？

### ISSUE THREAD

**Issue by lib-javascript** [fluttercommunity/flutter_downloader#114]
`* Error running Gradle:
ProcessException: Process "C:\Users\yy\Desktop\flutter_downloader-master\example\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\yy\Desktop\flutter_downloader-master\example\android\app\build.gradle' line: 16

* What went wrong:
A problem occurred evaluating project ':app'.
> versionCode not found. Define flutter.versionCode in the local.properties file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
  Command: C:\Users\yy\Desktop\flutter_downloader-master\example\android\gradlew.bat app:properties

Please review your Gradle project setup in the android/ folder.`

**Comment by hnvn** [comment]
Have look at https://github.com/flutter/flutter/issues/18983
