### ISSUE TITLE
download failed on android 9.0

### ISSUE THREAD

**Issue by simeon49** [fluttercommunity/flutter_downloader#119]
it works very well on some android phone, but it failed on android 9.0

```
 Future<String> get _apkLocalPath async {
    // import 'package:path_provider/path_provider.dart';
    final direcory = await getExternalStorageDirectory();
    return direcory.path;
  }

  Future<void> _downloadAndInstallAndroidApk() async {
    if (!await _checkPermission()) {
      return;
    }

    final String savedDir = await _apkLocalPath;
    final taskId = await FlutterDownloader.enqueue(
      url: _apkDownLoadUrl,
      savedDir: savedDir,
      showNotification: true,
      openFileFromNotification: true,
    );

    DownloadProgressDialog downloadProgressDialog = DownloadProgressDialog(_context);
    downloadProgressDialog.show();
    FlutterDownloader.registerCallback((id, status, progress) async {

      if (taskId == id) {
        if (status == DownloadTaskStatus.running) {
          downloadProgressDialog.updateProgress(progress / 100);

        } else if (status == DownloadTaskStatus.complete) {
          downloadProgressDialog.close();
          print('complate!');
          _installAndroidApk();

        } else if (status == DownloadTaskStatus.failed) {
          print('failed!');
          final tasks = await FlutterDownloader.loadTasks();
          print(tasks);
        }
      }
    });
  }
```

log:
> I/flutter ( 2255): Download task is enqueued with id(d41583c8-0240-48a4-ab80-dccf17f2ff8a)
I/flutter ( 2255): failed!
I/flutter ( 2255): [DownloadTask(taskId: d41583c8-0240-48a4-ab80-dccf17f2ff8a, status: DownloadTaskStatus(4), progress: 0, url: http://release.zlya.net/com.zlya.maintenance.apk, filename: null, savedDir: /storage/emulated/0/Android/data/com.xxx.xxxxxx/files)]

AndroidManifest.xml
```
<provider
            android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider"
            android:authorities="${applicationId}.flutter_downloader.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
</provider>
```

**Comment by simeon49** [comment]
android log:
> java.io.IOException: Cleartext HTTP traffic to release.zlya.net not permitted

this is because Starting with Android 9.0 (API level 28), cleartext support is disabled by default.

[https://medium.com/@imstudio/android-8-cleartext-http-traffic-not-permitted-73c1c9e3b803](look here!)

**Comment by hnvn** [comment]
so it works now. I am going to close this issue.

**Comment by nemoryoliver** [comment]
> android log:
> 
> > java.io.IOException: Cleartext HTTP traffic to release.zlya.net not permitted
> 
> this is because Starting with Android 9.0 (API level 28), cleartext support is disabled by default.
> 
> [https://medium.com/@imstudio/android-8-cleartext-http-traffic-not-permitted-73c1c9e3b803](look here!)

**Option 2** from the medium article didn't solve the problem for me. Should this solve the issue?

**Comment by nemoryoliver** [comment]
> https://medium.com/@son.rommer/fix-cleartext-traffic-error-in-android-9-pie-2f4e9e2235e6

I'm still getting the error

**W/System.err(25114): 	at vn.hunghd.flutterdownloader.DownloadWorker.addImageOrVideoToGallery(DownloadWorker.java:471)
W/System.err(25114): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:282)
W/System.err(25114): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:115)
I/WM-WorkerWrapper(25114): Worker result FAILURE for Work [ id=a8edef5d-8ede-4f42-a3ea-b6b6b3f8196f, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]**

**Comment by nemoryoliver** [comment]
I made the fix by modifying **DownloadWorker.java**

```
private void addImageOrVideoToGallery(String fileName, String filePath, String contentType) {
        if (contentType != null && filePath != null && fileName != null) {
            ContentValues values = new ContentValues();
            ContentResolver contentResolver = getApplicationContext().getContentResolver();

            values.put(MediaStore.Images.Media.TITLE, fileName);
            values.put(MediaStore.Images.Media.DISPLAY_NAME, fileName);
            values.put(MediaStore.Images.Media.DESCRIPTION, "");
            values.put(MediaStore.Images.Media.MIME_TYPE, contentType);
            values.put(MediaStore.Images.Media.DATE_ADDED, System.currentTimeMillis());
            values.put(MediaStore.Images.Media.DATE_TAKEN, System.currentTimeMillis());
            values.put(MediaStore.Images.Media.DATA, filePath);

            // FIXED HERE: Must use the correct Content URI for mime-type
            android.net.Uri contentURI = MediaStore.Images.Media.EXTERNAL_CONTENT_URI;
            if (contentType.startsWith("video")) {
                contentURI = MediaStore.Video.Media.EXTERNAL_CONTENT_URI;
            }

            contentResolver.insert(contentURI, values);

            Log.d(TAG, "insert " + values + " to MediaStore");
        }
    }
```

**Comment by zxj17815** [comment]
I still have this problem and I've tried everything you said

**Comment by WajahtAli** [comment]
java.lang.NullPointerException
at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.kt:393)
at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.kt:206)
at androidx.work.Worker$1.run(Worker.java:82)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.lang.Thread.run(Thread.java:764)

 Future download()async{
    var status = await Permission.storage.request();
      final baseStorage = await getExternalStorageDirectory();
      final taskId = await FlutterDownloader.enqueue(
        url: widget.data!,
        savedDir: baseStorage!.path,
        showNotification: true, // show download progress in status bar (for Android)
        openFileFromNotification: true, // click on notification to open downloaded file (for Android)
        allowCellular: true,
        saveInPublicStorage: true,

      );

  }
  
i am facing this error when I try to download in Android 9 on other version it runs fine anyone can help me in this
