### ISSUE TITLE
Package can`t save Videos 

### ISSUE THREAD

**Issue by Ahmed20Salah** [fluttercommunity/flutter_downloader#123]
I`m trying to download videos but after I get a complete notification I can`t find the  video and the download time take no time so I think it doesn`t download at all
I tried to use the example to test but it has the same issue

**Comment by hnvn** [comment]
I believe it's same as #119

**Comment by nemoryoliver** [comment]
Getting the same issue here....

**Comment by nemoryoliver** [comment]
Fixed my issue with this: https://github.com/fluttercommunity/flutter_downloader/issues/119#issuecomment-
