### ISSUE TITLE
how to get file size,thanks

### ISSUE THREAD

**Issue by saviourdog** [fluttercommunity/flutter_downloader#124]
how to get file size,thanks

**Comment by hnvn** [comment]
Try google or stackoverflow. It's not hard to find out:
```
var file = File('the_path_to_your_file.mp4');
print(file.lengthSync()); 
```

**Comment by saviourdog** [comment]
> Try google or stackoverflow. It's not hard to find out:
> 
> ```
> var file = File('the_path_to_your_file.mp4');
> print(file.lengthSync()); 
> ```

I mean the downloading file,do i have to request again by dio?

**Comment by hnvn** [comment]
The plugin can get file size when it starts downloading the file but this information is not saved to DB.

**Comment by saviourdog** [comment]
not cool

**Comment by AhmedNourJamalElDin** [comment]
and how to get it later?
