### ISSUE TITLE
Notification issue 

### ISSUE THREAD

**Issue by romawizard** [fluttercommunity/flutter_downloader#125]
Cant open file from notification, although file was downloaded
![Снимок экрана 2019-09-23 в 11 01 27 ДП](https://user-images.githubusercontent.com/31043679/65409877-89c8b600-ddf1-11e9-8c72-4283b26b335f.png)

**Comment by hnvn** [comment]
Does this issue happen in example project?

**Comment by romawizard** [comment]
> Does this issue happen in example project?

Yes it happen in my real project

**Comment by hnvn** [comment]
I mean the example project in this repository. If this issue only happens in your own project, I guess you have problems with your project configuration.

**Comment by romawizard** [comment]
finally i solved this issue. the problem was in permission. I didn't check it before start download file.

**Comment by romawizard** [comment]
> I mean the example project in this repository. If this issue only happens in your own project, I guess you have problems with your project configuration.

finally i solved this issue. the problem was in permission. I didn't check it before start download file.

**Comment by hnvn** [comment]
Nice. If you solved your issue, I am going to close this issue.
