### ISSUE TITLE
Google access problem stuck download

### ISSUE THREAD

**Issue by yuxizhe** [fluttercommunity/flutter_downloader#129]
In some areas, such as China, we can't access Google, but native Android will try to connect to `Captive Portal Server` under WiFi to determine network connection. The server address defaults to `Google.com`, so in some areas, Android shows disconnect. but in fact, we can access the network.

![image](https://user-images.githubusercontent.com/14990734/65572422-a05e4100-df9a-11e9-982a-e067104928dc.png)

In this case, when I want to download, the process will be stuck in 0, because `NetworkType.CONNECTED` is required, but Android shows a disconnect.

https://github.com/fluttercommunity/flutter_downloader/blob/bc165794239060bd48be2fc158cff4a2eaa6b472/android/src/main/java/vn/hunghd/flutterdownloader/FlutterDownloaderPlugin.java#L143

What about removing this `RequiredNetworkType`?

**Comment by yuxizhe** [comment]
maybe it also the reason for this problem https://github.com/fluttercommunity/flutter_downloader/issues/105

**Comment by bartekpacia** [comment]
Closing. [See this](https://github.com/fluttercommunity/flutter_downloader/pull/130#issuecomment-1221618125) for some context.

**Comment by lxl518000** [comment]
i removed  .setRequiredNetworkType(NetworkType.CONNECTED)  and it works well. on debug mode.

but now work on release mode.

could somenoe help me?
@bartekpacia
