### ISSUE TITLE
Download file that cannot accessible from other application.

### ISSUE THREAD

**Issue by Kyaw-Zin-Thant** [fluttercommunity/flutter_downloader#131]
I developed flutter application that can download video file and display. downloaded video file from my application can be viewed in gallery. But I don't want to view downloaded video file in other application. How can I do?

**Comment by hnvn** [comment]
Save your files into your sandbox application folder

**Comment by Kyaw-Zin-Thant** [comment]
What options do I used in `flutter_downloader`  to save files in sandbox application folder?

**Comment by hnvn** [comment]
`savedDir`

**Comment by Kyaw-Zin-Thant** [comment]
What directory is `sandbox application folder`?

**Comment by Kyaw-Zin-Thant** [comment]
How can I write code to save files to **sandbox application folder**?

**Comment by hnvn** [comment]
https://developer.android.com/guide/topics/data/data-storage#filesInternal

**Comment by yorickreum** [comment]
Did you work this out? Facing exactly the same problem, always running into permissions problems… @Kyaw-Zin-Thant

**Comment by P-B1101** [comment]
i have the same problem. i do save my video file in my application data directory and also change the name and remove the extension and encrypt my video file but the original file that downloaded by library will be shown in gallery. i do remove the file after i encrypted it (obviously the encrypted file is a new file) but still my gallery show original file (as a corrupted file). what is the problem here!?
by the way is use .nomedia file in my target folder, still same result.

**Comment by P-B1101** [comment]
after some research and testing i find that if i use `getApplicationSupportDirectory()` from Provider package the file will be protected and only can be used by my application. 
this will happened if i encrypt and rename my file. i'm going to test it without encryption and if it work i will let u know.

**Comment by P-B1101** [comment]
i test it without encryption and its fine. but i don't know if someone can achieve the files on a rooted android device or not.

**Comment by deepashree-ballodi** [comment]
> after some research and testing i find that if i use `getApplicationSupportDirectory()` from Provider package the file will be protected and only can be used by my application.
> this will happened if i encrypt and rename my file. i'm going to test it without encryption and if it work i will let u know.

Hi,P-B1101 can you please help me how to save video in encrypted format?
