### ISSUE TITLE
Error when run app

### ISSUE THREAD

**Issue by SayedRagab** [fluttercommunity/flutter_downloader#132]
Launching lib/main.dart on Android SDK built for x86 in debug mode...
/home/rootx/Desktop/flutter_linux_v1.7.8+hotfix.4-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_downloader-1.2.2/android/src/main/java/vn/hunghd/flutterdownloader/FlutterDownloaderPlugin.java:106: error: cannot access FragmentActivity
        if (activity instanceof FlutterActivity || activity instanceof FlutterFragmentActivity) {
                                                            ^
  class file for android.support.v4.app.FragmentActivity not found
/home/rootx/Desktop/flutter_linux_v1.7.8+hotfix.4-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_downloader-1.2.2/android/src/main/java/vn/hunghd/flutterdownloader/FlutterDownloaderPlugin.java:124: error: incompatible types: Activity cannot be converted to FlutterFragmentActivity
        if (activity instanceof FlutterActivity || activity instanceof FlutterFragmentActivity) {
                                                   ^
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_downloader:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by kuchro09** [comment]
It's still about  #110

**Comment by devliber** [comment]
Is there a workaround?

It seems flutter_downloader cannot be used right now.

**Comment by chrystoffer** [comment]
I have the same problem :(

**Comment by hnvn** [comment]
I'm working on it. There are many things to do, not only this problem. I am refactoring codes and following new background execution support in Flutter. You can see my works in `refactor` branch and welcome any contribution. My time is quite tight in the week, so I can only work on it at weekend, it can take time until the next release ready. Thanks for your feedback.

**Comment by hnvn** [comment]
I've just pushed some committed in `refactor` branch in order to:
- resolve this issue.
- implement background isolate execution in Android.
If you can't wait for these fix and feature released, you can check it out in that branch.

**Comment by SayedRagab** [comment]
@hnvn Thank you

**Comment by zhongmeizhi** [comment]
I have the same problem :(

**Comment by guangyingmodao** [comment]
https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility

I just did the third step. And it's ok now

In android/gradle.properties, append

android.enableJetifier=true
android.useAndroidX=true

**Comment by FletchM90** [comment]
> https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility
> 
> I just did the third step. And it's ok now
> 
> In android/gradle.properties, append
> 
> android.enableJetifier=true
> android.useAndroidX=true

That did the job. Cheers!
