### ISSUE TITLE
How to broadcast when downloaded

### ISSUE THREAD

**Issue by guangyingmodao** [fluttercommunity/flutter_downloader#133]
Now I download the files to my mobile phone. I can find the files in the file directory, but I can't find them in the file management of my mobile phone. For example, I downloaded a picture, but I couldn't find it in the album. Or, I downloaded a TXT file, but I couldn't find it in the document.

**Comment by hnvn** [comment]
Which platform do you mention?

**Comment by guangyingmodao** [comment]
> Which platform do you mention?

Android
