### ISSUE TITLE
Why Choose Images for Both Images and Videos

### ISSUE THREAD

**Issue by guangyingmodao** [fluttercommunity/flutter_downloader#134]
private void addImageOrVideoToGallery(String fileName, String filePath, String contentType) {
        if (contentType != null && filePath != null && fileName != null) {
            ContentValues values = new ContentValues();
            values.put(MediaStore.Images.Media.TITLE, fileName);
            values.put(MediaStore.Images.Media.DISPLAY_NAME, fileName);
            values.put(MediaStore.Images.Media.DESCRIPTION, "");
            values.put(MediaStore.Images.Media.MIME_TYPE, contentType);
            values.put(MediaStore.Images.Media.DATE_ADDED, System.currentTimeMillis());
            values.put(MediaStore.Images.Media.DATE_TAKEN, System.currentTimeMillis());
            values.put(MediaStore.Images.Media.DATA, filePath);

            Log.d(TAG, "insert " + values + " to MediaStore");

            ContentResolver contentResolver = getApplicationContext().getContentResolver();
            contentResolver.insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, values);
        }
    }

I found Video class in MediaStore. Why not distinguish them?

**Comment by hnvn** [comment]
fixed in v1.3.0
