### ISSUE TITLE
 Build failed with an exception.

### ISSUE THREAD

**Issue by Moonwing** [fluttercommunity/flutter_downloader#138]
As soon as I try to build
FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:preDebugBuild'.
Android dependency 'androidx.core:core' has different version for the compile (1.0.1) and runtime (1.1.0) classpath. You should manually set the same version via DependencyResolution

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 18s

In android/gradle.properties, i have append

android.enableJetifier=true
android.useAndroidX=true

and I have tired then old version before Androidx . but it looks useless ，

other dependencies:
http: ^0.12.0+2 
  chewie: ^0.9.8
  cached_network_image: ^1.1.1
  flutter_webview_plugin: ^0.3.7
  webview_flutter: ^0.3.13
  share: ^0.6.2+1
  fluttertoast: ^3.1.2
  url_launcher: ^5.1.6
  easy_dialog: ^1.0.5
  device_info: ^0.4.0+2
  dio: 3.0.1
  prefs: ^3.0.0
  flutter_email_sender: ^2.0.3
  flutter_spinkit: ^4.0.0

**Comment by marcelgarus** [comment]
Having the same issue.

**Comment by guangyingmodao** [comment]
https://github.com/flutter/flutter/issues/27254

**Comment by hnvn** [comment]
It's version conflict problem in Android, I can downgrade some libraries using in the plugin, but I don't think it is a good idea. You may as well follow the solutions in @guangyingmodao 's comment. Thanks for your feedback.

**Comment by Moonwing** [comment]
thinks @guangyingmodao @hnvn  I  have  resolved this problem just by upgrade gradle to  'com.android.tools.build:gradle:3.3.1'
now I can use this flutter_downloader now   thank you so much
