### ISSUE TITLE
[Question] iOS Integration on AppDelegate.swift

### ISSUE THREAD

**Issue by TimothyY** [fluttercommunity/flutter_downloader#139]
I am not familiar with iOS development.
How to apply the iOS integration on the AppDelegate.swift ? 
The readme section is showing the integration on AppDelegate.h and AppDelegate.m and all I have on my xcode is AppDelegate.swift

**Comment by TimothyY** [comment]
never mind. it is automatically configured. (no need to do anything).
I just haven't handle the file opening after the file is downloaded since iOS don't have file explorer like android.

**Comment by ahadali** [comment]
Hi @TimothyY  can you tell me how did you resolve the issue. I am trying to use flutter_downloader in IOS but getting an error in xcode's AppDelegate.swift "Use of unresolved identifier 'FlutterDownloaderPlugin'", did you recieved the same issue while you configured the plugin in IOS?
I followed the steps as given in the documentation but I am stuck in this error could you please help?

**Comment by hnvn** [comment]
```swift
import flutter_downloader
```

**Comment by ahadali** [comment]
Thanks @hnvn. The ios build is generating but my after clicking the download option in my app, it is crashing and after checking the logs I got these messages : 
`Lost connection to device.
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000112c9b1ab __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000112330f41 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000112ca0372 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x0000000111dd5089 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   Flutter                             0x000000010fd4a96b -[FlutterEngine registrarForPlugin:] + 269
	5   Runner                              0x000000010fad3780 +[GeneratedPluginRegistrant registerWithRegistry:] + 80
	6   Runner                              0x000000010fad3e6c $s6Runner15registerPlugins33_A9240C085443F9A3748492E4015AD82ALL8registryySo21FlutterPluginRegistry_p_tF + 76
	7   Runner                          <…>`
