### ISSUE TITLE
Problem in new Version

### ISSUE THREAD

**Issue by aliyazdi75** [fluttercommunity/flutter_downloader#142]
Hello my friend,
Thanks for  your amazing work on new update.

It has a problem I think:
When you request a download for this method and update `taskId`:
```
  Future<void> _requestDownload(TaskInfo task) async {
    task.taskId = await FlutterDownloader.enqueue(
      url: task.link,
      savedDir: _localPath,
      fileName: task.name,
      showNotification: true,
      openFileFromNotification: true,
    );
  }
```
Before `task.taskId` updating, this `listener` was called:
```
        final task = _tasks.firstWhere((task) => task.taskId == id);
        setState(() {
          task?.status = status;
          task?.progress = progress;
        });
```
and faced a problem because `taskId` was `nulled`.

**Comment by hnvn** [comment]
It's much helpful if you can give me a project to reproduce your issue

**Comment by aliyazdi75** [comment]
For example in `example.lib` if you add `_requestDownload(_tasks[4]);` at the end of `_prepare()`,
I don't why but this scenario happened that `listener` was called with the previous local variable like `_task`
Sorry it's hard to express this situation, and i'm gonna fix it twm.

**Comment by aliyazdi75** [comment]
Please add this `IsolateNameServer.removePortNameMapping('downloader_send_port');` to `dispose()` method.

**Comment by aliyazdi75** [comment]
Have you seen this my friend?

**Comment by hnvn** [comment]
How can I help you?

**Comment by aliyazdi75** [comment]
If you mind add this to example dispose:

> Please add this IsolateNameServer.removePortNameMapping('downloader_send_port'); to dispose() method.
