### ISSUE TITLE
Problem with Google Maps Plugin

### ISSUE THREAD

**Issue by gsantiagom** [fluttercommunity/flutter_downloader#145]
I'm having a problem with Google Maps Plugin, but perhaps happens with other plugins.
My app builds, installs and executes succesfully, but when I enqueue the download I get the error:

E/AndroidRuntime(31823): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
E/AndroidRuntime(31823): 	at io.flutter.plugins.googlemaps.GoogleMapsPlugin.<init>(GoogleMapsPlugin.java:90)
E/AndroidRuntime(31823): 	at io.flutter.plugins.googlemaps.GoogleMapsPlugin.registerWith(GoogleMapsPlugin.java:30)
E/AndroidRuntime(31823): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:31)
E/AndroidRuntime(31823): 	at hnapp.flutter.ptemergencias.com.hnapp.MyApplication.registerWith(MyApplication.java:10)
E/AndroidRuntime(31823): 	at vn.hunghd.flutterdownloader.DownloadWorker.startBackgroundIsolate(DownloadWorker.java:124)
E/AndroidRuntime(31823): 	at vn.hunghd.flutterdownloader.DownloadWorker.access$000(DownloadWorker.java:59)
E/AndroidRuntime(31823): 	at vn.hunghd.flutterdownloader.DownloadWorker$1.run(DownloadWorker.java:97)
E/AndroidRuntime(31823): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(31823): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(31823): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(31823): 	at android.app.ActivityThread.main(ActivityThread.java:6863)
E/AndroidRuntime(31823): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31823): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/AndroidRuntime(31823): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

In the stacktrace you can see that the DownloadWorker execution is followed by a GoogleMapsPlugin one that crashes.

I have been searching in Google for the solution of the issue and I found a clue:

- The Maps call 'application name' in Manifest and this parameter is altered for flutter_downloader.

It is not possible to configure the Plugin Registrant without altering the application - Android:name in manifest?

**Comment by catacs** [comment]
I have a similar problem with another plugin:

```
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference
        at com.pauldemarco.flutterblue.FlutterBluePlugin.<init>(FlutterBluePlugin.java:90)
        at com.pauldemarco.flutterblue.FlutterBluePlugin.registerWith(FlutterBluePlugin.java:81)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:54)
        at com.example.app.MyApplication.registerWith(MyApplication.java:10)
        at vn.hunghd.flutterdownloader.DownloadWorker.startBackgroundIsolate(DownloadWorker.java:124)
        at vn.hunghd.flutterdownloader.DownloadWorker.access$000(DownloadWorker.java:59)
        at vn.hunghd.flutterdownloader.DownloadWorker$1.run(DownloadWorker.java:97)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5525)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

**Comment by hnvn** [comment]
It's more helpful if you can give me a project to reproduce this issue

**Comment by gsantiagom** [comment]
> It's more helpful if you can give me a project to reproduce this issue

I don't have the project in GitHub, perhaps @catacs does...
For now, I have removed the Google Maps plugin and I'm working with googleapis - staticmap images and the applications works again.

**Comment by catacs** [comment]
@hnvn Here you have an example app with the crash in android https://github.com/catacs/test_flutter_downloader_crash. To reproduce the bug you have to press download button.

```
git clone https://github.com/catacs/test_flutter_downloader_crash.git
````

The main problem is registering the plugins with FlutterApplication instead of activity because there are plugins accessing the activity.

**Comment by hnvn** [comment]
Thanks, I will have a look at it this weekend.

**Comment by catacs** [comment]
Yes, loading only flutter_downloader plugin works. I finally used this code to solve the problem

```
import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import vn.hunghd.flutterdownloader.FlutterDownloaderPlugin;

public class MainApplication extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {
  private static final String FLUTTER_DOWNLOADER_REGISTRAR_NAME = "vn.hunghd.flutterdownloader.FlutterDownloaderPlugin";

  @Override
  public void registerWith(PluginRegistry registry) {
    if (registry.hasPlugin(FLUTTER_DOWNLOADER_REGISTRAR_NAME))
      FlutterDownloaderPlugin.registerWith(registry.registrarFor(FLUTTER_DOWNLOADER_REGISTRAR_NAME));
  }
}

```

**Comment by hnvn** [comment]
So this issue can be closed now?
