### ISSUE TITLE
Version 1.3.x crash on IOS when working with flutter_inappbrowser

### ISSUE THREAD

**Issue by TimothyY** [fluttercommunity/flutter_downloader#149]
The android version of the app is working just fine. The crash only occured on ios app.

When compiling and running the ios app via android studio i get:
**Lost connection on phone**

When compiling and running the ios app via xcode I get:

**Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/user/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappbrowser-1.2.1/ios/Classes/FlutterWebViewFactory.swift, line 25
2019-10-22 17:44:48.289006+0700 Runner[360:13751] Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/user/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappbrowser-1.2.1/ios/Classes/FlutterWebViewFactory.swift, line 25**

This was tested on iPhone 6 (real device) - ios 12.4.2 and iPhone 8 (simulator) - ios 13.1

For now I'm using flutter_downloader 1.2.2 and it works fine.

Here is a repo that I create to show case the issue (navigate to the webview by clicking the title):
**https://github.com/TimothyY/downloader_inappbrowser.git**

**Comment by shijinliang** [comment]
I have a similar problem.

**Comment by hnvn** [comment]
Try modify your `AppDelegate` like this:
```objective-c
@implementation AppDelegate

void registerPlugins(NSObject<FlutterPluginRegistry>* registry) {
  [GeneratedPluginRegistrant registerWithRegistry:registry];
    [FlutterDownloaderPlugin registerWithRegistrar:[registry registrarForPlugin:@"vn.hunghd.flutter_downloader"]];
}

- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  [GeneratedPluginRegistrant registerWithRegistry:self];
  [FlutterDownloaderPlugin setPluginRegistrantCallback:registerPlugins];
  // Override point for customization after application launch.
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}
```
I uses Objective-C, you may as well convert it to Swift yourself

**Comment by TimothyY** [comment]
I am having difficulty translating it into swift, can someone post their version of working appdelegate.swift? 

Also I am not sure the problem is because of failing to set the plugin.
Here is my **AppDelegate.swift** which is working just fine as long I am not importing the webview plugin.
==========================
import UIKit
import Flutter
import flutter_downloader

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    FlutterDownloaderPlugin.setPluginRegistrantCallback(registerPlugins)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

private func registerPlugins(registry: FlutterPluginRegistry) {
    GeneratedPluginRegistrant.register(with: registry)
}

**Comment by jjjachyty** [comment]
i use your code can setup,but when refresh Lost connection to device @TimothyY

**Comment by TimothyY** [comment]
@jjjachyty to be honest I'm not sure about my AppDelegate.swift since I don't have much ios experience. It will be great if someone with more knowledge share their AppDelegate.swift here.

For my stable project, I am currently using flutter_downloader 1.2.2 with no extra setup at all (code below) and it works for me. 

```
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

private func registerPlugins(registry: FlutterPluginRegistry) {
    GeneratedPluginRegistrant.register(with: registry)
}
```

**Comment by easazade** [comment]
if you get this error : 
`ios using swift, build error: A C function pointer can only be formed from a reference to a 'func' or a literal closure`

use this code for your AppDelegate.swift

```swift
import UIKit
import Flutter
import flutter_downloader

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    FlutterDownloaderPlugin.setPluginRegistrantCallback({ registry in
         FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "vn.hunghd.flutter_downloader")!)
         GeneratedPluginRegistrant.register(with: registry)
    })
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```
