### ISSUE TITLE
flutter_download conflict with barscan_code

### ISSUE THREAD

**Issue by JiweiMaster** [fluttercommunity/flutter_downloader#159]
java.lang.IllegalStateException: registrar.activity() must not be null
E/AndroidRuntime(13368): 	at com.apptreesoftware.barcodescan.BarcodeScanPlugin$Companion.registerWith(BarcodeScanPlugin.kt:19)
E/AndroidRuntime(13368): 	at com.apptreesoftware.barcodescan.BarcodeScanPlugin.registerWith(BarcodeScanPlugin.kt)
E/AndroidRuntime(13368): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:24)
E/AndroidRuntime(13368): 	at com.sap.sj_transport.MyApplication.registerWith(MyApplication.java:10)
E/AndroidRuntime(13368): 	at vn.hunghd.flutterdownloader.DownloadWorker.startBackgroundIsolate(DownloadWorker.java:124)
E/AndroidRuntime(13368): 	at vn.hunghd.flutterdownloader.DownloadWorker.access$000(DownloadWorker.java:59)
E/AndroidRuntime(13368): 	at vn.hunghd.flutterdownloader.DownloadWorker$1.run(DownloadWorker.java:97)
E/AndroidRuntime(13368): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime(13368): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(13368): 	at android.os.Looper.loop(Looper.java:159)
E/AndroidRuntime(13368): 	at android.app.ActivityThread.main(ActivityThread.java:6364)
E/AndroidRuntime(13368): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13368): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
E/AndroidRuntime(13368): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)

**Comment by JiweiMaster** [comment]
when  creating a Application extends FlutterApplication implements PluginRegistrantCallback,

**Comment by JiweiMaster** [comment]
when do so complex operation

**Comment by hnvn** [comment]
Have look at this [comment ](https://github.com/fluttercommunity/flutter_downloader/issues/145#issuecomment-546845051)for solution and this [comment ](https://github.com/fluttercommunity/flutter_downloader/issues/158#issuecomment-548248836)for explanation

**Comment by JiweiMaster** [comment]
thanks , it works
