### ISSUE TITLE
Cannot use the plugin

### ISSUE THREAD

**Issue by sajadj313** [fluttercommunity/flutter_downloader#160]
As mentioned in the plugin documentation, I installed the plugin in flutter and did the configuration for Android.

This is my custom flutter application class which I newly created :
`public class CustomFlutterApp extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {
    @Override
    public void registerWith(PluginRegistry registry) {
        GeneratedPluginRegistrant.registerWith(registry);
    }
}`

My main activity class is in a separate file (which was already existing):

`public class MainActivity extends FlutterActivity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);
  }
}`

Now in the flutter side, I initialize the plugin and enqueue a download task like this:

` await FlutterDownloader.initialize();

    final String dirPath =
        path

    Directory dir = Directory(dirPath);

    if (!dir.existsSync()) {
      dir.createSync(recursive: true);
    }

    final taskId = await FlutterDownloader.enqueue(
        url: 'http://some-url.txt',
        savedDir: dirPath,
        showNotification: true,
        openFileFromNotification: false);`

But as soon as the enqueue method is hit, this exception is thrown and the app is crashed:

`
E/UncaughtException(18958): java.lang.IllegalStateException: registrar.activity() must not be null
E/UncaughtException(18958): 	at co.paystack.flutterpaystack.FlutterPaystackPlugin$Companion.registerWith(FlutterPaystackPlugin.kt:18)
E/UncaughtException(18958): 	at co.paystack.flutterpaystack.FlutterPaystackPlugin.registerWith(Unknown Source:2)
E/UncaughtException(18958): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:30)
E/UncaughtException(18958): 	at xxxx.CustomFlutterApp.registerWith(CustomFlutterApp.java:10)
E/UncaughtException(18958): 	at vn.hunghd.flutterdownloader.DownloadWorker.startBackgroundIsolate(DownloadWorker.java:124)
E/UncaughtException(18958): 	at vn.hunghd.flutterdownloader.DownloadWorker.access$000(DownloadWorker.java:59)
E/UncaughtException(18958): 	at vn.hunghd.flutterdownloader.DownloadWorker$1.run(DownloadWorker.java:97)
E/UncaughtException(18958): 	at android.os.Handler.handleCallback(Handler.java:790)
E/UncaughtException(18958): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/UncaughtException(18958): 	at android.os.Looper.loop(Looper.java:164)
E/UncaughtException(18958): 	at android.app.ActivityThread.main(ActivityThread.java:7000)
E/UncaughtException(18958): 	at java.lang.reflect.Method.invoke(Native Method)
E/UncaughtException(18958): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
E/UncaughtException(18958): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
`

As a workaround, I tried doing the Android configuration in the same MainActivity.java file (which is this)

`
public class MainActivity extends FlutterActivity implements PluginRegistry.PluginRegistrantCallback {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);
  }

  @Override
  public void registerWith(PluginRegistry registry) {
    GeneratedPluginRegistrant.registerWith(registry);
  }

}
`

but it throws me this error
`E/AndroidRuntime(23158): java.lang.AssertionError: The Application must be implemented PluginRegistrantCallback
E/AndroidRuntime(23158): 	at vn.hunghd.flutterdownloader.DownloadWorker.startBackgroundIsolate(DownloadWorker.java:106)
E/AndroidRuntime(23158): 	at vn.hunghd.flutterdownloader.DownloadWorker.access$000(DownloadWorker.java:59)
E/AndroidRuntime(23158): 	at vn.hunghd.flutterdownloader.DownloadWorker$1.run(DownloadWorker.java:97)
E/AndroidRuntime(23158): 	at android.os.Handler.handleCallback(Handler.java:790)
E/AndroidRuntime(23158): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(23158): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(23158): 	at android.app.ActivityThread.main(ActivityThread.java:7000)
E/AndroidRuntime(23158): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23158): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
E/AndroidRuntime(23158): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)`

Can anyone describe why this is happening?
Thank you

**Comment by hnvn** [comment]
Have a look at #145

**Comment by sajadj313** [comment]
Thank you! It worked =D
