### ISSUE TITLE
downloadCallback will not be call alltime

### ISSUE THREAD

**Issue by tomnattle** [fluttercommunity/flutter_downloader#161]
FlutterDownloader.registerCallback(downloadCallback);

static void downloadCallback(
      String id, DownloadTaskStatus status, int progress) {
    print('task ($id) is in status ($status) and process ($progress)');
    final SendPort send =
        IsolateNameServer.lookupPortByName('downloader_send_port');
    send.send([id, status, progress]);
  }

sometimes downloadCallback is called,sometime not

**logs**

D/InputMethodManager(19519): prepareNavigationBarInfo() DecorView@c194fe2[MainActivity]
D/InputMethodManager(19519): getNavigationBarColor() -855310
D/skia    (19519): --- Failed to create image decoder with message 'unimplemented'
D/skia    (19519): --- Failed to create image decoder with message 'unimplemented'
D/skia    (19519): --- Failed to create image decoder with message 'unimplemented'
D/skia    (19519): --- Failed to create image decoder with message 'unimplemented'
D/skia    (19519): --- Failed to create image decoder with message 'unimplemented'
D/skia    (19519): --- Failed to create image decoder with message 'unimplemented'
D/DownloadWorker(19519): File downloaded
I/WM-WorkerWrapper(19519): Worker result SUCCESS for Work [ id=d25bbc06-4ff2-4e62-a996-aa20cfe273d3, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]
D/ConnectivityManager(19519): unregisterNetworkCallback; CallingUid : 10343, CallingPid : 19519

**Comment by hnvn** [comment]
Does it happen on the [example](https://github.com/fluttercommunity/flutter_downloader/tree/master/example) project?

**Comment by hnvn** [comment]
I am going to close this issue if you need no more help

**Comment by vishwajit76** [comment]
> Does it happen on the [example](https://github.com/fluttercommunity/flutter_downloader/tree/master/example) project?

not working on flutter v1.22 or later

logs::

D/DownloadWorker(12967): File downloaded
I/WM-WorkerWrapper(12967): Worker result SUCCESS for Work [ id=64fd16b7-b1ab-427d-aae5-226ffe33fade, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]
