### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by tjswk2008** [fluttercommunity/flutter_downloader#162]
DownloadTaskStatus starts from 1, then 2 and finally goes to 4.
BTW, I can download the file from the download url.

**Comment by hnvn** [comment]
I need more information, some log messages are much helpful

**Comment by tjswk2008** [comment]
I can't see any log. Below is my code:

final taskId = await FlutterDownloader.enqueue(
        url: downLoadUrl + '/app-release.apk',
        savedDir: path,
        showNotification: true,
        openFileFromNotification: true
    );
    FlutterDownloader.registerCallback((id, status, progress) {
      if (taskId == id && status == DownloadTaskStatus.complete) {
        OpenFile.open(path + '/app-release.apk');
      } else if (status == DownloadTaskStatus.failed) {
        YaCaiUtil.getInstance().showMsg('Download Failed');
      }
    });
  }

**Comment by hnvn** [comment]
Can you reproduce this issue with the [example ](https://github.com/fluttercommunity/flutter_downloader/tree/master/example)project?

**Comment by tjswk2008** [comment]
the example project is not working on my pc
![image](https://user-images.githubusercontent.com/17583754/68177246-acd6b000-ffc2-11e9-9f1b-98b40c454398.png)

**Comment by hnvn** [comment]
Try to google: https://stackoverflow.com/questions/30045417/android-gradle-could-not-reserve-enough-space-for-object-heap

**Comment by tjswk2008** [comment]
error msg:
java.io.FileNotFoundException: /storage/emulated/0/app-release.apk (Permission denied)

**Comment by hnvn** [comment]
Where do you save your files? if you save it in the external storage, you need to request permission to write data on it.

**Comment by hnvn** [comment]
Do you need more supports? If not, I will close this issue?
