### ISSUE TITLE
Required configuration problem

### ISSUE THREAD

**Issue by lxcyha** [fluttercommunity/flutter_downloader#165]
As I add MyApplication to the same dir of MainActivity.java and then build it. throw beblow error 
error: cannot find symbol
        GeneratedPluginRegistrant.registerWith(registry);
        ^

And when I import io.flutter.plugins.GeneratedPluginRegistrant, throw below error 
Didn't find class "com.name.project.MyApplication

**Comment by hnvn** [comment]
Have a look at the [example ](https://github.com/fluttercommunity/flutter_downloader/tree/master/example/android)project
