### ISSUE TITLE
Flutter downloader throws assertion exception

### ISSUE THREAD

**Issue by snehil2112** [fluttercommunity/flutter_downloader#172]
this is my **MainActivity.java**

package com.sandm.flutter_app;

import android.os.Bundle;
import io.flutter.app.FlutterActivity;
import io.flutter.plugins.GeneratedPluginRegistrant;
import vn.hunghd.flutterdownloader.FlutterDownloaderPlugin;

public class MainActivity extends FlutterActivity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);
  }
}

This is MyApplication.java

package com.sandm.flutter_app;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugins.GeneratedPluginRegistrant;
import vn.hunghd.flutterdownloader.FlutterDownloaderPlugin;

public class MyApplication extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {
    @java.lang.Override
    public void registerWith(PluginRegistry pluginRegistry) {
        GeneratedPluginRegistrant.registerWith(pluginRegistry);
    }
}

manifest.xml

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.sandm.flutter_app">

    

    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="flutter_app"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <provider
            android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider"
            android:authorities="${applicationId}.flutter_downloader.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>
        <provider
            android:name="androidx.work.impl.WorkManagerInitializer"
            android:authorities="${applicationId}.workmanager-init"
            android:enabled="false"
            android:exported="false" />

        <provider
            android:name="vn.hunghd.flutterdownloader.FlutterDownloaderInitializer"
            android:authorities="${applicationId}.flutter-downloader-init"
            android:exported="false">
            
            <meta-data
                android:name="vn.hunghd.flutterdownloader.MAX_CONCURRENT_TASKS"
                android:value="5" />
        </provider>
    </application>
</manifest>

main.dart has the same code as your example but still it gives AssertionException:

Backoff delay duration less than minimum value
I/flutter (30484): Download task is enqueued with id(76149b09-d120-4902-a356-4f8cb60307e3)
D/AndroidRuntime(30484): Shutting down VM
E/AndroidRuntime(30484): FATAL EXCEPTION: main
E/AndroidRuntime(30484): Process: com.sandm.flutter_app, PID: 30484
E/AndroidRuntime(30484): java.lang.AssertionError: The Application must be implemented PluginRegistrantCallback
E/AndroidRuntime(30484): 	at vn.hunghd.flutterdownloader.DownloadWorker.startBackgroundIsolate(DownloadWorker.java:106)
E/AndroidRuntime(30484): 	at vn.hunghd.flutterdownloader.DownloadWorker.access$000(DownloadWorker.java:59)
E/AndroidRuntime(30484): 	at vn.hunghd.flutterdownloader.DownloadWorker$1.run(DownloadWorker.java:97)
E/AndroidRuntime(30484): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(30484): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(30484): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(30484): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime(30484): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30484): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(30484): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process (30484): Sending signal. PID: 30484 SIG: 9

**Comment by hnvn** [comment]
Document said:
>And update AndroidManifest.xml
  ```xml
  <!-- AndroidManifest.xml -->
  <application
          android:name=".MyApplication"
          ....>
  ```

**Comment by snehil2112** [comment]
Thank you so much my issue is solved.
