### ISSUE TITLE
'package:flutter_downloader/src/downloader.dart': Failed assertion: line 70 pos 12: 'Directory(savedDir).existsSync()': is not t

### ISSUE THREAD

**Issue by guangming21** [fluttercommunity/flutter_downloader#173]
'package:flutter_downloader/src/downloader.dart': Failed assertion: line 70 pos 12: 'Directory(savedDir).existsSync()': is not t

how to fix this

**Comment by hnvn** [comment]
The directory that you pass in this function isn't existed, just create it.

**Comment by erperejildo** [comment]
> The directory that you pass in this function isn't existed, just create it.

how do we know this? Also the documentation mentions this:

> You have to save your downloaded files in external storage

What about if the user doesn't have any external storage?

**Comment by vikivyas** [comment]
@hnvn What about if the user doesn't have The directory? As app developer we might know which name we have given or but how users will know that.
