### ISSUE TITLE
iOS 按照那你的配置设置，奔溃

### ISSUE THREAD

**Issue by HanQiGod** [fluttercommunity/flutter_downloader#175]
大佬，我按照你的文档配置，结果奔溃在 FlutterDownloaderPlugin.m 文件里的下面方法：
- (void)startBackgroundIsolate:(int64_t)handle {
    NSLog(@"startBackgroundIsolate");
    FlutterCallbackInformation *info = [FlutterCallbackCache lookupCallbackInformation:handle];
    NSAssert(info != nil, @"failed to find callback");
    NSString *entrypoint = info.callbackName;
    NSString *uri = info.callbackLibraryPath;
    [_headlessRunner runWithEntrypoint:entrypoint libraryURI:uri];  // 奔溃在这里
    NSAssert(registerPlugins != nil, @"failed to set registerPlugins");
    
    // Once our headless runner has been started, we need to register the application's plugins
    // with the runner in order for them to work on the background isolate. `registerPlugins` is
    // a callback set from AppDelegate.m in the main application. This callback should register
    // all relevant plugins (excluding those which require UI).
    registerPlugins(_headlessRunner);
    [_registrar addMethodCallDelegate:self channel:_callbackChannel];
}

大佬看看怎么回事？

**Comment by hnvn** [comment]
Please use English

**Comment by HanQiGod** [comment]
IOS follows your configuration Settings and crashes:
Bosses, I according to the result of your document configuration, melt in "FlutterDownloaderPlugin.m" files in the following ways:

`(void)startBackgroundIsolate:(int64_t)handle {
NSLog(@"startBackgroundIsolate");
FlutterCallbackInformation *info = [FlutterCallbackCache lookupCallbackInformation:handle];
NSAssert(info != nil, @"failed to find callback");
NSString *entrypoint = info.callbackName;
NSString *uri = info.callbackLibraryPath;
### [_headlessRunner runWithEntrypoint:entrypoint libraryURI:uri]; /////// Run down here
NSAssert(registerPlugins != nil, @"failed to set registerPlugins");

// Once our headless runner has been started, we need to register the application's plugins
// with the runner in order for them to work on the background isolate. registerPlugins is
// a callback set from AppDelegate.m in the main application. This callback should register
// all relevant plugins (excluding those which require UI).
registerPlugins(_headlessRunner);
[_registrar addMethodCallDelegate:self channel:_callbackChannel];
}`
What's going on?

**Comment by hnvn** [comment]
Sorry, I cannot understand your matter. Here's the [example ](https://github.com/fluttercommunity/flutter_downloader/tree/master/example) project, you may as well have a look at it.
