### ISSUE TITLE
Question : how to get list of all downloads by this package

### ISSUE THREAD

**Issue by mohammadne** [fluttercommunity/flutter_downloader#176]
I am currently use this nice package in my app.
I want to know how can I get List of all downloads ?

**Comment by hnvn** [comment]
I guess `final tasks = await FlutterDownloader.loadTasksWithRawQuery(query: query);` is what you need

**Comment by mohammadne** [comment]
E/SQLiteLog( 2071): (1) no tables specified
E/MethodChannel#vn.hunghd/downloader( 2071): Failed to handle method call
E/MethodChannel#vn.hunghd/downloader( 2071): android.database.sqlite.SQLiteException: no tables specified (code 1): , while compiling: SELECT *
E/MethodChannel#vn.hunghd/downloader( 2071): 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
E/MethodChannel#vn.hunghd/downloader( 2071): 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
E/MethodChannel#vn.hunghd/downloader( 2071): 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
E/MethodChannel#vn.hunghd/downloader( 2071): 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
E/MethodChannel#vn.hunghd/downloader( 2071): 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
E/MethodChannel#vn.hunghd/downloader( 2071): 	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
E/MethodChannel#vn.hunghd/downloader( 2071): 	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)

**Comment by mohammadne** [comment]
I am using:
final tasks = await FlutterDownloader.loadTasksWithRawQuery(query: 'SELECT *');
