### ISSUE TITLE
Hot Restart Crash

### ISSUE THREAD

**Issue by date13** [fluttercommunity/flutter_downloader#182]
when app run under ios simulator 13.2.2,click "Flutter Hot Restart", the app crash and show as below 
methodCallHandler: initialize
startBackgroundIsolate
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c4f02e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50b97b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c4eda8 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff256c9b61 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   Flutter                             0x00000001076b93ea -[FlutterEngine registrarForPlugin:] + 282
	5   Runner                              0x0000000106820bf0 +[GeneratedPluginRegistrant registerWithRegistry:] + 80
	6   Runner                              0x000000010681c0af registerPlugins + 63
	7   Runner                              0x0000000106944ea7 -[FlutterDownloaderPlugin startBackgroundIsolate:] + 823
	8   Ru<…>
Lost connection to device.

Difficult to debug unless you comment out the code 
### FlutterDownloader.initialize();
please provide some work round

**Comment by jaredanderton** [comment]
Having the same issue

**Comment by hnvn** [comment]
Where do you put `FlutterDownloader.initialize()` in your codes? I recommend that it should call one time in the whole of your application life. Have a look at the [example](https://github.com/fluttercommunity/flutter_downloader/tree/master/example) codes for a solution.

**Comment by date13** [comment]
my code as below 

[void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await SystemChrome.setPreferredOrientations(
      [DeviceOrientation.portraitUp, DeviceOrientation.portraitDown]);
 ...
**### await FlutterDownloader.initialize();**
...
](url)

**Comment by jaredanderton** [comment]
Another code example: 
```
void main({bool testing = false}) async {

  if (!isInDebugMode) {
    // keep debugPrint from reaching console in release builds
    debugPrint = (String message, {int wrapWidth}) {};
    // Handles the red screen error message in release builds
    ErrorWidget.builder = (FlutterErrorDetails details) => Container();
  }

  try {
    **await FlutterDownloader.initialize();**
  } catch(e) {
    debugPrint("FlutterDownloader.initialize() failed $e");
  }
  ...
}
```

**Comment by bzh2610** [comment]
I was experiencing the same issue.

In your AppDelegate.swift edit the _registerPlugins()_ function like this :


```
private func registerPlugins(registry: FlutterPluginRegistry) {
   if( !registry.hasPlugin("vn.hunghd.flutter_downloader") ){
       FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "vn.hunghd.flutter_downloader"))
    }
}

```

I think Flutter Downloader gets registered twice in FlutterPluginRegistry on a hot restart: here's an output from Instruments debugger just after a hot restart : 

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Duplicate plugin key: vn.hunghd.flutter_downloader'
*** Assertion failure in -[FlutterEngine registrarForPlugin:], ../../flutter/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm:640	
```

**Comment by jmolins** [comment]
The same solution has also worked for me in Objective-C using the following code:

```
void registerPlugins(NSObject<FlutterPluginRegistry>* registry) {
  if( ![registry hasPlugin:@"vn.hunghd.flutter_downloader"] ) { 
[FlutterDownloaderPlugin registerWithRegistrar:[registry registrarForPlugin:@"vn.hunghd.flutter_downloader"]];
  }
}
```

**Comment by hnvn** [comment]
@bzh2610 's solution will fix this issue. I am going to close it. Thanks for your feedback.

**Comment by albert2169** [comment]
@bzh2610 thanks a lot, it works for me as well.
