### ISSUE TITLE
IOS save video crash

### ISSUE THREAD

**Issue by Nitish-29** [fluttercommunity/flutter_downloader#184]
There is a crash when i try to save video in local storage in iOS. Share video works fine.

**Comment by hnvn** [comment]
How do you save your files on local storage?

**Comment by Nitish-29** [comment]
I downloaded the files using flutter download, once downloaded i opened the video , on button left corner there is share button , it provides option to save, on Saving there is a crash

**Comment by hnvn** [comment]
I mean your source codes, error logs or anything I can trace your problem

**Comment by Nitish-29** [comment]
I ran the sample given in the documentation

**Comment by hnvn** [comment]
The example codes have already saved the downloaded files in the local storage in your device, they are saved in the external storage on Android and `NSDocumentDirectory` on iOS devices.

**Comment by Nitish-29** [comment]
I'm trying to save from NSDocument directort to local to show in gallery , I'm using iphone 5s iOS 12

**Comment by hnvn** [comment]
So that's what I am thinking about. You should be aware that file management on iOS is very restricted. You cannot save your files wherever you want or you cannot save your photos in a folder and expect that they are shown in the gallery app. In my iOS experience, to save photos in the gallery app, you have to use some official frameworks such as PhotoKit, AssetsLibrary. Btw, accessing Photo library permission also needs to be gained before you can do anything in this case.

**Comment by hnvn** [comment]
I am going to close this issue. Your problem is beyond the capability of this plugin, the plugin only focus on handling download files process after files are downloaded, you are responsible to handle and process they in your own codes.

**Comment by Nitish-29** [comment]
When I try to save the video through "Save Video" option(See attachment), I will get error "Lost connection to device" and app crash.
 
I want to save my downloaded video to gallery. Any help please.

![Screenshot 2019-11-27 at 11 36 43 AM](https://user-images.githubusercontent.com/29624798/69699533-29fecc00-110e-11ea-876b-3768d2c4a4be.png)

**Comment by hnvn** [comment]
I guess in this case you are missing some permission descriptions in Info.plist file:
https://stackoverflow.com/a/39749331/3693334

**Comment by Nitish-29** [comment]
Thanks, it worked. It was permission issue.
