### ISSUE TITLE
ios using swift, build error: A C function pointer can only be formed from a reference to a 'func' or a literal closure

### ISSUE THREAD

**Issue by mfkwgizhoujian** [fluttercommunity/flutter_downloader#187]
![image](https://user-images.githubusercontent.com/33543763/69856676-26637480-12c9-11ea-9196-60972c472188.png)
import UIKit
import Flutter
import flutter_downloader

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)

    _// here occurs error, "A C function pointer can only be formed from a reference to a 'func' or a literal closure"_
    FlutterDownloaderPlugin.setPluginRegistrantCallback(registerPlugins)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  private func registerPlugins(registry: FlutterPluginRegistry) {
      GeneratedPluginRegistrant.register(with: registry)
  }
}

**Comment by tomadimitrie** [comment]
Solved it by using a closure: 
```
FlutterDownloaderPlugin.setPluginRegistrantCallback({ registry in
    FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "vn.hunghd.flutter_downloader"))
    GeneratedPluginRegistrant.register(with: registry)
})
```

**Comment by mfkwgizhoujian** [comment]
> Solved it by using a closure:
> 
> ```
> FlutterDownloaderPlugin.setPluginRegistrantCallback({ registry in
>     FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "vn.hunghd.flutter_downloader"))
>     GeneratedPluginRegistrant.register(with: registry)
> })
> ```

it worked. thank u very much.

**Comment by JanMate** [comment]
> Solved it by using a closure:
> 
> ```dart
> FlutterDownloaderPlugin.setPluginRegistrantCallback({ registry in
>     FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "vn.hunghd.flutter_downloader"))
>     GeneratedPluginRegistrant.register(with: registry)
> })
> ```

On Flutter version 1.20.4 and iOS 14 this helped.

**Comment by valterh4ck3r** [comment]
> > Solved it by using a closure:
> > ```dart
> > FlutterDownloaderPlugin.setPluginRegistrantCallback({ registry in
> >     FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "vn.hunghd.flutter_downloader"))
> >     GeneratedPluginRegistrant.register(with: registry)
> > })
> > ```
> 
> On Flutter version 1.20.4 and iOS 14 this helped.

THANK YOU SO MUCH

**Comment by wanosoft** [comment]
> Solved it by using a closure:
> 
> ```dart
> FlutterDownloaderPlugin.setPluginRegistrantCallback({ registry in
>     FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "vn.hunghd.flutter_downloader"))
>     GeneratedPluginRegistrant.register(with: registry)
> })
> ```

It works! Thanks

**Comment by ufukhawk** [comment]
```
 FlutterDownloaderPlugin.setPluginRegistrantCallback({ registry in
            FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "FlutterDownloaderPlugin") as! FlutterPluginRegistrar)
        GeneratedPluginRegistrant.register(with: registry)
        })
```

**Comment by erperejildo** [comment]
> ```dart
> FlutterDownloaderPlugin.setPluginRegistrantCallback({ registry in
>     FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "vn.hunghd.flutter_downloader"))
>     GeneratedPluginRegistrant.register(with: registry)
> })
> ```

Thanks.

Why is not this merged already after all this time?

**Comment by photizzo** [comment]
> Solved it by using a closure:
> 
> ```dart
> FlutterDownloaderPlugin.setPluginRegistrantCallback({ registry in
>     FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "vn.hunghd.flutter_downloader"))
>     GeneratedPluginRegistrant.register(with: registry)
> })
> ```

If this is crashing your app on ios 15.2. Consider using this:
```
GeneratedPluginRegistrant.register(with: self)
    FlutterDownloaderPlugin.setPluginRegistrantCallback({ registry in
        if (!registry.hasPlugin("FlutterDownloaderPlugin")) {
               FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "FlutterDownloaderPlugin")!)
            }
    })
```

**Comment by gjae** [comment]
> > Solved it by using a closure:
> > ```dart
> > FlutterDownloaderPlugin.setPluginRegistrantCallback({ registry in
> >     FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "vn.hunghd.flutter_downloader"))
> >     GeneratedPluginRegistrant.register(with: registry)
> > })
> > ```
> 
> If this is crashing your app on ios 15.2. Consider using this:
> 
> ```
> GeneratedPluginRegistrant.register(with: self)
>     FlutterDownloaderPlugin.setPluginRegistrantCallback({ registry in
>         if (!registry.hasPlugin("FlutterDownloaderPlugin")) {
>                FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "FlutterDownloaderPlugin")!)
>             }
>     })
> ```

This work for me! thanks
