### ISSUE TITLE
error log - WorkerWrapper

### ISSUE THREAD

**Issue by keiraperks** [fluttercommunity/flutter_downloader#192]
I/duction.flutte(31504): Background young concurrent copying GC freed 40940(1948KB) AllocSpace objects, 50(1552KB) LOS objects, 39% free, 4855KB/8068KB, paused 12.724ms total 185.351ms
E/WM-WorkerWrapper(31504): Work [ id=61fc339c-344f-4daa-9676-0d1ec7437a2a, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ] failed because it threw an exception/error
E/WM-WorkerWrapper(31504): java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to read from field 'int vn.hunghd.flutterdownloader.DownloadTask.primaryId' on a null object reference
E/WM-WorkerWrapper(31504): 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
E/WM-WorkerWrapper(31504): 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
E/WM-WorkerWrapper(31504): 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:284)
E/WM-WorkerWrapper(31504): 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
E/WM-WorkerWrapper(31504): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/WM-WorkerWrapper(31504): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/WM-WorkerWrapper(31504): 	at java.lang.Thread.run(Thread.java:919)
E/WM-WorkerWrapper(31504): Caused by: java.lang.NullPointerException: Attempt to read from field 'int vn.hunghd.flutterdownloader.DownloadTask.primaryId' on a null object reference
E/WM-WorkerWrapper(31504): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:181)
E/WM-WorkerWrapper(31504): 	at androidx.work.Worker$1.run(Worker.java:85)
E/WM-WorkerWrapper(31504): 	... 3 more

**Comment by bartekpacia** [comment]
Closing because old, 0 likes and not enough info.
