### ISSUE TITLE
Android configuration

### ISSUE THREAD

**Issue by RafaelR7** [fluttercommunity/flutter_downloader#197]
It was added some new configuration, and my older version is no longer working.
Following the readme it says to create a .java file, and to change the "android:name",
but doing this I got this error: "error: cannot find symbol GeneratedPluginRegistrant.registerWith(registry)", this step is really necessary?

**Comment by hnvn** [comment]
It is necessary to work with background isolate in Dart

**Comment by redabelca** [comment]
> It is necessary to work with background isolate in Dart

if we use
GeneratedPluginRegistrant.registerWith(registry)

in the latest flutter version
we get error.

that what he is talking about. maybe you can test it , and then update the docs, kindly.
