### ISSUE TITLE
MissingPluginException(No implementation found for method initialize on channel vn.hunghd/downloader)

### ISSUE THREAD

**Issue by RafaelR7** [fluttercommunity/flutter_downloader#200]
I got this error `MissingPluginException(No implementation found for method initialize on channel vn.hunghd/downloader)` when I run the widget test, I also had to put  on the main() `TestWidgetsFlutterBinding.ensureInitialized();` and ` await FlutterDownloader.initialize();`
how can I resolve this error?

**Comment by pmrajani** [comment]
@RafaelR7 same issue

**Comment by nemoryoliver** [comment]
I got the same issue. I did **flutter clean** then re-run. got it fixed

**Comment by htetaunglin** [comment]
same issus

**Comment by htetaunglin** [comment]
Same issue. When exit with back key and then reopen to app immediately, I got this error in debug console. I use `flutter_downloader: ^1.4.1`. 
`E/flutter ( 7222): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel vn.hunghd/downloader)
E/flutter ( 7222): #0      MethodChannel._invokeMethod 
package:flutter/…/services/platform_channel.dart:154
E/flutter ( 7222): <asynchronous suspension>
E/flutter ( 7222): #1      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:329
E/flutter ( 7222): #2      FlutterDownloader.initialize 
package:flutter_downloader/src/downloader.dart:37
E/flutter ( 7222): #3      _AsyncAwaitCompleter.start  (dart:async-patch/async_patch.dart:47:6)
E/flutter ( 7222): #4      FlutterDownloader.initialize 
package:flutter_downloader/src/downloader.dart:29
`....

**Comment by P-B1101** [comment]
just need to re-run the project

**Comment by rakib205** [comment]
What is the solution for this? Any idea? I am facing this issue.

**Comment by congfandi** [comment]
this is real bug guys.. please help.. event i close the app and reopen it the app will got crash cs this lib. always say `MissingPluginException(No implementation found for method initialize on channel vn.hunghd/downloader`

**Comment by surveshoeb** [comment]
@congfandi @rakib205 Kindly refer https://github.com/fluttercommunity/flutter_downloader/issues/393#issuecomment-776625511

**Comment by RawanJizzine** [comment]
the solution for this error plzzz help me plzzzz plzzzzz

**Comment by islinjj** [comment]
Hi, I think you can use this to miss this error.
```dart
const MethodChannel('vn.hunghd/downloader').setMockMethodCallHandler((MethodCall methodCall) {});
```
