### ISSUE TITLE
PHPhoto (ios) and MediaStore (android) are not triggered

### ISSUE THREAD

**Issue by rignaneseleo** [fluttercommunity/flutter_downloader#202]
Hi,
I'm using this plugin in combination with **flutter_photo** and I noticed a strange behaviour that can be related to both libraries: if I download a picture using your plugin, it doesn't appear in the list of recent pictures of flutter_photo. It only shows there if I manually rename the file from the File Manager.

I opened an issue [over there](https://github.com/CaiJingLong/flutter_photo/issues/85) and the developer explained that the library actually is based on PHPhoto (ios) and MediaStore (android) so a conclusion might be that your plugin doesn't trigger them. 
May that be possible?

Thanks

**Comment by hnvn** [comment]
It's true in iOS, but not in Android. Here are the codes in Android:
https://github.com/fluttercommunity/flutter_downloader/blob/555187a631f8a7d11c80bf1a2f36c2a8e4c11ef0/android/src/main/java/vn/hunghd/flutterdownloader/DownloadWorker.java#L550

**Comment by rignaneseleo** [comment]
I solved it using my plugin: https://pub.dev/packages/gallerytrigger
