### ISSUE TITLE
can i create a task with multiple files?

### ISSUE THREAD

**Issue by zzAbel** [fluttercommunity/flutter_downloader#206]
i need create a task with multiple files(img、audio、video...),and listen for task completion, Is there any way to achieve this or suggest

**Comment by hnvn** [comment]
What is your use case? Why don't you create a task for a file?

**Comment by zzAbel** [comment]
> What is your use case? Why don't you create a task for a file?

Such as download a m3u8 audio,i want download all the ts files by one task,until ts files download completed,I can understand that the audio download completed，even listen the download progress

**Comment by hnvn** [comment]
I have no plan to support it, it will make project more complicated and harder to maintain. I may as well adapt your use case to single file per a task use case.
