### ISSUE TITLE
call a less  “downloadCallback” function

### ISSUE THREAD

**Issue by rm9233** [fluttercommunity/flutter_downloader#208]
hey, due

 I had use flutter_downloader plugin downloading some file. it's  call a less  “downloadCallback” 
 function . do you have some case can call a lot times? 
 for a example ：
 downloaded 1% , will call "downloadCallback",  second 12% will call, 23%, 34%, 45%  ... ,
 but times is a less,   I hope like 1%, 2%, 3%, 4% ,  call 100 times. 
 how to do it?

**Comment by hnvn** [comment]
It's expected. I don't want to update download progress in every percent units, it will flood the platform channel.
