### ISSUE TITLE
Download Progress Manual Configuration

### ISSUE THREAD

**Issue by varunananddudeja** [fluttercommunity/flutter_downloader#211]
Hi, Can you please make download progress timer to configurable so that progress is shown on lesser intervals than "10".

**Comment by varunananddudeja** [comment]
unable to delete files on iOS by using delete task method. I guess it's because the path of document directory keeps on changing.

**Comment by lengthmin** [comment]
https://github.com/fluttercommunity/flutter_downloader/pull/285

**Comment by bartekpacia** [comment]
Looks like PR #435 would fix this when merged.

**Comment by salmaahhmed** [comment]
https://github.com/fluttercommunity/flutter_downloader/pull/435 merged
