### ISSUE TITLE
'callbackHandle != null': callback must be a top-level or a static function

### ISSUE THREAD

**Issue by BedRockGx** [fluttercommunity/flutter_downloader#215]
APP flash back！！！

Unhandled Exception: 'package:flutter_downloader/src/downloader.dart': Failed assertion: line 388 pos 12: 'callbackHandle != null': callback must be a top-level or a static function

**Comment by josecaseiro** [comment]
Same error for me. I think the documentation ins't clear

**Comment by hnvn** [comment]
Have a look at [example](https://github.com/fluttercommunity/flutter_downloader/tree/master/example) codes

**Comment by lijing89** [comment]
> 看看[示例](https://github.com/fluttercommunity/flutter_downloader/tree/master/example)代码

AndroidManifest.xml  =>
    <application
        android:name=".MyApplication"
        android:label="kuaichuan"
        android:usesCleartextTraffic="true"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"

add MyApplication.java
![屏幕快照 2020-01-12 下午10 08 48](https://user-images.githubusercontent.com/19546352/72220095-3c32ad80-3588-11ea-9c4b-db8f791c2c69.png)

MyApplication.java =>

package xxx.xxxxxx;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugins.GeneratedPluginRegistrant;
import vn.hunghd.flutterdownloader.FlutterDownloaderPlugin;

public class MyApplication extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {
    @Override
    public void registerWith(PluginRegistry registry) {
        GeneratedPluginRegistrant.registerWith(registry);
//        FlutterDownloaderPlugin.registerWith(registry.registrarFor("vn.hunghd.flutterdownloader.FlutterDownloaderPlugin"));
    }
}

but it not work,always is this question.

**Comment by hnvn** [comment]
Have a look at this [document](https://github.com/fluttercommunity/flutter_downloader#update-download-progress)

**Comment by sahil-ingeniousmindslab** [comment]
> APP flash back！！！
> 
> Unhandled Exception: 'package:flutter_downloader/src/downloader.dart': Failed assertion: line 388 pos 12: 'callbackHandle != null': callback must be a top-level or a static function



==>> Solution ...



Future<void> initLocalNotifications() async {
    const iOS = DarwinInitializationSettings();
    const android = AndroidInitializationSettings('@drawable/ic_launcher');
    const settings = InitializationSettings(android: android, iOS: iOS);
    await _localNotifications.initialize(
      settings,
      onDidReceiveNotificationResponse: (playload) {
        var message = RemoteMessage.fromMap(jsonDecode(playload.payload!));
        handleMessage(message);
      },
    );

    final platform = _localNotifications.resolvePlatformSpecificImplementation<
        AndroidFlutterLocalNotificationsPlugin>();
    await platform?.createNotificationChannel(_andriodChannel);
  }

**Comment by sahil-ingeniousmindslab** [comment]
> APP flash back！！！
> 
> Unhandled Exception: 'package:flutter_downloader/src/downloader.dart': Failed assertion: line 388 pos 12: 'callbackHandle != null': callback must be a top-level or a static function

==> Solucation


Future<void> initLocalNotifications() async {
    const iOS = DarwinInitializationSettings();
    const android = AndroidInitializationSettings('@drawable/ic_launcher');
    const settings = InitializationSettings(android: android, iOS: iOS);
    await _localNotifications.initialize(
      settings,
      onDidReceiveNotificationResponse: (playload) {
        var message = RemoteMessage.fromMap(jsonDecode(playload.payload!));
        handleMessage(message);
      },
    );

    final platform = _localNotifications.resolvePlatformSpecificImplementation<
        AndroidFlutterLocalNotificationsPlugin>();
    await platform?.createNotificationChannel(_andriodChannel);
  }

**Comment by sahil-viradiya** [comment]
> APP flash back！！！
> 
> Unhandled Exception: 'package:flutter_downloader/src/downloader.dart': Failed assertion: line 388 pos 12: 'callbackHandle != null': callback must be a top-level or a static function


==> Solucation


Future<void> initLocalNotifications() async {
    const iOS = DarwinInitializationSettings();
    const android = AndroidInitializationSettings('@drawable/ic_launcher');
    const settings = InitializationSettings(android: android, iOS: iOS);
    await _localNotifications.initialize(
      settings,
      onDidReceiveNotificationResponse: (playload) {
        var message = RemoteMessage.fromMap(jsonDecode(playload.payload!));
        handleMessage(message);
      },
    );

    final platform = _localNotifications.resolvePlatformSpecificImplementation<
        AndroidFlutterLocalNotificationsPlugin>();
    await platform?.createNotificationChannel(_andriodChannel);
  }
