### ISSUE TITLE
Flutter App freeze after installing with TestFlight

### ISSUE THREAD

**Issue by iKK001** [fluttercommunity/flutter_downloader#216]
There is an issue that might be related to your Flutter package 'flutter_downloader': My iOS Flutter App does freeze to a grey screen when first launched from TestFlight (i.e. uploaded to Apple App Store and made a TestFlight from it). After installing with TestFlight, the Flutter App on my iOS device freezes (grey screen after LaunchScreen). Could this be a problem with `await FlutterDownloader.initialize();` inside `void main()` ??

Also, the Apple App Store does not pass any App in the review process due to this App freeze at startup.

Again, I am completely not sure if the described problem is related to your flutter_downloader.

I use :
```dart
  flutter_downloader:
   git:
      url: https://github.com/fluttercommunity/flutter_downloader.git
      ref: embedding-v2
```

Pleas don't feel offended when suspecting your flutter_downloader. But since I am completely clueless why the App Freeze after TestFlight install happens, I try to get any information on this way to whether the problem might come from your flutter package.

**Comment by hnvn** [comment]
The proper intialization of this plugin should be:
```
WidgetsFlutterBinding.ensureInitialized();
await FlutterDownloader.initialize();
```
