### ISSUE TITLE
Notification bar shows problems

### ISSUE THREAD

**Issue by mrdong916** [fluttercommunity/flutter_downloader#217]
一次下载很多个文件，会出现文件已经下载完成但是通知栏还是下载中的情况，而且在用户的设备复现的几率不是很高
Download many files at one time, it may happen that the files have been downloaded but the notification bar is still downloading, and the probability of recurrence on the user ’s device is not very high

**Comment by MuraliThangavel** [comment]
any solution found @mrdong916

**Comment by salmaahhmed** [comment]
No reply from @mrdong916
