### ISSUE TITLE
Failed to set registerPlugins on iOS

### ISSUE THREAD

**Issue by anisalibegic** [fluttercommunity/flutter_downloader#219]
Hi! I'm having a problem running an app with this plugin installed. I've done everything I found on the internet and nothing works... If I comment `await FlutterDownloader.initialize();` I can start the application.

**Exception:**
```
[   +2 ms] [DEVICE LOG] 2020-01-09 10:10:13.600816+0100  localhost Runner[14546]: methodCallHandler: initialize
[        ] [DEVICE LOG] 2020-01-09 10:10:13.601151+0100  localhost Runner[14546]: startBackgroundIsolate
[        ] [DEVICE LOG] 2020-01-09 10:10:13.639051+0100  localhost Runner[14546]: (Foundation) *** Assertion failure in -[FlutterDownloaderPlugin startBackgroundIsolate:], /Users/breakpoint/Flutter/.pub-cache/hosted/pub.dartlang.org/flutter_downloader-1.3.4/ios/Classes/FlutterDownloaderPlugin.m:117
[        ] [DEVICE LOG] 2020-01-09 10:10:13.686382+0100  localhost Runner[14546]: (CoreFoundation) *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'failed to set registerPlugins'
[        ] [DEVICE LOG] *** First throw call stack:
[   +4 ms] [DEVICE LOG] (
[        ] [DEVICE LOG]         0   CoreFoundation                      0x000000010a5828db __exceptionPreprocess + 331
[        ] [DEVICE LOG]         1   libobjc.A.dylib                     0x0000000109437ac5 objc_exception_throw + 48
[        ] [DEVICE LOG]         2   CoreFoundation                      0x000000010a582662 +[NSException raise:format:arguments:] + 98
[        ] [DEVICE LOG]         3   Foundation                          0x0000000108b0d76b -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
[        ] [DEVICE LOG]         4   Runner                              0x0000000105e50cfe -[FlutterDownloaderPlugin startBackgroundIsolate:] + 782
[        ] [DEVICE LOG]         5   Runner                              0x0000000105e569eb -[FlutterDownloaderPlugin initializeMethodCall:result:] + 187
[        ] [DEVICE LOG]         6   Runner                              0x0000000105e5a7d0 -[FlutterDownloaderPlugin handleMethodCall:result:] + 256
[        ] [DEVICE LOG]         7   Flutter                             0x0000000106a98f95 __45-[FlutterMethodCha<…>
[  +16 ms] methodCallHandler: initialize
[        ] startBackgroundIsolate
[        ] *** First throw call stack:
[        ] (
[        ]      0   CoreFoundation                      0x000000010a5828db __exceptionPreprocess + 331
[        ]      1   libobjc.A.dylib                     0x0000000109437ac5 objc_exception_throw + 48
[        ]      2   CoreFoundation                      0x000000010a582662 +[NSException raise:format:arguments:] + 98
[        ]      3   Foundation                          0x0000000108b0d76b -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
[        ]      4   Runner                              0x0000000105e50cfe -[FlutterDownloaderPlugin startBackgroundIsolate:] + 782
[        ]      5   Runner                              0x0000000105e569eb -[FlutterDownloaderPlugin initializeMethodCall:result:] + 187
[        ]      6   Runner                              0x0000000105e5a7d0 -[FlutterDownloaderPlugin handleMethodCall:result:] + 256
[        ]      7   Flutter                             0x0000000106a98f95 __45-[FlutterMethodCha<…>
[   +3 ms] Service protocol connection closed.
[        ] Lost connection to device.

```

**main.dart:**
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await FlutterDownloader.initialize();

  ...
}
```

**AppDelegate.m:**
```
#include "AppDelegate.h"
#include "GeneratedPluginRegistrant.h"
#include "FlutterDownloaderPlugin.h"

@implementation AppDelegate

void registerPlugins(NSObject<FlutterPluginRegistry>* registry) {
    [FlutterDownloaderPlugin registerWithRegistrar:[registry registrarForPlugin:@"vn.hunghd.flutter_downloader"]];
}

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    if (@available(iOS 10.0, *)) {
        [UNUserNotificationCenter currentNotificationCenter].delegate = (id<UNUserNotificationCenterDelegate>)self;
    }

    [GeneratedPluginRegistrant registerWithRegistry:self];
    [FlutterDownloaderPlugin setPluginRegistrantCallback:registerPlugins];

    return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

@end
```

**flutter doctor:**
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.13.6 17G10021,
    locale en-BA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Community Edition (version 2019.3.1)
[✓] Connected device (1 available)

• No issues found!
```

**flutter_downloader version:**
```
1.3.4
```

**Comment by hnvn** [comment]
The proper initialization of the plugin should be:
```
WidgetsFlutterBinding.ensureInitialized();
await FlutterDownloader.initialize();
```

**Comment by anisalibegic** [comment]
> The proper initialization of the plugin should be:
> 
> ```
> WidgetsFlutterBinding.ensureInitialized();
> await FlutterDownloader.initialize();
> ```

It already is. This is a screenshot of my main.dart:
![image](https://user-images.githubusercontent.com/12012869/72219991-5c447b80-354c-11ea-8df4-a493067406f3.png)

**Comment by niranjan-b-prajapati** [comment]
I am also facing same issue. 

**Flutter Downloader version :**
`flutter_downloader: ^1.3.4`  


**AppDelegate.m :**
```
#include "AppDelegate.h"
#include "GeneratedPluginRegistrant.h"
#include "FlutterDownloaderPlugin.h"

#import "ACPCore.h"
#import "ACPAnalytics.h"
#import "ACPUserProfile.h"
#import "ACPIdentity.h"
#import "ACPLifecycle.h"
#import "ACPSignal.h"

@implementation AppDelegate

void registerPlugins(NSObject<FlutterPluginRegistry>* registry) {
  //
  // Integration note:
  //
  // In Flutter, in order to work in background isolate, plugins need to register with
  // a special instance of `FlutterEngine` that serves for background execution only.
  // Hence, all (and only) plugins that require background execution feature need to
  // call `registerWithRegistrar` in this function.
  //
  // The default `GeneratedPluginRegistrant` will call `registerWithRegistrar` of all
  // plugins integrated in your application. Hence, if you are using `FlutterDownloaderPlugin`
  // along with other plugins that need UI manipulation, you should register
  // `FlutterDownloaderPlugin` and any 'background' plugins explicitly like this:
  //
  // if (![registry hasPlugin:@"FlutterDownloaderPlugin"]) {
  //    [FlutterDownloaderPlugin registerWithRegistrar:[registry registrarForPlugin:@"FlutterDownloaderPlugin"]];
  // }
  //
  // [GeneratedPluginRegistrant registerWithRegistry:registry];
  // if (![registry hasPlugin:@"FlutterDownloaderPlugin"]) {
  //   [FlutterDownloaderPlugin registerWithRegistrar:[registry registrarForPlugin:@"vn.hunghd.flutter_downloader"]];
  // }

  [FlutterDownloaderPlugin registerWithRegistrar:[registry registrarForPlugin:@"vn.hunghd.flutter_downloader"]];
  
}

- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  [GeneratedPluginRegistrant registerWithRegistry:self];
    [FlutterDownloaderPlugin setPluginRegistrantCallback:registerPlugins];
    [ACPCore setLogLevel:ACPMobileLogLevelDebug];
    [ACPCore configureWithAppId:@"e4c76be5b9e7/376991a8835f/launch-d9474b348673-development"];
    [ACPAnalytics registerExtension];
    [ACPUserProfile registerExtension];
    [ACPIdentity registerExtension];
    [ACPLifecycle registerExtension];
    [ACPSignal registerExtension];
    [ACPCore start:^{
       [ACPCore lifecycleStart:nil];
    }];
  // Override point for customization after application launch.
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

@end

```

**main.dart :** 

```
Future<void> main() async {
  await setupLocator();
  WidgetsFlutterBinding.ensureInitialized();
  await FlutterDownloader.initialize();
  runApp(
    AppTheme(
      child: MyApp(),
      initialThemeKey: MyThemeKeys.LIGHT,
    ),
  );
}
```
**Flutter Doctor :**

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.2 19C57, locale
    en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

Please help me out as I have been trying to fix this from the last few days and the app is near delivery and the file download requirement came last moment.

**Comment by nerdlibfront** [comment]
Is this issue being investigated? I have the same problem.

**Comment by nemoryoliver** [comment]
I am getting the same issue.. crashing when I register the plugin on app delegate

**Comment by anisalibegic** [comment]
@hnvn You should really take a look at this.

**Comment by y-sihyeon** [comment]
@anisalibegic check your "/ios/Runner/AppDelegate.swift" file.
I had the same problem.
I solved it by adding the code below.

"AppDelegate.swift"

`import UIKit
import Flutter
import flutter_downloader

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    FlutterDownloaderPlugin.setPluginRegistrantCallback(registerPlugins)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

private func registerPlugins(registry: FlutterPluginRegistry) {
    if (!registry.hasPlugin("FlutterDownloaderPlugin")) {
       FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "FlutterDownloaderPlugin"))
    }
}`

good lock!!

**Comment by anisalibegic** [comment]
Hello @y-sihyeon. When I created my application I picked the `Objective C` as an iOS language. Following the `flutter_downloader` tutorial I always configured the `AppDelegate.m` file since it's `Objective C`, I never touched `AppDelegate.swift`. Copying your code into the `AppDelegate.swift` file fixes my problem. Thank you very much!

**Comment by nemoryoliver** [comment]
> @anisalibegic check your "/ios/Runner/AppDelegate.swift" file.
> I had the same problem.
> I solved it by adding the code below.
> 
> "AppDelegate.swift"
> 
> ```
> import UIKit
> import Flutter
> import flutter_downloader
> 
> @UIApplicationMain
> @objc class AppDelegate: FlutterAppDelegate {
>   override func application(
>     _ application: UIApplication,
>     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
>   ) -> Bool {
>     GeneratedPluginRegistrant.register(with: self)
>     FlutterDownloaderPlugin.setPluginRegistrantCallback(registerPlugins)
>     return super.application(application, didFinishLaunchingWithOptions: launchOptions)
>   }
> }
> 
> private func registerPlugins(registry: FlutterPluginRegistry) {
>     if (!registry.hasPlugin("FlutterDownloaderPlugin")) {
>        FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "FlutterDownloaderPlugin"))
>     }
> }
> ```
> 
> good luck!!

This is mentioned in the Readme. Even with this I'm experiencing a crash.

**Comment by braysonjohn148** [comment]
> Hello @y-sihyeon. When I created my application I picked the `Objective C` as an iOS language. Following the `flutter_downloader` tutorial I always configured the `AppDelegate.m` file since it's `Objective C`, I never touched `AppDelegate.swift`. Copying your code into the `AppDelegate.swift` file fixes my problem. Thank you very much!

I don't have AppDelegate.swift in my Objective C. Am getting the same error.

**Comment by braysonjohn148** [comment]
> Is this issue being investigated? I have the same problem.
> EDIT: Fixed! Sorry, was my mistake, i was missing the
> `[FlutterDownloaderPlugin setPluginRegistrantCallback:registerPlugins];`
> call.w

how please elaborate.

**Comment by bhargavsejpalindianic** [comment]
> @anisalibegic check your "/ios/Runner/AppDelegate.swift" file.
> I had the same problem.
> I solved it by adding the code below.
> 
> "AppDelegate.swift"
> 
> ```
> import UIKit
> import Flutter
> import flutter_downloader
> 
> @UIApplicationMain
> @objc class AppDelegate: FlutterAppDelegate {
>   override func application(
>     _ application: UIApplication,
>     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
>   ) -> Bool {
>     GeneratedPluginRegistrant.register(with: self)
>     FlutterDownloaderPlugin.setPluginRegistrantCallback(registerPlugins)
>     return super.application(application, didFinishLaunchingWithOptions: launchOptions)
>   }
> }
> 
> private func registerPlugins(registry: FlutterPluginRegistry) {
>     if (!registry.hasPlugin("FlutterDownloaderPlugin")) {
>        FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "FlutterDownloaderPlugin"))
>     }
> }
> ```
> 
> good luck!!

A C function pointer can only be formed from a reference to a 'func' or a literal closure

**Comment by erperejildo** [comment]
> Hello @y-sihyeon. When I created my application I picked the `Objective C` as an iOS language. Following the `flutter_downloader` tutorial I always configured the `AppDelegate.m` file since it's `Objective C`, I never touched `AppDelegate.swift`. Copying your code into the `AppDelegate.swift` file fixes my problem. Thank you very much!

I replaced the content of the file with that and didn't work

**Comment by valterh4ck3r** [comment]
A C function pointer can only be formed from a reference to a 'func' or a literal closure

**Comment by valterh4ck3r** [comment]
> @anisalibegic check your "/ios/Runner/AppDelegate.swift" file.
> I had the same problem.
> I solved it by adding the code below.
> 
> "AppDelegate.swift"
> 
> ```
> import UIKit
> import Flutter
> import flutter_downloader
> 
> @UIApplicationMain
> @objc class AppDelegate: FlutterAppDelegate {
>   override func application(
>     _ application: UIApplication,
>     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
>   ) -> Bool {
>     GeneratedPluginRegistrant.register(with: self)
>     FlutterDownloaderPlugin.setPluginRegistrantCallback(registerPlugins)
>     return super.application(application, didFinishLaunchingWithOptions: launchOptions)
>   }
> }
> 
> private func registerPlugins(registry: FlutterPluginRegistry) {
>     if (!registry.hasPlugin("FlutterDownloaderPlugin")) {
>        FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "FlutterDownloaderPlugin"))
>     }
> }
> ```
> 
> good luck!!

A C function pointer can only be formed from a reference to a 'func' or a literal closure

**Comment by frankenstein19** [comment]
`FlutterDownloaderPlugin.setPluginRegistrantCallback { registry in
    if !registry.hasPlugin("FlutterDownloaderPlugin"),
       let registrar = registry.registrar(forPlugin: "FlutterDownloaderPlugin") {
        FlutterDownloaderPlugin.register(with: registrar)
    }
}`
This solved my issue
