### ISSUE TITLE
How to get the download speed of the m3u8 file?

### ISSUE THREAD

**Issue by lytian** [fluttercommunity/flutter_downloader#221]
For example:

I want to donwload the m3u8 file，It contains a large number of TS files。I can compute download speed of a single TS file,  but it do not represent the download speed of the whole  m3u8 file， Because downloads are concurrent。

**Comment by hnvn** [comment]
I don't have a plan to support this specific use case, just a simple plugin for common file downloading

**Comment by kareemX** [comment]
how can I get download speed for any task?

**Comment by Oklahomawhore** [comment]
> how can I get download speed for any task?

seems not supported
