### ISSUE TITLE
Can not download file other than image file such as pdf,doc,mp4

### ISSUE THREAD

**Issue by didiiswadi** [fluttercommunity/flutter_downloader#224]
Hi,
need help, please

when i download file such as PDF,DOC,MP4 files always fail with log :
I/flutter (24623): Download task is enqueued with id(f991ff90-8d6b-41bb-a535-43ace55a0048)
I/flutter (24623): Background Isolate Callback: task (f991ff90-8d6b-41bb-a535-43ace55a0048) is in status (DownloadTaskStatus(2)) and process (0)
I/flutter (24623): Background Isolate Callback: task (f991ff90-8d6b-41bb-a535-43ace55a0048) is in status (DownloadTaskStatus(4)) and process (-1)
I/flutter (24623): UI Isolate Callback: [f991ff90-8d6b-41bb-a535-43ace55a0048, DownloadTaskStatus(2), 0]
I/flutter (24623): UI Isolate Callback: [f991ff90-8d6b-41bb-a535-43ace55a0048, DownloadTaskStatus(4), -1]

**Comment by HassanDev13** [comment]
Yeah i have the same issue 😔

**Comment by hnvn** [comment]
Any logs from Logcat?

**Comment by didiiswadi** [comment]
I/flutter (24623): Download task is enqueued with id(f991ff90-8d6b-41bb-a535-43ace55a0048)
I/flutter (24623): Background Isolate Callback: task (f991ff90-8d6b-41bb-a535-43ace55a0048) is in status (DownloadTaskStatus(2)) and process (0)
I/flutter (24623): Background Isolate Callback: task (f991ff90-8d6b-41bb-a535-43ace55a0048) is in status (DownloadTaskStatus(4)) and process (-1)
I/flutter (24623): UI Isolate Callback: [f991ff90-8d6b-41bb-a535-43ace55a0048, DownloadTaskStatus(2), 0]
I/flutter (24623): UI Isolate Callback: [f991ff90-8d6b-41bb-a535-43ace55a0048, DownloadTaskStatus(4), -1]

**Comment by hnvn** [comment]
It's not logs from logcat, it's just flutter logs from `print` command.

**Comment by didiiswadi** [comment]
how to show logcat in flutter sir. :)

**Comment by hnvn** [comment]
Open `android` folder of `example` project in Android Studio, that's an android project and you can see Logcat in the bottom tool (along with Run, Terminal,...).

BTW, I believe your issue related to this problem in Android 8: https://stackoverflow.com/a/50834600/3693334

**Comment by hnvn** [comment]
That fixes your issue, doesn't it?

**Comment by didiiswadi** [comment]
i'll try your suggestion after back from work. i will update to you ASAP. thank you sir

**Comment by didiiswadi** [comment]
you are correct sir :)
adding line : 
**android:usesCleartextTraffic="true"**
solving the issue.
thanks alot.

**Comment by didiiswadi** [comment]
> Yeah i have the same issue 😔

hi, 
please add :
**android:usesCleartextTraffic="true"**
to your androidmanifest.xml
will solve the issue

**Comment by hnvn** [comment]
Great. I will close this issue

**Comment by NguyenPhatBG** [comment]
I have a link to download pdf file, but Can't receive file i need although everything working good, Android is ok, iOS failed with some file format download_task.sql, GetStorage.bak or GetStorage.gs. So something wrong everyone? I using newest version flutter_dowloader package.
