### ISSUE TITLE
MissingPluginException(No implementation found for method initialize on channel vn.hunghd/downloader)

### ISSUE THREAD

**Issue by ponytony** [fluttercommunity/flutter_downloader#226]
i click Android's back button, and then open the app again, console would report an error。

that is Exception:
```
I/flutter (17804): MissingPluginException(No implementation found for method initialize on channel vn.hunghd/downloader)
I/flutter (17804): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
I/flutter (17804): <asynchronous suspension>
I/flutter (17804): #1      FlutterDownloader.initialize (package:flutter_downloader/src/downloader.dart:37:10)
I/flutter (17804): #2      _main (package:yiyun/main.dart:272:27)
I/flutter (17804): <asynchronous suspension>
I/flutter (17804): #3      initializeApp.<anonymous closure> (package:yiyun/main.dart:152:11)
I/flutter (17804): #4      _rootRun (dart:async/zone.dart:1126:13)
I/flutter (17804): #5      _CustomZone.run (dart:async/zone.dart:1023:19)
I/flutter (17804): #6      _runZoned (dart:async/zone.dart:1518:10)
I/flutter (17804): #7      runZoned (dart:async/zone.dart:1502:12)
I/flutter (17804): #8      initializeApp (package:yiyun/main.dart:151:3)
I/flutter (17804): #9      main (package:yiyun/main_dev.dart:21:3)
I/flutter (17804): #10     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
I/flutter (17804): #11     _rootRun (dart:async/zone.dart:1126:13)
I/flutter (17804): #12     _CustomZone.run (dart:async/zone.dart:1023:19)
I/flutter (17804): #13     _runZoned (dart:async/zone.dart:1518:10)
I/flutter (17804): #14     runZoned (dart:async/zone.dart:1502:12)
I/flutter (17804): #15     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
```

flutter doctor:
```
[✓] Flutter (Channel unknown, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G87, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.4)
[✓] Connected device (2 available)

• No issues found!

```
mainActivity:
```
import android.os.Bundle

import io.flutter.app.FlutterActivity
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    GeneratedPluginRegistrant.registerWith(this)
  }
}
```
I'm sure the configuration is OK, version of flutter_downloader is 1.4.0.

**Comment by hnvn** [comment]
Have you tried the [example](https://github.com/fluttercommunity/flutter_downloader/tree/master/example) project?

**Comment by ponytony** [comment]
> Have you tried the [example](https://github.com/fluttercommunity/flutter_downloader/tree/master/example) project?

your example is  ok. this is my bug

**Comment by ponytony** [comment]
> Have you tried the [example](https://github.com/fluttercommunity/flutter_downloader/tree/master/example) project?

I had reproduced the problem.
when delete '<meta-data
            android:name="flutterEmbedding"
            android:value="2" /> ' and edit mainActivity.java to old version, the bug can be occur;
so, can you write it to readme.md?and please provide a kotlin version.
i think it is Necessary。

**Comment by ferryhart** [comment]
Any progress with this? I'm also occured it when i close program and re-open it

**Comment by ponytony** [comment]
> Any progress with this? I'm also occured it when i close program and re-open it

listen willpopscope on root page, if listen the event, you should close your application.

**Comment by ponytony** [comment]
> Any progress with this? I'm also occured it when i close program and re-open it

code is exit(0)

**Comment by nemoryoliver** [comment]
I got the same issue. I did **flutter clean** then re-run. got it fixed

**Comment by ferryhart** [comment]
> > Any progress with this? I'm also occured it when i close program and re-open it
> 
> listen willpopscope on root page, if listen the event, you should close your application.

Yes, this is solve my problem actually. Previously, if I normally close the app somehow the plugin is not detected

**Comment by JEuler** [comment]
I am facing this error during the app usual lifecycle, for example, when you have switched to another app and then returning I've got 
Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel vn.hunghd/downloader)
E/flutter ( 5785): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)

Could you reopen the issue?

**Comment by ponytony** [comment]
> I am facing this error during the app usual lifecycle, for example, when you have switched to another app and then returning I've got
> Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel vn.hunghd/downloader)
> E/flutter ( 5785): #0 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
> 
> Could you reopen the issue?

no, i dont have same problem

**Comment by JEuler** [comment]
https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects - I've done this stuff and now all is okay :)
