### ISSUE TITLE
DownloadTaskStatus is failed when download completes

### ISSUE THREAD

**Issue by bbasanta19** [fluttercommunity/flutter_downloader#227]
I am having problem while downloading PDF files. After the download completes with progress of 100,  DownloadTaskStatus(4) is returned which is failed but the file is already downloaded when checked in file explorer. Here is the screenshot of log.

![image](https://user-images.githubusercontent.com/42217505/72887739-63ca0880-3d34-11ea-92a2-7166b9ea2b59.png)

**Comment by hnvn** [comment]
It's better to have native logs from logcat

**Comment by deepss1** [comment]
@bbasanta19 

Can you please tell us if you were able to solve the issue as I am facing the same issue.

Thank you
