### ISSUE TITLE
Cloning the 'example' of the project gives this error

### ISSUE THREAD

**Issue by tanmaypandharipande** [fluttercommunity/flutter_downloader#230]
After clicking on the download icon I am getting this error.

**Background Isolate Callback: task (52dd1de0-63a2-4ec3-ac95-8c2c83fa2b6a) is in status (DownloadTaskStatus(4)) and process (-1)
I/flutter ( 9617): UI Isolate Callback: [52dd1de0-63a2-4ec3-ac95-8c2c83fa2b6a, DownloadTaskStatus(4), -1]**

I am getting the notification -> Filename and Download failed.

I am not able to figure out where I it's going wrong?
Added the provider and permission in AndroidManifest.xml as well.

**Comment by ferryhart** [comment]
What android version you use? In android 9 you must include android:usesCleartextTraffic="true" on your manifest.

**Comment by hnvn** [comment]
I believe that @ferryhart 's suggestion would solve your issue.

**Comment by tanmaypandharipande** [comment]
@ferryhart  Thanks for the suggestion. The problem was getting the external path for download. Actually there was no error regarding it, so wasn't able to figure out the error. Tried changing the path and the file got downloaded.

> Directory tempDir = await getExternalStorageDirectory();
    String tempPath = tempDir.path +"/FolderName/";
    if(!Directory(tempPath).existsSync()){
      Directory(tempPath).createSync(recursive: true);
    }
