### ISSUE TITLE
File type

### ISSUE THREAD

**Issue by marialuizads26** [fluttercommunity/flutter_downloader#233]
When I open a PDF file in my app, it is opened with a DWG program instead of the PDF (Adobe). Does anyone know why and how change this?

**Comment by hnvn** [comment]
When you have many applications that can read a file type, the first time you click to open that file, Android will show you a chooser popup and let you decide what application you prefer to use, in that popup has an "Always use" checkbox, if you tick on that checkbox, this application becomes default application to read the given file type.

**Comment by marialuizads26** [comment]
> When you have many applications that can read a file type, the first time you click to open that file, Android will show you a chooser popup and let you decide what application you prefer to use, in that popup has an "Always use" checkbox, if you tick on that checkbox, this application becomes default application to read the given file type.

The problem is that it only offers DWG programs and does not show Adobe, it is as if it recognizes the PDF file as DWG.
