### ISSUE TITLE
File type

### ISSUE THREAD

**Issue by marialuizads26** [fluttercommunity/flutter_downloader#234]
When I open a PDF file in my app, it is opened with a DWG program instead of the PDF (Adobe). Does anyone know why and how change this?
The problem is that in the popup the android offers only DWG programs and does not show Adobe, it is as if it recognizes the PDF file as DWG.

**Comment by hnvn** [comment]
What happens when you click on that file from a file browser app?

**Comment by marialuizads26** [comment]
> What happens when you click on that file from a file browser app?

It offers de adobe app and not de dwg app.

**Comment by hnvn** [comment]
I guess there's something wrong with the mime-type of these files, you can try to debug the value of `mime_type` from the sqlite database.

**Comment by bartekpacia** [comment]
Closing because it's more than 2 years old. Feel free to create new bug report following the template :)
