### ISSUE TITLE
can not open apk

### ISSUE THREAD

**Issue by weiandebeiying** [fluttercommunity/flutter_downloader#235]
when i Download complete I use FlutterDownloader.open(taskId: id) it tell me Failed assertion: line 327 pos 12: '_initialized': FlutterDownloader.initialize() must be called first,but I was  FlutterDownloader.initialize() in main

**Comment by weiandebeiying** [comment]
flutter_downloader: ^1.4.1

**Comment by JohnnyCrazy** [comment]
How did you solve it @weiandebeiying? Having the same issue currently.

**Comment by weiandebeiying** [comment]
> How did you solve it @weiandebeiying? Having the same issue currently.
see registerCallback's comment

**Comment by weiandebeiying** [comment]
> > How did you solve it @weiandebeiying? Having the same issue currently.
> > see registerCallback's comment
![image](https://user-images.githubusercontent.com/31149748/74098043-57c0b200-4b4e-11ea-99ca-32013e65fdd9.png)
