### ISSUE TITLE
Can not Access class #FlutterEngine  

### ISSUE THREAD

**Issue by IsaacHome** [fluttercommunity/flutter_downloader#236]
Running Gradle task 'assembleDebug'...
e: C:\Users\WinPaPa\AndroidStudioProjects\ch2_mylocal_app\android\app\src\main\kotlin\com\example\ch2_mylocal_app\MainActivity.kt: (4, 19): Unresolved reference: embedding
e: C:\Users\WinPaPa\AndroidStudioProjects\ch2_mylocal_app\android\app\src\main\kotlin\com\example\ch2_mylocal_app\MainActivity.kt: (5, 19): Unresolved reference: embedding
e: C:\Users\WinPaPa\AndroidStudioProjects\ch2_mylocal_app\android\app\src\main\kotlin\com\example\ch2_mylocal_app\MainActivity.kt: (8, 21): Unresolved reference: FlutterActivity
e: C:\Users\WinPaPa\AndroidStudioProjects\ch2_mylocal_app\android\app\src\main\kotlin\com\example\ch2_mylocal_app\MainActivity.kt: (9, 5): 'configureFlutterEngine' overrides nothing
e: C:\Users\WinPaPa\AndroidStudioProjects\ch2_mylocal_app\android\app\src\main\kotlin\com\example\ch2_mylocal_app\MainActivity.kt: (9, 65): Unresolved reference: FlutterEngine
e: C:\Users\WinPaPa\AndroidStudioProjects\ch2_mylocal_app\android\app\src\main\kotlin\com\example\ch2_mylocal_app\MainActivity.kt: (10, 35): Cannot access class 'FlutterEngine'. Check your module classpath for missing or conflicting dependencies

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Finished with error: Gradle task assembleDebug failed with exit code 1[](url)

**Comment by hnvn** [comment]
What Flutter version are you using?

**Comment by bartekpacia** [comment]
not actionable :(
