### ISSUE TITLE
Not work on Android 4.4

### ISSUE THREAD

**Issue by vinhdn** [fluttercommunity/flutter_downloader#237]
I got a message: 

> Could not find class 'android.app.NotificationChannel', referenced from method vn.hunghd.flutterdownloader.DownloadWorker.buildNotification

when I run application on Android device version 4.4.
### flutter_downloader version:

1.3.4

**Comment by hnvn** [comment]
It's not about Android version, it looks like AndroidX migration issue. Make sure that you setup your android project worked with AndroidX properly.

**Comment by vinhdn** [comment]
I setup my android project worked with AndroidX yet.
I tested and It's worked on Android 10, 9.0 and 8.0

**Comment by hnvn** [comment]
Have a lookt at: https://stackoverflow.com/questions/45232457/android-studio-notification-channel-cannot-be-imported

**Comment by hnvn** [comment]
Have you resolved your issue yet?

**Comment by vinhdn** [comment]
No, I haven't @hnvn .
My project using compileSdkVersion 28

**Comment by hnvn** [comment]
Have you tried on the [example project](https://github.com/fluttercommunity/flutter_downloader/tree/master/example) yet?

**Comment by vinhdn** [comment]
No, I haven't. I will try later and send you result. Thanks

**Comment by vinhdn** [comment]
Hi @hnvn, I update to version 1.4.1 and It's work now. Thanks.
