### ISSUE TITLE
DownloadTaskStatus(1)

### ISSUE THREAD

**Issue by vvvliqian** [fluttercommunity/flutter_downloader#241]
download status alwasy 1----DownloadTaskStatus(1), always enqueued.
terminal info:Backoff delay duration less than minimum value
I/flutter ( 7200): Download task is enqueued with id(a5881a91-f26c-4674-90a6-83f65f1fa33c)

**Comment by qiu997018209** [comment]
how do you solve this proble?

**Comment by liudonghua123** [comment]
I have the similar issue https://github.com/fluttercommunity/flutter_downloader/issues/254.
