### ISSUE TITLE
Unrecognized token

### ISSUE THREAD

**Issue by YudizMohitS** [fluttercommunity/flutter_downloader#244]
Hi,

I am using your lib for downloading images but I am not able to get the **file name**, plz check my code if anything I am missing or wrong

```
var taskId = await FlutterDownloader.enqueue(
          url: "http://www.xyz.com/xxx.jpg",
          savedDir: _localPath,
          showNotification: true,
          openFileFromNotification: true);

      print("Task Id " + taskId.toString());

      final tasks = await FlutterDownloader.loadTasksWithRawQuery(
          query: "select * from task where task_id = " + taskId);
      print("Task Download List " + tasks.toString());
```

In android I am getting taker id like 9d05546a-a0ba-4783-aff6-961903b4bbaf
so SQLite gives me this type of error and ios getting blank array from the query so I am not able to get the **file name**.

**Comment by salmaahhmed** [comment]
Will close as the op never replied
