### ISSUE TITLE
Failed assertion: line 74 pos 12: 'Directory(savedDir).existsSync()': is not true.

### ISSUE THREAD

**Issue by baptisteArnaud** [fluttercommunity/flutter_downloader#249]
I'm doing everything like the repo example: 

```
String localPath = (await _findLocalPath()) + Platform.pathSeparator + 'Download';
          print(localPath);
          await FlutterDownloader.enqueue(
            url: "https://cdn.pixabay.com/photo/2016/09/05/10/50/app-1646213_960_720.png",
            savedDir: localPath,
            showNotification: true, // show download progress in status bar (for Android)
            openFileFromNotification: true, // click on notification to open downloaded file (for Android)
          );
```

`localPath` printed value is : 
> /storage/emulated/0/Android/data/com.getinshoot.getinshoot/files/Download

I still have the error:
> Failed assertion: line 74 pos 12: 'Directory(savedDir).existsSync()': is not true.

Any idea what's happening?

**Comment by baptisteArnaud** [comment]
I forgot to actually create this directory before.

```
String localPath = (await _findLocalPath()) + Platform.pathSeparator + 'Download';
          final savedDir = Directory(localPath);
          bool hasExisted = await savedDir.exists();
          if (!hasExisted) {
            savedDir.create();
          }
```

**Comment by ashishkj93** [comment]
> I forgot to actually create this directory before.
> 
> ```
> String localPath = (await _findLocalPath()) + Platform.pathSeparator + 'Download';
>           final savedDir = Directory(localPath);
>           bool hasExisted = await savedDir.exists();
>           if (!hasExisted) {
>             savedDir.create();
>           }
> ```
Failed assertion: line 74 pos 12: 'Directory(savedDir).existsSync()': is not true.

**Comment by divyankkaushik** [comment]
I am having the same error in my project. I am using flutter_insta plugin with  flutter_downloader.
I also checked if the Directory('/storage/emulated/0/Download/').existsSync() is true or not it returns true. And the funny thing is i am saving pdf file in the same folder and it downloads perfectly.
Please help.

**Comment by divyankkaushik** [comment]
My error is solved, i am not adding the fileName parameter that's why the error is happening. 
Must add .mp4 at the end to download video.
Happy coding

**Comment by hiteshsurbhiinfotech** [comment]
Some delay to after getting **localpath** solved my problem.

**Comment by Sahilbhayani** [comment]
just add 
WidgetsFlutterBinding.ensureInitialized();
await FlutterDownloader.initialize();

**Comment by Uvais-Mohammad** [comment]
622a3cf46f1143f89b6c156a9587edc5.m4a
