### ISSUE TITLE
build fails after including package (flutter_downloader: ^1.0.6)

### ISSUE THREAD

**Issue by Apurv2017** [fluttercommunity/flutter_downloader#25]
Getting following error after including package
`flutter_downloader: ^1.0.6` 

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: ...
> 
>   Program type already present: com.google.common.util.concurrent.ListenableFuture

`flutter doctor
`

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.6 17G65, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[!] VS Code (version 1.28.2)
[✓] Connected devices (1 available)

**Comment by hnvn** [comment]
#19

**Comment by Apurv2017** [comment]
@hnvn 
this is working for me

subprojects {
    project.configurations.all {

        exclude group: 'com.google.guava', module: 'failureaccess'


        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "26.1.0"
            }

            if('guava' == details.requested.name) {
                details.useVersion '27.0-android'
            }

        }
    }
}
