### ISSUE TITLE
On download Cancel returns progress=100on version 1.4.1

### ISSUE THREAD

**Issue by surpriso1997** [fluttercommunity/flutter_downloader#255]
While canceling download, the progress value is returned 100.
Found similar issue #37   which is supposed to be fixed in 1.1.5 but still exists in the latest version.

Here is the log:
I/flutter (20434): task id is: 800f3187-d6ce-4305-8b6d-d0599a7af49a
I/flutter (20434): task id from locator: 800f3187-d6ce-4305-8b6d-d0599a7af49a
I/flutter (20434): UI Isolate Callback: [800f3187-d6ce-4305-8b6d-d0599a7af49a, DownloadTaskStatus(2), 0]
I/flutter (20434): progress data: 0
I/flutter (20434): download percentage from locator: 0
I/System  (20434): core_booster, getBoosterConfig = false
I/System  (20434): core_booster, getBoosterConfig = false
I/flutter (20434): UI Isolate Callback: [800f3187-d6ce-4305-8b6d-d0599a7af49a, DownloadTaskStatus(2), 1]
I/flutter (20434): progress data: 1
I/flutter (20434): download percentage from locator: 1
I/flutter (20434): UI Isolate Callback: [800f3187-d6ce-4305-8b6d-d0599a7af49a, DownloadTaskStatus(2), 12]
I/flutter (20434): progress data: 12
I/flutter (20434): download percentage from locator: 12
I/WM-WorkerWrapper(20434): Work [ id=800f3187-d6ce-4305-8b6d-d0599a7af49a, tags={ vn.hunghd.flutterdownloader.DownloadWorker, flutter_download_task } ] was cancelled
I/WM-WorkerWrapper(20434): java.util.concurrent.CancellationException: Task was cancelled.
I/WM-WorkerWrapper(20434): 	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1184)
I/WM-WorkerWrapper(20434): 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:514)
I/WM-WorkerWrapper(20434): 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
I/WM-WorkerWrapper(20434): 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:284)
I/WM-WorkerWrapper(20434): 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
I/WM-WorkerWrapper(20434): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
I/WM-WorkerWrapper(20434): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
I/WM-WorkerWrapper(20434): 	at java.lang.Thread.run(Thread.java:833)
I/flutter (20434): download cancelled::
I/flutter (20434): UI Isolate Callback: [800f3187-d6ce-4305-8b6d-d0599a7af49a, DownloadTaskStatus(5), 100]
I/flutter (20434): progress data: 100
I/flutter (20434): download percentage from locator: 100

**Comment by bartekpacia** [comment]
More than 2 years old, no reproduction steps - I have to close it.
