### ISSUE TITLE
mistake in FlutterDownloaderInitializer.java

### ISSUE THREAD

**Issue by moodstubos** [fluttercommunity/flutter_downloader#26]
https://github.com/fluttercommunity/flutter_downloader/commit/eb953a92183e5e7e4ecd1f165f2f57411111353c#diff-c6d6a94ee56dc0a98facc3b90a5254d1

Line 28: WorkManagerInitializer

I am pretty sure this line must be removed (or completed).

> .pub-cache\hosted\pub.dartlang.org\flutter_downloader-1.1.1\android\src\main\java\vn\hunghd\flutterdownloader\FlutterDownloaderInitializer.java:28: error: ';' expected
        WorkManagerInitializer
                              ^
2 errors
FAILURE: Build failed with an exception.

**Comment by hnvn** [comment]
Oh, that's my silly mistake. I've fixed in v1.1.2 and it will be released today
