### ISSUE TITLE
Add parameter to specify notification title

### ISSUE THREAD

**Issue by BaranMichal25** [fluttercommunity/flutter_downloader#260]
**Background:**
Currently, the plugin uses `fileName` parameter as a title in the Notification. 

**Problem:**
It's often the case that we will want to store our files with their IDs (or something similar) as filename, but display something more user-friendly to users. For example:
We want to store: `sdjb3j45k34.mp3`
but show to user: `Downloading: Queen - We are the champions`

**Proposed Solution:**
Add a `String notificationTitle` parameter to `enqueue()` method and use it for title in the notification.

I would be happy to implement it on Android, if you're up for this feature :)

**Comment by hnvn** [comment]
In order to support this feature, you need to store notification titles in SQLite database and it must modify the current DB schema. You should be aware that and your implementation should not break the current feature.

**Comment by BaranMichal25** [comment]
Right, ok, I don't think the feature is worth the breaking change and risk, so I will pass on it for now :)
