### ISSUE TITLE
README is not correct (the code in iOS Swift version)

### ISSUE THREAD

**Issue by renjiale1214** [fluttercommunity/flutter_downloader#262]
FlutterDownloaderPlugin.setPluginRegistrantCallback(registerPlugins)
This code in Swift5.0 will show error "A C function pointer can only be formed from a reference to a'func' or a literal closure"

It need to change func 'registerPlugins' with a closure like this:

FlutterDownloaderPlugin.setPluginRegistrantCallback({(registry:FlutterPluginRegistry) in
        if (!registry.hasPlugin("FlutterDownloaderPlugin")) {
           FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "FlutterDownloaderPlugin"))
        }
    })

Then I can run program as well.

**Comment by surpriso1997** [comment]
> FlutterDownloaderPlugin.setPluginRegistrantCallback(registerPlugins)
> This code in Swift5.0 will show error "A C function pointer can only be formed from a reference to a'func' or a literal closure"
> 
> It need to change func 'registerPlugins' with a closure like this:
> 
> FlutterDownloaderPlugin.setPluginRegistrantCallback({(registry:FlutterPluginRegistry) in
> if (!registry.hasPlugin("FlutterDownloaderPlugin")) {
> FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "FlutterDownloaderPlugin"))
> }
> })
> 
> Then I can run program as well.

I was trying to set up the library in ios. I followed the docs to setup ios side but notification do not appear while downloading.

**Comment by hnvn** [comment]
Displaying download progress on notification only supports in Android, there's no such thing on iOS.

**Comment by hnvn** [comment]
I think I already made the problem clear. I am going to close this issue.

**Comment by befirst** [comment]
Please update the Swift part of the docs according to this issue

**Comment by andynvt** [comment]
> FlutterDownloaderPlugin.setPluginRegistrantCallback(registerPlugins) This code in Swift5.0 will show error "A C function pointer can only be formed from a reference to a'func' or a literal closure"
> 
> It need to change func 'registerPlugins' with a closure like this:
> 
> FlutterDownloaderPlugin.setPluginRegistrantCallback({(registry:FlutterPluginRegistry) in if (!registry.hasPlugin("FlutterDownloaderPlugin")) { FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "FlutterDownloaderPlugin")) } })
> 
> Then I can run program as well.

Thank you, it works for me
