### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File android.app.Activity.getExternalFilesDir(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by Slhaos7373** [fluttercommunity/flutter_downloader#268]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File android.app.Activity.getExternalFilesDir(java.lang.String)' on a null object reference
E/AndroidRuntime( 5032): 	at io.flutter.plugins.imagepickersaver.ImagePickerSaverPlugin.registerWith(ImagePickerSaverPlugin.java:31)
E/AndroidRuntime( 5032): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:53)
E/AndroidRuntime( 5032): 	at com.jingjiang.liang.yuntuibao.MyApplication.registerWith(MyApplication.java:28)
E/AndroidRuntime( 5032): 	at vn.hunghd.flutterdownloader.DownloadWorker.startBackgroundIsolate(DownloadWorker.java:124)
E/AndroidRuntime( 5032): 	at vn.hunghd.flutterdownloader.DownloadWorker.access$000(DownloadWorker.java:59)
E/AndroidRuntime( 5032): 	at vn.hunghd.flutterdownloader.DownloadWorker$1.run(DownloadWorker.java:97)
E/AndroidRuntime( 5032): 	at android.os.Handler.handleCallback(Handler.java:808)
E/AndroidRuntime( 5032): 	at android.os.Handler.dispatchMessage(Handler.java:101)
E/AndroidRuntime( 5032): 	at android.os.Looper.loop(Looper.java:166)
E/AndroidRuntime( 5032): 	at android.app.ActivityThread.main(ActivityThread.java:7529)
E/AndroidRuntime( 5032): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5032): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/AndroidRuntime( 5032): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
I/Process ( 5032): Sending signal. PID: 5032 SIG: 9
Lost connection to device.

**Comment by hnvn** [comment]
You haven't migrated your project to v2 embedding yet. Check [this document](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)
