### ISSUE TITLE
Bad notification status

### ISSUE THREAD

**Issue by wangbo4020** [fluttercommunity/flutter_downloader#276]
<img width="415" alt="image" src="https://user-images.githubusercontent.com/5559403/78385178-0abd0180-760e-11ea-9f9c-2885cf5c44af.png">

flutter_downloader: 1.4.2
Android 10

<img width="562" alt="image" src="https://user-images.githubusercontent.com/5559403/78385311-393adc80-760e-11ea-98aa-0ebe88962292.png">

**Comment by ChemistryX** [comment]
same for me, any fixes? ;(

**Comment by hnvn** [comment]
I tried it on Android-emulator (Android 10), but I couldn't reproduce it

**Comment by wangbo4020** [comment]
I used the vpn software when downloading, because my network speed was very slow.
