### ISSUE TITLE
[iOS] missing file when completing download

### ISSUE THREAD

**Issue by 781flyingdutchman** [fluttercommunity/flutter_downloader#278]
I use the downloader to download thousands of small files, and on iOS run into an issue where the download completes successfully (and notifies the app as such), yet the downloaded file isn't there.  Right now I simply do a check upon download completion and reschedule the download if the file isn't there, but it's obviously not what the downloader 'contract' states. This issue does not exist on Android.

I build my iOS app via CodeMagic, so I cannot debug iOS very well, and therefore don't really understand where this is going wrong (the code looks fine to me).

**Comment by hnvn** [comment]
There's a problem in iOS that the NSDocument path changes every times the application relaunch. I guess it maybe let to you issue 
https://stackoverflow.com/questions/47864143/document-directory-path-change-when-rebuild-application

**Comment by 781flyingdutchman** [comment]
Pull request #277 is my proposed solution (store only the relative portion of the savedDir on iOS), but it does introduce behavior that's different between iOS and Android, unless we introduce the same change there.  However, that change still doesn't resolve this issue.  We need someone to test why this is happening on an iOS device in debug mode (I can't do that)
