### ISSUE TITLE
dont work on android8

### ISSUE THREAD

**Issue by lyqiai** [fluttercommunity/flutter_downloader#287]
example code dont work on android8~10

**Comment by am1994** [comment]
I had a problem too in android8 and I fixed it by adding this file on Manifest.xml
![sec_file2](https://user-images.githubusercontent.com/17643446/84719010-14e66f00-af72-11ea-9c90-4d7916cf09af.png)
![sec_file](https://user-images.githubusercontent.com/17643446/84719035-23348b00-af72-11ea-94f3-8bfe4fb87115.png)
![sec_file3](https://user-images.githubusercontent.com/17643446/84719065-37788800-af72-11ea-974c-9e397c81ca7c.png)

check more from StackOverflow question:
https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted
