### ISSUE TITLE
Conflict with google_sign_in (ListenableFuture)

### ISSUE THREAD

**Issue by gleesonger** [fluttercommunity/flutter_downloader#293]
When I added the plugin google_sign_in to my project the android build failed with the error 'Duplicate class com.google.common.util.concurrent.ListenableFuture found'. This is not an issue with flutter_downloader but rather a conflict between the dependencies of both plugins.

The fix is to add this line to 'android/app/build.grandle' in the 'dependencies' section:
`implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'`

The solution was found here:
https://stackoverflow.com/questions/56639529/duplicate-class-com-google-common-util-concurrent-listenablefuture-found-in-modu

**Comment by zwz1192511822** [comment]
Encountered the same problem,How do you solve it?

**Comment by bartekpacia** [comment]
No needed anymore. Please use the latest versions of `flutter_downloader` and Flutter.
