### ISSUE TITLE
Flutter desktop(macos, linux, windows) support.

### ISSUE THREAD

**Issue by liudonghua123** [fluttercommunity/flutter_downloader#303]
There are some apps which support multi platforms android/ios/web/macos/linux/windows, hope this package can support them. 😄

**Comment by liudonghua123** [comment]
There is web support issue https://github.com/fluttercommunity/flutter_downloader/issues/222 already.

**Comment by Chuanbin-Wang** [comment]
+1

**Comment by rekire** [comment]
Vote to reopen: Could be fixed with #793

**Comment by bartekpacia** [comment]
@rekire You can do `fixes #391` and `fixes #617` in your PR's description.
