### ISSUE TITLE
unable to download a file .In notification I am getting downloading  failed  .

### ISSUE THREAD

**Issue by Nanika-19** [fluttercommunity/flutter_downloader#304]

**Comment by am1994** [comment]
if u use android 8 so u need adding security file cos issue with HTTP in android 8 and above 
![sec_file2](https://user-images.githubusercontent.com/17643446/84719703-ecf80b00-af73-11ea-8ed7-ee60dcd0bad7.png)
![sec_file](https://user-images.githubusercontent.com/17643446/84719719-f5504600-af73-11ea-9a10-460148aa3162.png)
![sec_file3](https://user-images.githubusercontent.com/17643446/84719734-00a37180-af74-11ea-8be7-2b05c73aa0f9.png)

check more from StackOverflow question:
https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

**Comment by bartekpacia** [comment]
Considering this as stale and closing. Feel free to open a new issue.
