### ISSUE TITLE
'FlutterDownloader.initialize() must be called first' thrown after initialization

### ISSUE THREAD

**Issue by hawkinsjb1** [fluttercommunity/flutter_downloader#308]
I am calling `await FlutterDownloader.initialize(debug: true);` in main after `WidgetsFlutterBinding.ensureInitialized();` and I am calling `FlutterDownloader.registerCallback(downloadCallback);` in the initState of my App class. Enqueue works, and my file is downloaded however I want to open it as soon as it finishes and unfortunately I am receiving `FlutterDownloader.initialize() must be called first` exception in my callback which calls .open().

My callback looks like
```  
static void downloadCallback(
      String id, DownloadTaskStatus status, int progress) async {
    if (status == DownloadTaskStatus.complete) {
      await FlutterDownloader.open(taskId: id);
    }
 }
```

**Comment by hawkinsjb1** [comment]
Solved. Looking at the source code helped, I needed to use ports/isolates even if I'm calling other methods in the package

**Comment by smj992925133** [comment]
请问怎么解决的

**Comment by hawkinsjb1** [comment]
@smj992925133 
添加隔离并从回调中调用隔离
我不会说中文
```
  startDownloaderListener() {
    IsolateNameServer.registerPortWithName(_port.sendPort, 'downloader_send_port');
    _port.listen((dynamic data) async {
        String id = data[0];
        String status = data[1];
        if (status == DownloadTaskStatus.complete) {
            await FlutterDownloader.open(taskId: id);
        }
    });

    FlutterDownloader.registerCallback(downloadCallback);
  }
```
```
  static void downloadCallback(String id, DownloadTaskStatus status, int progress) {
    final SendPort send =IsolateNameServer.lookupPortByName('downloader_send_port');
    send.send([id, status, progress]);
  }
```
