### ISSUE TITLE
[Android] Start the error 

### ISSUE THREAD

**Issue by zhanglijie5997** [fluttercommunity/flutter_downloader#311]
```
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve androidx.room:room-common:[2.2.3].
     Required by:
         project :app > project :flutter_downloader > androidx.work:work-runtime:2.3.4 > androidx.room:room-runtime:2.2.3
      > Failed to list versions for androidx.room:room-common.
```

**Comment by am1994** [comment]
I faced the same issue and I fixed it :

1. go to plugin folder and  open  gradle-wrapper.properties   =>
 (flutter/.pub-cache/hosted/pub.dartlang.org/flutter_downloader-1.4.4/android/gradle/wrapper)

3. change the Gradle version "distributionUrl"  depend on your project Gradle version in android 
like this : distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip

**Comment by zhanglijie5997** [comment]
Thanks for giving it a try

**Comment by hnvn** [comment]
I think @am1994 's comment solved this issue

**Comment by DG-Wangtao** [comment]
jcenter is now available now, and I got the `Read timed out` error:
> https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
```
* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve androidx.room:room-common:[2.2.5].
     Required by:
         project :app > project :flutter_downloader > androidx.work:work-runtime:2.4.0 > androidx.room:room-runtime:2.2.5
      > Failed to list versions for androidx.room:room-common.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/androidx/room/room-common/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/androidx/room/room-common/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/androidx/room/room-common/maven-metadata.xml'.
                  > Read timed out
```

**Comment by songsongtao** [comment]
I faced the same issue
`         project :app > project :flutter_downloader > androidx.work:work-runtime:2.4.0 > androidx.room:room-runtime:2.2.5
      > Failed to list versions for androidx.room:room-common.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/androidx/room/room-common/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/androidx/room/room-common/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/androidx/room/room-common/maven-metadata.xml'.
                  > Read timed out
`

**Comment by yasin-sicpa** [comment]
same issue here as well 

> jcenter is now available now, and I got the `Read timed out` error:
> 
> > https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
> 
> ```
> * What went wrong:
> Could not determine the dependencies of task ':app:lintVitalRelease'.
> > Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
>    > Could not resolve androidx.room:room-common:[2.2.5].
>      Required by:
>          project :app > project :flutter_downloader > androidx.work:work-runtime:2.4.0 > androidx.room:room-runtime:2.2.5
>       > Failed to list versions for androidx.room:room-common.
>          > Unable to load Maven meta-data from https://jcenter.bintray.com/androidx/room/room-common/maven-metadata.xml.
>             > Could not get resource 'https://jcenter.bintray.com/androidx/room/room-common/maven-metadata.xml'.
>                > Could not GET 'https://jcenter.bintray.com/androidx/room/room-common/maven-metadata.xml'.
>                   > Read timed out
> ```

**Comment by dzfdan** [comment]
Could not resolve androidx.room:room-common
