### ISSUE TITLE
android:'_initialized': FlutterDownloader.initialize() must be called first

### ISSUE THREAD

**Issue by quweifan** [fluttercommunity/flutter_downloader#312]
Unhandled Exception: 'package:flutter_downloader/src/downloader.dart': Failed assertion: line 73 pos 12: '_initialized': FlutterDownloader.initialize() must be called first
E/flutter (10872): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
E/flutter (10872): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
E/flutter (10872): #2      FlutterDownloader.enqueue (package:flutter_downloader/src/downloader.dart:73:12)

**Comment by am1994** [comment]
i think adding  these lines in main will fix the issue :
  WidgetsFlutterBinding.ensureInitialized();
  await FlutterDownloader.initialize(debug: true);

**Comment by hnvn** [comment]
I think the above comment solved this issue

**Comment by zwz1192511822** [comment]
> I think the above comment solved this issue

_initialized should be a public variable

**Comment by erperejildo** [comment]
> i think adding these lines in main will fix the issue :
> WidgetsFlutterBinding.ensureInitialized();
> await FlutterDownloader.initialize(debug: true);



> I think the above comment solved this issue

It didn't fix anything for me

**Comment by Abdollar1** [comment]
> WidgetsFlutterBinding.ensureInitialized();
I added it but the problem was not solve

**Comment by quanghuy-comply** [comment]
await FlutterDownloader.initialize(debug: true);

is not helping in my case

**Comment by innovatoraakash** [comment]
_AssertionError ('package:flutter_downloader/src/downloader.dart': Failed assertion: line 124 pos 12: '_initialized': plugin flutter_downloader is not initialized)
 I can download files but then I run loadTask query it asserts this error
I have initialized flutterdownloader in main

**Comment by hsynaksu** [comment]
Not working for me too :(

**Comment by rmahmadkhan** [comment]
Even after adding the `await FlutterDownloader.initialize(debug: true);` in `main.dart`, the exception only comes when you register a callback. Otherwise it works fine
