### ISSUE TITLE
[IOS] loadAllTasks always return null.

### ISSUE THREAD

**Issue by catoldcui** [fluttercommunity/flutter_downloader#32]
Env:
IOS 12.1 (iPhone X simulator)
downloader:  v1.1.3

Already config it following the README.md in xcode. No error logs for sqlite but loadAllTasks returns null. Works fine in Android.

**Comment by hnvn** [comment]
Have you tested on a real device yet?

**Comment by hnvn** [comment]
And, this issue occurs on demo project, doesn't it?

**Comment by catoldcui** [comment]
> And, this issue occurs on demo project, doesn't it?

Yeah, mainly similar to your demo project.

> Have you tested on a real device yet?

Just in simulator, not test in a real IOS device. I dev in IOS simulator, release for android. It works in Andorid device.

**Comment by hnvn** [comment]
I've just tested the demo project on iOS (iPhone X simulator), it works well. I have no idea about your matter.

**Comment by catoldcui** [comment]
Thanks, you are right. I run your example directly, it works fine. But I integrated with 
[sqflite](https://github.com/tekartik/sqflite) in my project. Maybe some conflict occurs. Not sure about this. 

I'll check with this.

**Comment by catoldcui** [comment]
I found the cause;

When the insert sql is error, when fields contains `"`.  I'll try to fix this issue with a PR.

For my case, I use param header like `{"HOST": "xxx","Authorization": "xxx"}`, the " is not be converted. This breaks the sql.
```
2019-01-27 01:12:55.048666+0800 Runner[68308:30516352] execute query: INSERT INTO task (task_id,url,status,progress,file_name,saved_dir,headers,resumable,show_notification,open_file_from_notification,time_created) VALUES ("xxx","xxx",1,0,"xxx","xxx","{"HOST": "xxx","Authorization": "xxx"}",0,0,0,1548522775048)
```
