### ISSUE TITLE
Build fails when using with google_sign_in package

### ISSUE THREAD

**Issue by gurnisht** [fluttercommunity/flutter_downloader#33]
Hi,
I get the message:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'android.arch.lifecycle:runtime' has different version for the compile (1.0.0) and runtime (1.1.0) classpath. You should manually set the same version via DependencyResolution

---------------------------

my pubspec.yaml:

dependencies:
  flutter:
    sdk: flutter
  flutter_downloader: ^1.1.4
  path_provider: ^0.4.1
  google_sign_in: ^3.2.4

thanks

**Comment by hnvn** [comment]
Try this:
```
allprojects {
    ...

    configurations {
        all {
            resolutionStrategy {
                force "android.arch.lifecycle:runtime:1.1.1"
            }
        }
    }

}
```
more detail at: https://stackoverflow.com/a/50047277/3693334

**Comment by gurnisht** [comment]
Thanks for your reply. I tried it but it still doesn't build. now it gives me a list of  many different jars, with "com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives".

**Comment by gurnisht** [comment]
Thanks for your reply. I tried it but it still doesn't build. now it gives me a list of many different jars, with "com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives".

**Comment by gurnisht** [comment]
Thanks for your kind help. I tried the suggested workaround too and it still didn't solve, I'm still getting the original error _(Android dependency 'android.arch.lifecycle:runtime' has different version for the compile (1.0.0) and runtime (1.1.0) classpath)._

Here is my build.gradle
`buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }

    configurations.all {
        exclude group: 'com.google.guava', module: 'failureaccess'

        resolutionStrategy {
            eachDependency { details ->
                if('guava' == details.requested.name) {
                    details.useVersion '27.0-android'
                }
            }
        }
    }

}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

**Comment by hnvn** [comment]
You should combine two configs together:
```
configurations {
        all {
            exclude group: 'com.google.guava', module: 'failureaccess'
            
            resolutionStrategy {
                eachDependency { details ->
                    if('guava' == details.requested.name) {
                        details.useVersion '27.0-android'
                    }
                    if('android.arch.lifecycle' == details.requested.group && 'runtime' == details.requested.name) {
                       details.useVersion '1.1.1'
                    }
               }
            }
    }

```
I just try to write codes directly in comment box, not sure that it's right syntax.

**Comment by gurnisht** [comment]
Works! thanks!
