### ISSUE TITLE
Download failed for android 10 ( Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied))

### ISSUE THREAD

**Issue by MasterJain** [fluttercommunity/flutter_downloader#330]
Although this is fixable for now by using requestLegacyExternalStorage: true
But from android 11 we will not have this option as google will completely switch to scoped storage
Just giving a little heads up

**Comment by zahidshaikh08** [comment]
Did you put storage permissions and did you enabled useLegacyStorage=true in AndroidManifest.xml file??
its compulsory for android 10+ versions else you will get error.
