### ISSUE TITLE
After upgrading to 1.20.2, it can't work normally, 1.17.5 version is ok, I don't know where the problem is

### ISSUE THREAD

**Issue by mingsnx** [fluttercommunity/flutter_downloader#337]
![20200902-101346](https://user-images.githubusercontent.com/39380183/91924710-03596b80-ed06-11ea-87ab-58d087740fc1.png)
![1599013060064](https://user-images.githubusercontent.com/39380183/91924847-516e6f00-ed06-11ea-808d-7903944ce93a.jpg)

**Comment by mingsnx** [comment]
![20200902-103604](https://user-images.githubusercontent.com/39380183/91925719-31d84600-ed08-11ea-83c8-2476c29dc693.png)
This is after running the flutter run command

**Comment by anisalibegic** [comment]
Adding textual version to make finding this easier.

**Comment by anisalibegic** [comment]
Adding `!` at the end of the line fixes the problem.

Instead of:
`FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "FlutterDownloaderPlugin"))`
Use:
`FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "FlutterDownloaderPlugin")!)`

**Comment by AAverin** [comment]
Also this https://github.com/fluttercommunity/flutter_downloader/issues/187

**Comment by hnvn** [comment]
#347 fixed it

**Comment by JanMate** [comment]
> Adding `!` at the end of the line fixes the problem.
> 
> Instead of:
> `FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "FlutterDownloaderPlugin"))`
> Use:
> `FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "FlutterDownloaderPlugin")!)`

On Flutter version 1.20.4 and iOS 14 does not work. #187 helped.

**Comment by Empty0Qc** [comment]
I finally fix it, thanks.💐
