### ISSUE TITLE
Download notification stuck at 100%

### ISSUE THREAD

**Issue by procodingtools** [fluttercommunity/flutter_downloader#345]
Hi,
I have an issue with flutter_downloader package.
After downloading the file, the notification being stuck at full progressbar (100%) state.

What should i do.
PS: i tried with requirestoragenotfull true and false.
![Screenshot_Chrome_20200919-053247~2](https://user-images.githubusercontent.com/50031998/93659140-36a43600-fa3a-11ea-830c-0d03d5b49579.png)

**Comment by hnvn** [comment]
any log?

**Comment by hnvn** [comment]
Fixed in v1.5.2

**Comment by uc-dve** [comment]
I have also the same issue, once any download failed and retry download using the below code if we pause it and resume then there is another error.

 `FlutterDownloader.retry(taskId: taskId!);`

on pause then resume => 

![image](https://user-images.githubusercontent.com/28289763/122190925-e6b2ac80-ceaf-11eb-9a60-9556510db7e9.png)

on complete download it failed =>

![image](https://user-images.githubusercontent.com/28289763/122188704-db5e8180-cead-11eb-9fa8-5a3106884f74.png)
