### ISSUE TITLE
Insert download task to the SQLite database

### ISSUE THREAD

**Issue by adarshhegde** [fluttercommunity/flutter_downloader#348]
In an app that I have been working on, I need to lets say "fake" a download in some cases where the file is already in storage in some temporary folder, and I just need to copy it to the final destination, so I was wondering if there is any way to add a new record to the sqlite db explicitly from outside, with the savedDir filename and status set by me so I can make it seem that file has been downloaded..

**Comment by hnvn** [comment]
You can use a third-party library supporting SQLite to manipulate the db of flutter_downloader

**Comment by adarshhegde** [comment]
I can use the sqlite module from flutter directly without needing to touch the native java and swift code right? I will have a look at this, thank you

**Comment by adarshhegde** [comment]
it worked thank you

**Comment by chrisbinsunny** [comment]
Hey @adarshhegde @hnvn @adarshhegde 

I am trying to implement the same thing in my app. I just have one doubt. What did you pass for `task_id`? It is being generated on the native side. So I couldn't find it. Please help me.

**Comment by adarshhegde** [comment]
@chrisbinsunny I think I passed in a v4 uuid, it can be anything unique.

I used this package to generate it 
https://pub.dev/packages/uuid

**Comment by chrisbinsunny** [comment]
Oh Thanks. I overthought that. Thank you for your help.
