### ISSUE TITLE
(Andriod)resource xml/provider_paths (aka com.example.downtaskdemo:xml/provider_paths) not found.

### ISSUE THREAD

**Issue by bocaiJs** [fluttercommunity/flutter_downloader#35]
configure  AndroidManifest.xml  use
 <provider
            android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider"
            android:authorities="${applicationId}.flutter_downloader.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  /Users/bocai/Code/Flutter/downtask_demo/build/app/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml:59: error: resource xml/provider_paths (aka com.example.downtaskdemo:xml/provider_paths) not found.
  error: failed processing manifest.

  Command: /Users/bocai/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-osx.jar/8848f4decba9eba34304a16ea15c97ed/aapt2-3.2.1-4818971-osx/aapt2 link -I\
          /Users/bocai/Library/Android/sdk/platforms/android-27/android.jar\
          --manifest\
          /Users/bocai/Code/Flutter/downtask_demo/build/app/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\
          -o\
          /Users/bocai/Code/Flutter/downtask_demo/build/app/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
          -R\
          @/Users/bocai/Code/Flutter/downtask_demo/build/app/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          /Users/bocai/Code/Flutter/downtask_demo/build/app/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
          --custom-package\
          com.example.downtaskdemo\
          -0\
          apk\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #0
  Output:  /Users/bocai/Code/Flutter/downtask_demo/build/app/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml:59: AAPT: error: resource xml/provider_paths (aka com.example.downtaskdemo:xml/provider_paths) not found.

**Comment by bocaiJs** [comment]
I was stupid.
Problem solved
I should install it first.
Then configure it

**Comment by saviourdog** [comment]
> I was stupid.
> Problem solved
> I should install it first.
> Then configure it

same problem any solutions?
