### ISSUE TITLE
 Unhandled Exception: 'package:flutter_downloader/src/downloader.dart': Failed assertion: line 30 pos 12: '!_initialized': FlutterDownloader.initialize() must be called only once!

### ISSUE THREAD

**Issue by rehamalraee** [fluttercommunity/flutter_downloader#354]
Hello!
I have called a function to initialize , then I navigate to another class that makes initiate state !! 
void initilizeDownloader() async {
  FlutterDownloader.initialize();
  WidgetsFlutterBinding.ensureInitialized();
}
what is wrong ?

**Comment by chandraguptgosavi** [comment]
@rehamalraee you should call FlutterDownloader.initialize() only once in whole project and it should be on main isolate, it will be good if you call it in main function like this:

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await FlutterDownloader.initialize(
      debug: true // optional: set false to disable printing logs to console
      );
  runApp(MyApp());
}

Hope, this may help you.
