### ISSUE TITLE
Download failed.

### ISSUE THREAD

**Issue by Dabhipb** [fluttercommunity/flutter_downloader#358]
Hi, Thanks for provide such a plugin.
Issue is that  in Android we could not download any contents from http url but https url working perfectly. in iOS  both urls from Http and Https are working like a charm.
please check this issue.

**W/WM-WorkSpec( 8234): Backoff delay duration less than minimum value
D/DownloadWorker( 8234): DownloadWorker{url=http://iphone.gettywallpapers.com/wp-content/uploads/2020/01/Cool-Wallpaper-iPhone.jpg,filename=1.jpg,savedDir=/storage/emulated/0/Android/data/com.app.download_demo/files/Download,header={"auth": "test_for_sql_encoding"},isResume=false
I/flutter ( 8234): Background Isolate Callback: task (78b9b10b-833c-4859-8984-debc3a0945e3) is in status (DownloadTaskStatus(2)) and process (0)
D/DownloadWorker( 8234): Open connection to http://iphone.gettywallpapers.com/wp-content/uploads/2020/01/Cool-Wallpaper-iPhone.jpg
D/DownloadWorker( 8234): Headers = {"auth": "test_for_sql_encoding"}
I/flutter ( 8234): Background Isolate Callback: task (78b9b10b-833c-4859-8984-debc3a0945e3) is in status (DownloadTaskStatus(4)) and process (-1)
W/System.err( 8234): java.io.IOException: Cleartext HTTP traffic to iphone.gettywallpapers.com not permitted
W/System.err( 8234): 	at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:142)
W/System.err( 8234): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:469)
W/System.err( 8234): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:418)
W/System.err( 8234): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:549)
W/System.err( 8234): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:278)
I/flutter ( 8234): UI Isolate Callback: [78b9b10b-833c-4859-8984-debc3a0945e3, DownloadTaskStatus(2), 0]
W/System.err( 8234): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:192)
I/flutter ( 8234): UI Isolate Callback: [78b9b10b-833c-4859-8984-debc3a0945e3, DownloadTaskStatus(4), -1]
W/System.err( 8234): 	at androidx.work.Worker$1.run(Worker.java:85)
W/System.err( 8234): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err( 8234): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err( 8234): 	at java.lang.Thread.run(Thread.java:764)
I/WM-WorkerWrapper( 8234): Worker result SUCCESS for Work [ id=78b9b10b-833c-4859-8984-debc3a0945e3, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]**

**Comment by wahyu-handayani** [comment]
Hi @DabPb I have the same case like yours, did you find any solution ?
