### ISSUE TITLE
Running example results in : Couldn't find meta-data for provider with authority com.example.download_example.flutter_downloader.provider

### ISSUE THREAD

**Issue by jorg1piano** [fluttercommunity/flutter_downloader#366]
Running the current example provided results in exception
`    java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority 
        com.example.download_example.flutter_downloader.provider
`

Theses are the logs:

`
    Launching lib\main.dart on SM G920F in debug mode...
     lib\main.dart
    √ Built build\app\outputs\flutter-apk\app-debug.apk.
    Connecting to VM Service at ws://127.0.0.1:53689/7XZ63Ngsa4g=/ws
    D/ViewRootImpl@411842e[MainActivity]( 7187): ViewPostImeInputStage processPointer 0
    W/System  ( 7187): ClassLoader referenced unknown path: /system/framework/QPerformance.jar
    E/BoostFramework( 7187): BoostFramework() : Exception_1 = java.lang.ClassNotFoundException: Didn't find class "com.qualcomm.qti.Performance" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib64, /vendor/lib64]]
    V/BoostFramework( 7187): BoostFramework() : mPerf = null
    D/ViewRootImpl@411842e[MainActivity]( 7187): ViewPostImeInputStage processPointer 1
    D/ViewRootImpl@411842e[MainActivity]( 7187): ViewPostImeInputStage processPointer 0
    D/ViewRootImpl@411842e[MainActivity]( 7187): ViewPostImeInputStage processPointer 1
    W/WM-WorkSpec( 7187): Backoff delay duration less than minimum value
    I/art     ( 7187): Background sticky concurrent mark sweep GC freed 23468(1480KB) AllocSpace objects, 5(100KB) LOS objects, 33% free, 9MB/14MB, paused 6.556ms total 51.709ms
    D/ConnectivityManager( 7187): requestNetwork; CallingUid : 10424, CallingPid : 7187
    D/DownloadWorker( 7187): DownloadWorker{url=https://upload.wikimedia.org/wikipedia/commons/b/b2/Sand_Dunes_in_Death_Valley_National_Park.jpg,filename=null,savedDir=/storage/emulated/0/Android/data/com.example.download_example/files/Download,header={"auth": "test_for_sql_encoding"},isResume=false
    D/DownloadWorker( 7187): Update notification: {notificationId: 3, title: https://upload.wikimedia.org/wikipedia/commons/b/b2/Sand_Dunes_in_Death_Valley_National_Park.jpg, status: 2, progress: 0}
    D/DownloadWorker( 7187): Open connection to https://upload.wikimedia.org/wikipedia/commons/b/b2/Sand_Dunes_in_Death_Valley_National_Park.jpg
    D/DownloadWorker( 7187): Headers = {"auth": "test_for_sql_encoding"}
    I/System.out( 7187): (HTTPLog)-Static: isSBSettingEnabled false
    I/System.out( 7187): (HTTPLog)-Static: isSBSettingEnabled false
    D/DownloadWorker( 7187): Content-Type = image/jpeg
    D/DownloadWorker( 7187): Content-Length = 1363085
    D/DownloadWorker( 7187): Charset = null
    D/DownloadWorker( 7187): Content-Disposition = null
    D/DownloadWorker( 7187): fileName = Sand_Dunes_in_Death_Valley_National_Park.jpg
    D/DownloadWorker( 7187): Update too frequently!!!!, this should be dropped
    D/DownloadWorker( 7187): Update too frequently!!!!, this should be dropped
    D/DownloadWorker( 7187): Update too frequently!!!!, this should be dropped
    D/DownloadWorker( 7187): Update too frequently!!!!, this should be dropped
    D/DownloadWorker( 7187): Update too frequently!!!!, this should be dropped
    D/DownloadWorker( 7187): Update too frequently!!!!, this should be dropped
    D/DownloadWorker( 7187): Update too frequently!!!!, this should be dropped
    D/DownloadWorker( 7187): Update too frequently!!!!, this should be dropped
    D/DownloadWorker( 7187): Update too frequently!!!!, this should be dropped
    D/DownloadWorker( 7187): Update too frequently!!!!, this should be dropped
    D/DownloadWorker( 7187): insert mime_type=image/jpeg _data=/storage/emulated/0/Android/data/com.example.download_example/files/Download/Sand_Dunes_in_Death_Valley_National_Park.jpg title=Sand_Dunes_in_Death_Valley_National_Park.jpg description= date_added=1604277080823 datetaken=1604277080823 _display_name=Sand_Dunes_in_Death_Valley_National_Park.jpg to MediaStore
    D/DownloadWorker( 7187): Update too frequently!!!!, but it is the final update, we should sleep a second to ensure the update call can be processed
    I/flutter ( 7187): Background Isolate Callback: task (3597e77e-ed08-460d-b44a-caad9f92b612) is in status (DownloadTaskStatus(2)) and process (0)
    I/flutter ( 7187): Background Isolate Callback: task (3597e77e-ed08-460d-b44a-caad9f92b612) is in status (DownloadTaskStatus(2)) and process (1)
    I/flutter ( 7187): Background Isolate Callback: task (3597e77e-ed08-460d-b44a-caad9f92b612) is in status (DownloadTaskStatus(2)) and process (12)
    I/flutter ( 7187): Background Isolate Callback: task (3597e77e-ed08-460d-b44a-caad9f92b612) is in status (DownloadTaskStatus(2)) and process (23)
    I/flutter ( 7187): Background Isolate Callback: task (3597e77e-ed08-460d-b44a-caad9f92b612) is in status (DownloadTaskStatus(2)) and process (34)
    I/flutter ( 7187): Background Isolate Callback: task (3597e77e-ed08-460d-b44a-caad9f92b612) is in status (DownloadTaskStatus(2)) and process (45)
    I/flutter ( 7187): Background Isolate Callback: task (3597e77e-ed08-460d-b44a-caad9f92b612) is in status (DownloadTaskStatus(2)) and process (56)
    I/flutter ( 7187): Background Isolate Callback: task (3597e77e-ed08-460d-b44a-caad9f92b612) is in status (DownloadTaskStatus(2)) and process (67)
    I/flutter ( 7187): Background Isolate Callback: task (3597e77e-ed08-460d-b44a-caad9f92b612) is in status (DownloadTaskStatus(2)) and process (78)
    I/flutter ( 7187): Background Isolate Callback: task (3597e77e-ed08-460d-b44a-caad9f92b612) is in status (DownloadTaskStatus(2)) and process (89)
    I/flutter ( 7187): Background Isolate Callback: task (3597e77e-ed08-460d-b44a-caad9f92b612) is in status (DownloadTaskStatus(2)) and process (100)
    I/flutter ( 7187): Background Isolate Callback: task (3597e77e-ed08-460d-b44a-caad9f92b612) is in status (DownloadTaskStatus(4)) and process (-1)
    I/flutter ( 7187): UI Isolate Callback: [3597e77e-ed08-460d-b44a-caad9f92b612, DownloadTaskStatus(2), 0]
    I/flutter ( 7187): UI Isolate Callback: [3597e77e-ed08-460d-b44a-caad9f92b612, DownloadTaskStatus(2), 1]
    I/flutter ( 7187): UI Isolate Callback: [3597e77e-ed08-460d-b44a-caad9f92b612, DownloadTaskStatus(2), 12]
    I/flutter ( 7187): UI Isolate Callback: [3597e77e-ed08-460d-b44a-caad9f92b612, DownloadTaskStatus(2), 23]
    I/flutter ( 7187): UI Isolate Callback: [3597e77e-ed08-460d-b44a-caad9f92b612, DownloadTaskStatus(2), 34]
    I/flutter ( 7187): UI Isolate Callback: [3597e77e-ed08-460d-b44a-caad9f92b612, DownloadTaskStatus(2), 45]
    I/flutter ( 7187): UI Isolate Callback: [3597e77e-ed08-460d-b44a-caad9f92b612, DownloadTaskStatus(2), 56]
    I/flutter ( 7187): UI Isolate Callback: [3597e77e-ed08-460d-b44a-caad9f92b612, DownloadTaskStatus(2), 67]
    I/flutter ( 7187): UI Isolate Callback: [3597e77e-ed08-460d-b44a-caad9f92b612, DownloadTaskStatus(2), 78]
    I/flutter ( 7187): UI Isolate Callback: [3597e77e-ed08-460d-b44a-caad9f92b612, DownloadTaskStatus(2), 89]
    I/flutter ( 7187): UI Isolate Callback: [3597e77e-ed08-460d-b44a-caad9f92b612, DownloadTaskStatus(2), 100]
    I/flutter ( 7187): UI Isolate Callback: [3597e77e-ed08-460d-b44a-caad9f92b612, DownloadTaskStatus(4), -1]
    D/DownloadWorker( 7187): Update notification: {notificationId: 3, title: https://upload.wikimedia.org/wikipedia/commons/b/b2/Sand_Dunes_in_Death_Valley_National_Park.jpg, status: 4, progress: -1}
    W/System.err( 7187): java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.example.download_example.flutter_downloader.provider
    W/System.err( 7187): 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:606)
    W/System.err( 7187): 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
    W/System.err( 7187): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
    W/System.err( 7187): 	at vn.hunghd.flutterdownloader.IntentUtils.buildIntent(IntentUtils.java:23)
    W/System.err( 7187): 	at vn.hunghd.flutterdownloader.IntentUtils.validatedFileIntent(IntentUtils.java:35)
    W/System.err( 7187): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:365)
    W/System.err( 7187): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:193)
    W/System.err( 7187): 	at androidx.work.Worker$1.run(Worker.java:85)
    W/System.err( 7187): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    W/System.err( 7187): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    W/System.err( 7187): 	at java.lang.Thread.run(Thread.java:762)
    I/WM-WorkerWrapper( 7187): Worker result FAILURE for Work [ id=3597e77e-ed08-460d-b44a-caad9f92b612, tags={ vn.hunghd.flutterdownloader.DownloadWorker, flutter_download_task } ]
`

Looks like it completes the download then throws the error...

**Comment by jorg1piano** [comment]
Adding this in the android manifest resolves the issue. Is there maybe a mistake in the documentation?

`<provider
            android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider"
            android:authorities="${applicationId}.flutter_downloader.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>        
</provider>`

**Comment by dotw** [comment]
I met the same issue and @jorg1piano 's solution works for my case.
