### ISSUE TITLE
The method 'call' was called on null

### ISSUE THREAD

**Issue by mulieli** [fluttercommunity/flutter_downloader#375]
下面图是报错
![image](https://user-images.githubusercontent.com/24307960/99876499-10fdfd80-2c32-11eb-848d-39b1b7aca03e.png)
下面是我的写法
![image](https://user-images.githubusercontent.com/24307960/99876536-3d197e80-2c32-11eb-9212-53d043252113.png)

**Comment by mulieli** [comment]
是我代码问题

**Comment by BazinC** [comment]
@mulieli What was your code problem ?
I have the same exception "The method 'call' was called on null"
Thanks :)
