### ISSUE TITLE
only success task can be opened

### ISSUE THREAD

**Issue by mulieli** [fluttercommunity/flutter_downloader#378]
下载完成后 打开文件 报错 only success task can be opened
我已经延时一秒后打开 仍是报错

**Comment by hgxin** [comment]
我也遇到了同样的问题

**Comment by mulieli** [comment]
> 我也遇到了同样的问题

我在其他地方看到了临时解决办法 

判断完文件是否下载完成后 延迟2秒 就可以了

**Comment by hgxin** [comment]
@mulieli 完美解决

**Comment by hgxin** [comment]
@mulieli 退出app后,再进入你会报一下错误吗?
`Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel vn.hunghd/downloader)`

**Comment by mulieli** [comment]
> @mulieli 退出app后,再进入你会报以下错误吗?
> `Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel vn.hunghd/downloader)`

我没有注意到有这个错 我应该是没有这个错

**Comment by hgxin** [comment]
加了exit(0);解决了,但是真机测试直接中断, 不过可以正常使用
`  Future<bool> _isExit() {
    if (_lastTime == null || DateTime.now().difference(_lastTime) > Duration(milliseconds: 2500)) {
      _lastTime = DateTime.now();
      ToastUtil.show("再次点击退出应用");
      return Future.value(false);
    }
    ToastUtil.cancelToast();
    //解决flutterdownloader : Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel vn.hunghd/downloader)
    exit(0);
    // SystemNavigator.pop();
    return Future.value(true);
  }`

**Comment by walkthehorizon** [comment]
有点坑啊，complete status != success
