### ISSUE TITLE
Plug-in initialization caused iOS APP startup crash

### ISSUE THREAD

**Issue by FangPro** [fluttercommunity/flutter_downloader#395]
Whenever I call the plugin's initialization method in the main() method, it will crash and exit directly after the app starts.

Here is my print log:

*** First throw call stack:

(

0 CoreFoundation 0x00000001012d3126 __exceptionPreprocess + 242

1 libobjc.A.dylib 0x0000000106587f78 objc_exception_throw + 48

2 CoreFoundation 0x00000001012d2f4f +[NSException raise:format:] + 0

3 Foundation 0x00000001046581ca -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191

4 flutter_downloader 0x000000010634f4c0 -[FlutterDownloaderPlugin startBackgroundIsolate:] + 528

5 flutter_downloader 0x00000001063552d9 -[FlutterDownloaderPlugin initializeMethodCall:result:] + 297

6 flutter_downloader 0x00000001063590af -[FlutterDownloaderPlugin handleMethodCall:result:] + 191

7 Flutter 0x00000001024B09DF __45-[FlutterMethodChannel setMet<... >

Lost connection to device.

**Comment by erperejildo** [comment]
any update?
