### ISSUE TITLE
when i run download function i see this in my debug panel and downloads fail

### ISSUE THREAD

**Issue by paraggupta9065** [fluttercommunity/flutter_downloader#398]
W/WM-WorkSpec(25934): Backoff delay duration less than minimum value
D/DownloadWorker(25934): DownloadWorker{url=https://pixabay.com/get/53e8dd444a54a914f6da8c7dda7936771d3ddced5a536c48732e7bdc9649c45fbb_1280.jpg,filename=5887065.jpeg,savedDir=/storage/emulated/0/Download,header=,isResume=false
D/DownloadWorker(25934): Update notification: {notificationId: 13, title: 5887065.jpeg, status: 2, progress: 0}
D/DownloadWorker(25934): Open connection to https://pixabay.com/get/53e8dd444a54a914f6da8c7dda7936771d3ddced5a536c48732e7bdc9649c45fbb_1280.jpg
D/DownloadWorker(25934): Content-Type = image/jpeg
D/DownloadWorker(25934): Content-Length = 218368
D/DownloadWorker(25934): Charset = null
D/DownloadWorker(25934): fileName = 5887065.jpeg
D/DownloadWorker(25934): Update too frequently!!!!, but it is the final update, we should sleep a second to ensure the update call can be processed
D/DownloadWorker(25934): Update notification: {notificationId: 13, title: 5887065.jpeg, status: 4, progress: -1}
W/System.err(25934): java.io.FileNotFoundException: /storage/emulated/0/Download/5887065.jpeg: open failed: EACCES (Permission denied)
W/System.err(25934): 	at libcore.io.IoBridge.open(IoBridge.java:496)
W/System.err(25934): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
W/System.err(25934): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:157)
W/System.err(25934): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:331)
W/System.err(25934): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:193)
W/System.err(25934): 	at androidx.work.Worker$1.run(Worker.java:85)
W/System.err(25934): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(25934): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(25934): 	at java.lang.Thread.run(Thread.java:919)
W/System.err(25934): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err(25934): 	at libcore.io.Linux.open(Native Method)
W/System.err(25934): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(25934): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
W/System.err(25934): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(25934): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7297)
W/System.err(25934): 	at libcore.io.IoBridge.open(IoBridge.java:482)
W/System.err(25934): 	... 8 more
I/WM-WorkerWrapper(25934): Worker result SUCCESS for Work [ id=a605bb89-fd69-4a3d-bdff-ff7c7c1d0940, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]

**Comment by thecaptrex** [comment]
i'm having the same problem. any news or solution to this?

**Comment by paraggupta9065** [comment]
Yes bro it is solved

You just have to give special permission from android manifest
And it is because you are running on android version above 10

**Comment by Andreigr0** [comment]
You could mark that it should be https://stackoverflow.com/a/60316149/9586934
