### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by IchordeDionysos** [fluttercommunity/flutter_downloader#412]
This is a request to add support for [null safety](https://dart.dev/null-safety) to `package:flutter_downloader`.
We depend on your awesome package, so would be great to have null safety enabled.

The Dart/Flutter team already encourages publishing the migrated packages: See [this blog post](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010).

See the [migration guide](https://dart.dev/null-safety/migration-guide) for details about enabling null safety.

**Comment by hnvn** [comment]
Support nullsafety in v1.6.0-nullsafety.0

**Comment by IchordeDionysos** [comment]
@hnvn any plans to release a stable version with null-safety? ☺️ 
It's been a month now since the null-safe pre-release version

**Comment by hnvn** [comment]
Sure, I will update it today

**Comment by marynovskyi** [comment]
Is there any updates when stable version will support null safety?
