### ISSUE TITLE
Sending $_POST parameter to the download URL

### ISSUE THREAD

**Issue by rivetingpeppermint** [fluttercommunity/flutter_downloader#416]
I'm using `flutter_downloader ^1.4.4`. I need to pass a $_POST parameter to the url of the file I am downloading. 
```
final download = await FlutterDownloader.enqueue(
    url: 'https://file.whateversite.org/images/Example.svg', //how to send e.g. $_POST['check'] here?
    savedDir: _localPath,
    showNotification: true,
    openFileFromNotification: true
);
````
Can this be done with `flutter_downloader`? I've been looking for examples and I've found nothing.

**Comment by Matej-Hlatky** [comment]
According to [FlutterDownloader.enqueue](https://github.com/fluttercommunity/flutter_downloader/blob/e782559d81a8b69e6d36440b55a4263c0de1a515/lib/src/downloader.dart#L65) source code, I afraid no.

I suggest you to make your own "proxy" site, that will execute `POST` request based on `GET` query parameters.

**Comment by rivetingpeppermint** [comment]
@Matej-Hlatky is this what you meant? I've tried passing the variable I want to pass as a $_GET, so it's become
```
String check = "examplexample";
final download = await FlutterDownloader.enqueue(
    url: fileURL+"?check="+check,
    savedDir: _localPath,
    showNotification: true,
    openFileFromNotification: true,
 );
```
My site can read the $_GET['check'] alright, but now the file can't be downloaded because the plugin thinks my $_GET is a part of the file's extension. Thoroughly lost on how to do this.

**Comment by rivetingpeppermint** [comment]
I got it to work by adding a fileName, like so:
```
String check = "example";
final download = await FlutterDownloader.enqueue(
  url: fileURL+"?check="+check,
  savedDir: _localPath,
  fileName: fileURL.split('/').last,
  showNotification: true,
  openFileFromNotification: true,
);
```
Thanks @Matej-Hlatky for the inspiration.

**Comment by yjt1216** [comment]
Not flexible enough，only Get
