### ISSUE TITLE
for loop inside listen callback not executing

### ISSUE THREAD

**Issue by rajeevjaiswal** [fluttercommunity/flutter_downloader#419]
This is very strange behavior. I am trying to run a loop to check the id inside the listen to port matches any object inside the list. But this is not getting executed for some strange reason. No print logs nothing. @hnvn any help?

` _port.listen((dynamic data) async {
      print('UI Isolate Callback: $data');
      
      String id = data[0];
      DownloadTaskStatus status = data[1];
      int progress = data[2];
      print("id $id");

      // taskId = id;

      print("downloadProgress ${progress.toString()}");
      // downloadStatus = status;
      // downloadProgress = progress;

      var taskData;

      downloadMap.values.forEach((element) {
        print("saved taskId ${element.taskId}");
        if (element.taskId == id) {
          taskData = element;
          taskData.status = status;
          taskData.progress = progress;
          update();
          return;
        }
      });

      /* var taskData = downloadMap.values
          ?.firstWhere((element) => element.taskId == id, orElse: () => null);
      print("statusDown1 ${status.toString()}");
      Get.snackbar("statusDown1", "${status.toString()}");
      taskData.progress = progress;
      taskData.status = status;
      update();*/
      // updateUi(progress, id, status);
    });`

**Comment by DhruvamSharma** [comment]
What was the reason @rajeevjaiswal?
