### ISSUE TITLE
Downloaded zip corrupted

### ISSUE THREAD

**Issue by antoninoSTB** [fluttercommunity/flutter_downloader#43]
``` dart    
await FlutterDownloader.enqueue(    
   url: MY_BASE_API + '/test-export.zip',
   headers: {
       'Content-Type': 'application/zip',
    },
    savedDir: _localPath,
    showNotification: true,
    openFileFromNotification: true,
);
```
I've tried with `Content-Type: application/octet-stream` and `Content-Type: application/force-download` but when I try to open the downloaded file, it's like it is corrupted: impossible to open

**Comment by hnvn** [comment]
Follow the `README` guideline about conditions to preview a file on your Android phone.

**Comment by antoninoSTB** [comment]
Hi, sorry for the late feedback.
I had already added the provider section in my AndroidManifest.xml, saved the file in my external storage and assured I can open zip file on my phone.

Do you manage to download and open zip file correctly?
Thanks

**Comment by hnvn** [comment]
Yes, I do. I try to replace a link in the example project by the following link:
* https://sample-videos.com/zip/10mb.zip
That link has been downloaded successfully and the downloaded file could be opened as well. In my case, that downloaded zip file is opened by File Commander.

**Comment by antoninoSTB** [comment]
I was misled by two almost equal endpoints. Sorry about that.
Zip download works as well.

Thank you again.
