### ISSUE TITLE
After removing flutter_downloader I am unable to run flutter app

### ISSUE THREAD

**Issue by shivanshPurple** [fluttercommunity/flutter_downloader#433]
I used the flutter_downloader plugin but in the end I got to know that I don't really need it. After removing the plugin from pubspec.yaml, when I run the app in debug mode this error occurs
```
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\JOINTS\r_x_i\build\app\intermediates\packaged_manifests\debug\AndroidManifest.xml:71: AAPT: error: resource xml/provider_paths (aka com.example.r_x_i:xml/provider_paths) not found.
```

After opening the debug android manifest file I found out there is a `<provider>` tag that is related to flutter_downloader. This tag is as follows
```
<provider
            android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider"
            android:authorities="com.example.r_x_i.flutter_downloader.provider"
            android:exported="false"
            android:grantUriPermissions="true" >
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths" />
</provider>
```

So, the only option was to remove this tag, BUT this tag gets generated again on the next debug run. I hope I am making sense here.

I have run flutter clean multiple times but up to no use.

I think there must be some file/code left behind even after removing flutter_downloader plugin that causes the provider tag to appear again.

Edit 1: The only solution is to add the flutter_downloader plugin again to the pubspec.yaml file that I don't need!

**Comment by Vinzent03** [comment]
If its regenerated I assume its still in your main android manifest. You have to remove it there.
