### ISSUE TITLE
Flutter hot reload not working for 1.6.0-nullsafety.0 (iOS)

### ISSUE THREAD

**Issue by funwithflutter** [fluttercommunity/flutter_downloader#443]
`1.6.0-nullsafety.0` seems to break hot reload.

Observed this in my project, and then confirmed that it is an issue with a clean project.

Hot reload stops working when initialize is called:
```dart
FlutterDownloader.initialize();
```

To replicate:
- run any application with flutter downloader configured (null safety enabled with version `1.6.0-nullsafety.0`)
- ensure `initialize` is called
- change any field or widget that will cause a visual change on screen (save file)
- then perform a hot reload.

At which point hot reloading gets stuck, and a force quit is required.

Example CLI output:
```
[        ] reloaded 1 of 1852 libraries
[  +59 ms] Reassembling application
[+2008 ms] This is taking a long time; will now check for paused isolates.
[  +90 ms] Found 0 newly paused isolate(s).
[+11217 ms] Ignoring terminal input: "q" because we are busy.
```

This could likely be a environment issue, but I tested different Flutter versions and on a simulator and physical device.

NOTE: Did not test Android.

**Comment by rodineijf** [comment]
I've experienced the same issue. Removing the `FlutterDownloader.initialize()` makes the hot reload work again.

**Comment by funwithflutter** [comment]
@rodineijf glad someone else is experiencing this as well!

**Comment by alhafoudh** [comment]
Same issue in 1.6.0 and 1.6.1 version. Tested on iOS simulator and real device.
Android works fine.

**Comment by funwithflutter** [comment]
@hnvn Can we get confirmation on this issue please. This is a headache to work around, and makes me nervous that something else might be wrong.

**Comment by knaeckeKami** [comment]
This is an issue that happens when you use fvm.

**Comment by knaeckeKami** [comment]
This should be fixed when updating to the latest version of fvm.
