### ISSUE TITLE
Any idea about loadXmlMetaData on a null object reference error?

### ISSUE THREAD

**Issue by wyxcoder** [fluttercommunity/flutter_downloader#45]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference

                var dir = await getTemporaryDirectory();

                final taskId = await FlutterDownloader.enqueue(
                  url: 'https://mydomain.com/static/mobile/m.apk',
                  savedDir: '${dir.path}/',
                  showNotification: true, // show download progress in status bar (for Android)
                  openFileFromNotification: true, // click on notification to open downloaded file (for Android)
                );

**Comment by zerohh** [comment]
any idea about this
Build failed with an exception.
* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'android.arch.core:runtime' has different version for the compile (1.1.0) and runtime (1.1.1) classpath. You should manually set the same version via DependencyResolution

**Comment by liruqian** [comment]
> any idea about this
> Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':app:preDebugBuild'.
> 
> > Android dependency 'android.arch.core:runtime' has different version for the compile (1.1.0) and runtime (1.1.1) classpath. You should manually set the same version via DependencyResolution

Has this problem been solved?How do you solve this error?

**Comment by hnvn** [comment]
#44

**Comment by zouzhenglu** [comment]
> java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
> 
> ```
>             var dir = await getTemporaryDirectory();
> 
>             final taskId = await FlutterDownloader.enqueue(
>               url: 'https://mydomain.com/static/mobile/m.apk',
>               savedDir: '${dir.path}/',
>               showNotification: true, // show download progress in status bar (for Android)
>               openFileFromNotification: true, // click on notification to open downloaded file (for Android)
>             );
> ```

Have you solve this problem??
