### ISSUE TITLE
What permission to make this work? 

### ISSUE THREAD

**Issue by wyxcoder** [fluttercommunity/flutter_downloader#46]
From the document, 
  "You have to save your downloaded files in external storage"

What if the phone doesn't have external storage? even I use, I still get error

java.io.FileNotFoundException: /storage/emulated/0/m.apk (Permission denied)

Seems I still need set permission?

Really need some guideline to use this plugin easier.

**Comment by hnvn** [comment]
External storage doesn't mean SD card or something like it. In Android, each application lives in a private location named Application Sandbox where only that application can read or write data. That's basic knowledge when you work in Android SDK (or based Linux OS). Here are some official documents:
- [Data and file storage overview](https://developer.android.com/guide/topics/data/data-storage)
- [Application Sandbox](https://source.android.com/security/app-sandbox)

In README, I focus on Flutter context, the concepts related to native SDK (Android and iOS) are beyond that document.
