### ISSUE TITLE
iOS download issue

### ISSUE THREAD

**Issue by Joyker** [fluttercommunity/flutter_downloader#460]
Download status stuck in enqueued and nothing happens. Empty debug messages. tested in real device, versions 1.5.0-1.5.2)

Android work well as expected

Hope for help, thanks in advance!

Edit:
Solved. In my app i enqueued download, then load this task by id. Based on this information i  create database record with field path 
` path = newtask[0].savedDir + "/" + fileName`
where newtask is:
```
newtask = await FlutterDownloader.loadTasksWithRawQuery(
        query: "SELECT * FROM task WHERE task_id=" + "\"" + taskId + "\"");  
```
newtask[0].savedDir gives wrong value! Instead of: 
`...../Documents/ `
it returns 
`...../Documents/(null)/`

**Comment by zoozobib** [comment]
same problem too
