### ISSUE TITLE
Flutter downloader not working with dynamic url

### ISSUE THREAD

**Issue by parthgandhi85** [fluttercommunity/flutter_downloader#463]
I have a strange issue with my flutter app. I am using flutter_downloader library for downloading pdf files.The issue is when i try to download a file using static download file link i am able to download but when i change the download link to dynamic links it doesnt download. This issue only happens in iOS and not in Android. Here is the code .

This works

```
await FlutterDownloader.enqueue(
       url: "http://server.com/file.pdf",
       savedDir: value,
       showNotification: false, 
       openFileFromNotification: false)
```

But this doesnt:

```
where BASE_URL="http://server.com"
    DOWNLOAD_PDF="endpoint/"
    fileName="file.pdf"


    await FlutterDownloader.enqueue(
           url: BASE_URL+DOWNLOAD_PDF+fileName,
           savedDir: value,
           showNotification: false, 
           openFileFromNotification: false)
```
           
Anyone who can help me out with this can please help. Help Appreciated.

I am new to flutter so please help me out.

**Comment by behzadcym** [comment]
I guess there is an issue in your dynamic URL. Shouldn't there be an "/" between your BASE_URL and DOWNLOAD_PDF?

**Comment by bartekpacia** [comment]
I'm pretty sure @behzadcym is right. You're missing a `/` between `BASE_URL` and `DOWNLOAD_PDF`.

Closing. If this reoccurs, please create a new issue using bug report template.
