### ISSUE TITLE
Download Fails

### ISSUE THREAD

**Issue by aqalgorepublic** [fluttercommunity/flutter_downloader#472]
The download fails most of the time, with error 
**Update too frequently!!!!, but it is the final update, we should sleep a second to ensure the update call can be processed**
What happens is that often it works alternatively, and sometimes it fails all in one row, but sometimes the download is a success.

**Comment by erperejildo** [comment]
@aqalgorepublic how did you resolve this?

**Comment by easazade** [comment]
same problem
