### ISSUE TITLE
method not available: ext.flutter.inspector.setPubRootDirectories

### ISSUE THREAD

**Issue by temwa** [fluttercommunity/flutter_downloader#473]
Hi,

I am getting the error below when I try to download a file using flutter_downloader.

> Error handling 'serviceExtension' custom request: method not available: ext.flutter.inspector.setPubRootDirectories

My Google searches seem to indicate that this is a problem with Firebase. I have [firebase_messaging](https://pub.dev/packages/firebase_messaging) installed but the issue only comes up when I try to downlaod a file using flutter_downloader.

Please assist.

Herewith the code snippet for the downloader;

```
IconButton(
                  icon: Icon(Icons.download),
                  onPressed: () async {
                    final status = await Permission.storage.request();

                    if (status.isGranted) {
                      final externalDir = await getExternalStorageDirectory();

                      final id = await FlutterDownloader.enqueue(
                        url: files[i].file,
                        fileName: 'filename',
                        savedDir: externalDir.path,
                        showNotification: true,
                        openFileFromNotification: true,
                      );
                    } else {
                      print('Permission denied');
                    }
                  },
                ),
```

**Comment by biswa1751** [comment]
I also faced this issue in ios and solved by completing the iOS integration steps

**Comment by temwa** [comment]
Implementing the "Update download progress:" section in the flutter_downloader Readme section solved the issue.
