### ISSUE TITLE
Problem With 1.6.1

### ISSUE THREAD

**Issue by Tanvir3488** [fluttercommunity/flutter_downloader#474]
1.Sometime failed Download without any issue After again click Downloaded success
2. After successful download clicking on notification downloaded file not open
3. can not find downloaded file in file manager / got that file in given name but the file size always 0 byte

Please Help

**Comment by behzadcym** [comment]
the exact same problem for me

**Comment by Tanvir3488** [comment]
This problem raise in amdroid Q&R in amdroid pie this package perform perfectly

**Comment by xSuperMu** [comment]
Same problem with me

**Comment by keehoo** [comment]
I can confirm this is happening.

**Comment by bartekpacia** [comment]
Does it still occur with the newest version (`v1.7.4`)?
