### ISSUE TITLE
Execution failed for task ':app:generateDebugBuildConfig'.

### ISSUE THREAD

**Issue by goku-org** [fluttercommunity/flutter_downloader#476]
i am using latest version = 1.6.0
this issue still creating a trouble

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugBuildConfig'.
> Failed to calculate the value of task ':app:generateDebugBuildConfig' property 'buildConfigPackageName'.
   > Failed to query the value of property 'packageName'.
      > org.xml.sax.SAXParseException; systemId: file:/D:/Project/****/android/app/src/main/AndroidManifest.xml; lineNumber: 66; columnNumber: 28; The prefix "tools" for attribute "tools:node" associated with an element type "provider" is not bound.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
`

**Comment by Tanvir3488** [comment]
in menifest file you should defile tools then this error will solve
