### ISSUE TITLE
getting this issue on downloading any file from the web

### ISSUE THREAD

**Issue by imyogisingh** [fluttercommunity/flutter_downloader#479]
Error handling 'checkPlatformOverride' custom request: method not available: ext.flutter.platformOverride
Error handling 'checkBrightnessOverride' custom request: method not available: ext.flutter.brightnessOverride
Error handling 'checkIsWidgetCreationTracked' custom request: Bad state: No element
Error handling 'serviceExtension' custom request: app '9b11d005-2076-4822-8344-4bbdf8eab682' not found

**Comment by imyogisingh** [comment]
Fixed

**Comment by swapnilsuccessive** [comment]
hey what was this issue?

**Comment by imyogisingh** [comment]
Fixed

**Comment by dwievermos** [comment]
Hey can you describe how to fixed it ? i having same issues here

**Comment by imyogisingh** [comment]
Just register a  callback method in init state.
