### ISSUE TITLE
How to check if a file has been downloaded

### ISSUE THREAD

**Issue by shingohu** [fluttercommunity/flutter_downloader#49]
I want to check a file has been downloaded by url? how can i do，or should you provide a query method

**Comment by hnvn** [comment]
Load all completed tasks and check your expected URL among URLs of these tasks.
```
final tasks = await FlutterDownloader.loadTasksWithRawQuery(query: 'SELECT * FROM task WHERE status=3');
```

**Comment by shingohu** [comment]
I have a few more questions ^_^

1. DownLoadTask bean can provide a localPath attribute to record the localPath of the file because I need to open the downloaded file in my app when the download is complete

2. Why not just download the same url once? I think we can use the parameter of enqueue method to encrypt MD5 to confirm whether it is the same request or not

**Comment by hnvn** [comment]
1. your file path = saveDir + filename
2. You can handle this rule in your own codes.

**Comment by shingohu** [comment]
1. I've seen your code  localPath is different with saveDir+filename，if filename == null

**Comment by hnvn** [comment]
If you don't give `filename` a value when you call `FlutterDownloader.enqueue()`, `filename` is still `null` when you load it from DB, so you should set an explicit value for `filename` in `enqueue` function

**Comment by ShoaibKakal** [comment]
`import 'dart:io' as io;
var syncPath = await path;

// for a file
await io.File(syncPath).exists();
io.File(syncPath).existsSync();

// for a directory
await io.Directory(syncPath).exists();
io.Directory(syncPath).existsSync();`

**Comment by NullByte08** [comment]
> Why not just download the same url once? I think we can use the parameter of enqueue method to encrypt MD5 to confirm whether it is the same request or not

@shingohu how did you do this part btw? Can you show the code pls?
