### ISSUE TITLE
 Permission Denial: writing com.android.providers.media.MediaProvider

### ISSUE THREAD

**Issue by ajayamal** [fluttercommunity/flutter_downloader#496]
When i try to download an image from url i am getting this error  `
W/System.err( 1845): java.lang.SecurityException: Permission Denial: writing com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=1845, uid=10513 requires android.permission.WRITE_EXTERNAL_STORAGE, or grantUriPermission()` but i am using this plugin to download videos as well and its working fine on MP4

`  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.WRITE_INTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.READ_INTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.INTERNET"/>`

I tried adding these permissions it is still not working. PS(minSdkVersion: 23)

**Comment by bouziane** [comment]
I have same issue when i tried to read a mp3 file

```
java.lang.SecurityException: Permission Denial: reading vn.hunghd.flutterdownloader.DownloadedFileProvider uri content://com.sn114.flutter_downloader.provider/external_files/Download/audio-bande_annonce_en_bambara-_clv_feuilleton_radio-bm.mp3 from pid=4131, uid=10318 requires the provider be exported, or grantUriPermission()
E/DatabaseUtils(10811): 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:848)
E/DatabaseUtils(10811): 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:689)
E/DatabaseUtils(10811): 	at android.content.ContentProvider$Transport.query(ContentProvider.java:244)
E/DatabaseUtils(10811): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:106)
E/DatabaseUtils(10811): 	at android.os.Binder.execTransactInternal(Binder.java:1157)
E/DatabaseUtils(10811): 	at android.os.Binder.execTransact(Binder.java:1126)

```

**Comment by Andreigr0** [comment]
I believe this is the solution https://github.com/fluttercommunity/flutter_downloader/issues/773#issuecomment-1347431145
