### ISSUE TITLE
pdf.save is missing

### ISSUE THREAD

**Issue by Laxman007** [fluttercommunity/flutter_downloader#50]
Compiler message:
lib/DownloadinTransactions.dart:142:29: Error: The method 'save' isn't defined for the class 'widget::Document'.
Try correcting the name to the name of an existing method, or defining a method named 'save'.
  file.writeAsBytesSync(pdf.save());
                            ^^^^
Compiler failed on /Users/ravipoovaiah/Documents/Flutter/Git/jellow_senior_/mbank2/lib/DownloadinTransactions.dart

**Comment by hnvn** [comment]
Have no idea about your question at all. There's no class or variable named `pdf` in source codes of this plugin
