### ISSUE TITLE
error: resource android:attr/fontVariationSettings not found.

### ISSUE THREAD

**Issue by xiaojia21190** [fluttercommunity/flutter_downloader#51]
![image](https://user-images.githubusercontent.com/16084693/53941508-390e9b80-40f3-11e9-8a60-52c08db5bfaf.png)

**Comment by xiaojia21190** [comment]
build faile

**Comment by hnvn** [comment]
I have a no idea with this error message but it looks like this one #42

**Comment by xiaojia21190** [comment]
open *.apk file ?

**Comment by hnvn** [comment]
you need REQUEST_INSTALL_PACKAGES permission to open APK files
