### ISSUE TITLE
Package doesn't exist error android

### ISSUE THREAD

**Issue by KevalPrajapati** [fluttercommunity/flutter_downloader#512]
This error is thrown while building the app for android
```
\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:20: error: package vn.hunghd.flutterdownloader does not exist
    flutterEngine.getPlugins().add(new vn.hunghd.flutterdownloader.FlutterDownloaderPlugin());
     
```                                                             ^
 
using latest version of plugin and flutter.

**Comment by KevalPrajapati** [comment]
It was a flutter error. I reinstalled flutter and it solved the problem.

**Comment by papmodern** [comment]
I have the same issue with flutter 3.3.6

**Comment by Dalakoti07** [comment]
I am also facing same issue with 3.3.0

**Comment by cvalab** [comment]
Same for Flutter 3.0.5.
Moreover, the assembly of the application broke even for the code that was correctly assembled earlier.
For the same commit in the same environment.
On October 25, the application was built, but yesterday it was not, including in the CI / DI environment.

**Comment by papmodern** [comment]
issue should reopen @KevalPrajapati

**Comment by KevalPrajapati** [comment]
> issue should reopen @KevalPrajapati 

Hey 
I will try building a sample once again with the latest versions.
Just to check if it fails for me too.

**Comment by xalabax** [comment]
My solution
1. Comment
        

        
        
        
        2. Remove
        buildscript {
    repositories {
        // ...
        maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal
    }
    dependencies {
        // ...
        // OneSignal-Gradle-Plugin
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.12.8'
    }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

3. Change
distributionUrl=https://services.gradle.org/distributions/gradle-6.7.1-all.zip
to
distributionUrl=https://services.gradle.org/distributions/gradle-7.4-all.zip

4. Change
        maven { url 'https://maven.google.com' }
to
        google()

**Comment by cvalab** [comment]
My solution
1. Comment
        

        
        
        

  2. Remove
        buildscript {
    repositories {
        // ...
        maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal
    }
    dependencies {
        // ...
        // OneSignal-Gradle-Plugin
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.12.8'
    }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

3. Change
distributionUrl=https://services.gradle.org/distributions/gradle-6.7.1-all.zip
to
distributionUrl=https://services.gradle.org/distributions/gradle-7.4-all.zip

4. Change
        maven { url 'https://maven.google.com' }
to
        google()
