### ISSUE TITLE
Download Failled

### ISSUE THREAD

**Issue by adeleof** [fluttercommunity/flutter_downloader#517]
hi,
i try running the sample code, and when trying to download the first item - Learning  Android Sttudio, the download is failled

`
I/flutter ( 1535): UI Isolate Callback: [5257fda7-4ff4-43d7-8221-547d5a6af01a, DownloadTaskStatus(4), -1]
D/DownloadWorker( 1535): Update notification: {notificationId: 1, title: learning_android_studio.pdf, status: 4, progress: -1}
W/System.err( 1535): java.net.ProtocolException: unexpected end of stream
W/System.err( 1535): 	at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:396)
W/System.err( 1535): 	at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
W/System.err( 1535): 	at java.io.InputStream.read(InputStream.java:101)
W/System.err( 1535): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:351)
W/System.err( 1535): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:203)
W/System.err( 1535): 	at androidx.work.Worker$1.run(Worker.java:85)
W/System.err( 1535): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err( 1535): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err( 1535): 	at java.lang.Thread.run(Thread.java:764)
I/WM-WorkerWrapper( 1535): Worker result SUCCESS for Work [ id=5257fda7-4ff4-43d7-8221-547d5a6af01a, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]
`

but its work fine with image item.

**Comment by abdullah432** [comment]
Same issue, If you fix this, Please share the solution
