### ISSUE TITLE
 AAPT: error: unexpected element <queries> found in <manifest> after upgrade from 1.5.2 to 1.7.0

### ISSUE THREAD

**Issue by mrjohnr** [fluttercommunity/flutter_downloader#528]
Hi
I've upgraded from 1.5.2 to 1.7.0 but on build got:

```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     D:\myapp\build\flutter_downloader\intermediates\library_manifest\debug\AndroidManifest.xml:8:5-12:15: AAPT: error: unexpected element <queries> found in <manifest>.

```
thanks for any clue

**Comment by midoshawky** [comment]
make sure you put them inside the `<Application>` tag

**Comment by mrjohnr** [comment]
what to put, I've just upgraded the package

**Comment by midoshawky** [comment]
its related to AndroidManifest.xml open android -> app -> src -> main -> main -> AndroidManifest.xml 
and make sure it look like thi
![Screen Shot 2021-09-18 at 2 52 05 AM](https://user-images.githubusercontent.com/33393194/133866623-8696e4f6-6ebd-4dc8-939d-3c356fb5df4d.png)
s

**Comment by mrjohnr** [comment]
meanwhile I've solved as [here](https://stackoverflow.com/a/64741539/3492996)
