### ISSUE TITLE
when i import flutter_downloader package and run project i got this error.please help

### ISSUE THREAD

**Issue by manishvvasaniya** [fluttercommunity/flutter_downloader#53]
00:05:31.582 1 info flutter.tools Launching lib\main.dart on Redmi 4 in debug mode...
00:05:31.613 2 info flutter.tools Initializing gradle...
00:05:32.975 3 info flutter.tools Resolving dependencies...
00:05:38.969 4 info flutter.tools Running Gradle task 'assembleDebug'...
00:05:44.075 5 info flutter.tools D8: Program type already present: android.support.v4.app.INotificationSideChannel
00:05:44.254 6 info flutter.tools 
00:05:44.254 7 info flutter.tools FAILURE: Build failed with an exception.
00:05:44.254 8 info flutter.tools 
00:05:44.256 9 info flutter.tools * What went wrong:
00:05:44.256 10 info flutter.tools Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
00:05:44.270 11 info flutter.tools > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\2.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\3.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\4.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\5.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\6.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\7.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\8.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\9.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\10.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\11.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\12.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\13.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\14.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\15.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\16.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\17.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\18.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\19.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\20.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\21.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\22.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\23.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\24.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\25.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\26.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\27.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\28.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\29.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\30.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\31.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\32.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\33.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\34.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\35.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\36.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\37.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\38.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\39.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\40.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\41.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\42.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\43.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\44.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\45.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\46.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\47.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\48.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\49.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\50.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\51.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\52.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\54.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\55.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\56.jar, C:\Users\Manish\Desktop\videostatus\build\app\intermediates\transforms\dexBuilder\debug\57.jar
00:05:44.270 12 info flutter.tools 
00:05:44.270 13 info flutter.tools   Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
00:05:44.270 14 info flutter.tools   Program type already present: android.support.v4.app.INotificationSideChannel
00:05:44.270 15 info flutter.tools 
00:05:44.270 16 info flutter.tools * Try:
00:05:44.270 17 info flutter.tools Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
00:05:44.270 18 info flutter.tools 
00:05:44.270 19 info flutter.tools * Get more help at https://help.gradle.org
00:05:44.270 20 info flutter.tools 
00:05:44.270 21 info flutter.tools BUILD FAILED in 5s
00:05:44.676 22 info flutter.tools *******************************************************************************************
00:05:44.676 23 info flutter.tools The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
00:05:44.676 24 info flutter.tools See https://goo.gl/CP92wY for more information on the problem and how to fix it.
00:05:44.676 25 info flutter.tools

**Comment by manishvvasaniya** [comment]
00:18:41.532 1 info flutter.tools Launching lib\main.dart on Redmi 4 in debug mode...
00:18:41.657 2 info flutter.tools Initializing gradle...
00:18:42.926 3 info flutter.tools Resolving dependencies...
00:18:47.260 4 info flutter.tools Running Gradle task 'assembleDebug'...
00:18:55.515 5 info flutter.tools C:\Program Files\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_downloader-1.1.6\android\src\main\java\vn\hunghd\flutterdownloader\DownloadWorker.java:10: error: package android.support.v4.content does not exist
00:18:55.515 6 info flutter.tools import android.support.v4.content.LocalBroadcastManager;
00:18:55.515 7 info flutter.tools                                  ^
00:18:55.600 8 info flutter.tools C:\Program Files\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_downloader-1.1.6\android\src\main\java\vn\hunghd\flutterdownloader\FlutterDownloaderPlugin.java:11: error: package android.support.v4.content does not exist
00:18:55.600 9 info flutter.tools import android.support.v4.content.LocalBroadcastManager;
00:18:55.600 10 info flutter.tools                                  ^
00:18:55.600 11 info flutter.tools C:\Program Files\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_downloader-1.1.6\android\src\main\java\vn\hunghd\flutterdownloader\DownloadWorker.java:342: error: cannot find symbol
00:18:55.600 12 info flutter.tools         LocalBroadcastManager.getInstance(context).sendBroadcast(intent);
00:18:55.600 13 info flutter.tools         ^
00:18:55.600 14 info flutter.tools   symbol:   variable LocalBroadcastManager
00:18:55.600 15 info flutter.tools   location: class DownloadWorker
00:18:55.600 16 info flutter.tools C:\Program Files\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_downloader-1.1.6\android\src\main\java\vn\hunghd\flutterdownloader\FlutterDownloaderPlugin.java:104: error: cannot find symbol
00:18:55.600 17 info flutter.tools             LocalBroadcastManager.getInstance(context).registerReceiver(updateProcessEventReceiver,
00:18:55.600 18 info flutter.tools             ^
00:18:55.600 19 info flutter.tools   symbol:   variable LocalBroadcastManager
00:18:55.600 20 info flutter.tools   location: class FlutterDownloaderPlugin
00:18:55.600 21 info flutter.tools C:\Program Files\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_downloader-1.1.6\android\src\main\java\vn\hunghd\flutterdownloader\FlutterDownloaderPlugin.java:122: error: cannot find symbol
00:18:55.601 22 info flutter.tools             LocalBroadcastManager.getInstance(context).unregisterReceiver(updateProcessEventReceiver);
00:18:55.601 23 info flutter.tools             ^
00:18:55.601 24 info flutter.tools   symbol:   variable LocalBroadcastManager
00:18:55.601 25 info flutter.tools   location: class FlutterDownloaderPlugin
00:18:55.601 26 info flutter.tools 5 errors
00:18:55.701 27 info flutter.tools 
00:18:55.702 28 info flutter.tools FAILURE: Build failed with an exception.
00:18:55.702 29 info flutter.tools 
00:18:55.702 30 info flutter.tools * What went wrong:
00:18:55.702 31 info flutter.tools Execution failed for task ':flutter_downloader:compileDebugJavaWithJavac'.
00:18:55.702 32 info flutter.tools > Compilation failed; see the compiler error output for details.
00:18:55.702 33 info flutter.tools 
00:18:55.702 34 info flutter.tools * Try:
00:18:55.702 35 info flutter.tools Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
00:18:55.702 36 info flutter.tools 
00:18:55.702 37 info flutter.tools * Get more help at https://help.gradle.org
00:18:55.702 38 info flutter.tools 
00:18:55.702 39 info flutter.tools BUILD FAILED in 8s
00:18:56.058 40 info flutter.tools *******************************************************************************************
00:18:56.058 41 info flutter.tools The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.

**Comment by hnvn** [comment]
#42
