### ISSUE TITLE
apk can not open in android8.0

### ISSUE THREAD

**Issue by welldone217** [fluttercommunity/flutter_downloader#54]
my code is

  FlutterDownloader.enqueue(
          url: http://xxxx.com/xxy.apk,
          savedDir: _dir,
          fileName: _filename,
          showNotification: true,
          openFileFromNotification: opend)
      .then((taskid) {
       FlutterDownloader.open(taskId: taskid); 
  });

this not work and also not  work in showNotification.

in showNotification it give me a open way page.
[the image](https://txl.wfyizhan.com/static/uploads/2019/03/12/201903121629486344.jpg)

**Comment by hnvn** [comment]
you need REQUEST_INSTALL_PACKAGES permission to open APK files

**Comment by welldone217** [comment]
I did it. but not work.  and I can not found the install apk permission  in  the permission_handler 3.0.0 .

**Comment by hnvn** [comment]
check **PackageInstaller** in README

**Comment by welldone217** [comment]
can not open  Exactly,

here is my code

`    FlutterDownloader.enqueue(
        url: url,
        savedDir: _path,
        fileName: _filename,
        showNotification: true,
        openFileFromNotification: true);
    FlutterDownloader.registerCallback((taskId, status, progress) {
      if (status == DownloadTaskStatus.complete) {
        FlutterDownloader.open(taskId: taskId);
      }
    });
`

also add 
    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" /> to AndroidManifest.xml
