### ISSUE TITLE
Not Saving file in desired given path

### ISSUE THREAD

**Issue by krunal1156** [fluttercommunity/flutter_downloader#540]
I have updated the library from 1.6.1 to 1.7.0 
i am facing very strange issue in android only in ios library works fine..
in android  i m not able to store file in given desire location by default library store files in  download folder only. i have checked the libraries database where its manages taskId and path and urls. in that database given storage path is what i set while download the request but file not saved on that location and instead of that location its stores files only in the download folder of external storage only.

**Comment by mpeng5120** [comment]
一样在Bug ,传了保存路径没有用到，  DownloadWorker.java   341行   saveFilePath

**Comment by yelkamel** [comment]
I have the same issue :/

**Comment by hnvn** [comment]
Duplicate of #533. Please have a look at this [comment](https://github.com/fluttercommunity/flutter_downloader/issues/533#issuecomment-939214932).
