### ISSUE TITLE
Exception while trying to download a file in android 9 

### ISSUE THREAD

**Issue by sanalkv** [fluttercommunity/flutter_downloader#541]
W/System.err(19848): java.io.IOException: Permission denied
W/System.err(19848): 	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
W/System.err(19848): 	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
W/System.err(19848): 	at java.io.File.createNewFile(File.java:1008)
W/System.err(19848): 	at vn.hunghd.flutterdownloader.DownloadWorker.addFileToDownloadsApi21(DownloadWorker.java:468)
W/System.err(19848): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:361)
W/System.err(19848): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:208)
W/System.err(19848): 	at androidx.work.Worker$1.run(Worker.java:85)
W/System.err(19848): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(19848): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(19848): 	at java.lang.Thread.run(Thread.java:764)
D/DownloadWorker(19848): Create a file using java.io API failed
D/DownloadWorker(19848): Update notification: {notificationId: 1, title: https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_700KB.mp3, status: 4, progress: -1}
W/System.err(19848): java.lang.NullPointerException
W/System.err(19848): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
W/System.err(19848): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:362)
W/System.err(19848): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:208)
W/System.err(19848): 	at androidx.work.Worker$1.run(Worker.java:85)
W/System.err(19848): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(19848): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(19848): 	at java.lang.Thread.run(Thread.java:764)
I/WM-WorkerWrapper(19848): Worker result FAILURE for Work [ id=57ae16b1-a306-4ec7-9985-8a32944b37ae, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]

**Comment by sanalkv** [comment]
Looks like i was using the package without the permission request, it was working until the 1.7.0 version. Works fine now after following the example project on how to ask for permission during download.

**Comment by jr24jr** [comment]
you need to have **MANAGE_EXTERNAL_STORAGE** permission
