### ISSUE TITLE
 java.lang.NullPointerException: uri

### ISSUE THREAD

**Issue by bugrevealingbme** [fluttercommunity/flutter_downloader#544]
I'm completely sure of the permissions. Some files are downloading, some files are not. APK files. There was no problem a few hours ago but now it is!!!!!

I/flutter (16748): Background Isolate Callback: task (a7b57d68-7c38-43a2-9726-c23780db97c3) is in status (DownloadTaskStatus(4)) and process (-1)
W/System.err(16748): java.lang.NullPointerException: uri
W/System.err(16748): 	at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:133)
W/System.err(16748): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1492)
W/System.err(16748): 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1242)
W/System.err(16748): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:358)
W/System.err(16748): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:208)
W/System.err(16748): 	at androidx.work.Worker$1.run(Worker.java:85)

**Comment by hnvn** [comment]
Duplication of #548
