### ISSUE TITLE
Some file can`t use pause when download 

### ISSUE THREAD

**Issue by Lyoona** [fluttercommunity/flutter_downloader#55]
i use the example code , but not yours file. when i use the pause, some file will error:
save partial downloaded data to a file: failure
    "BackgroundDownloadTask <952771EC-E5EA-4572-88D5-FEF0DF6E9969>.<4>",
    "LocalDownloadTask <952771EC-E5EA-4572-88D5-FEF0DF6E9969>.<4>"
), _NSURLErrorFailingURLSessionTaskErrorKey=BackgroundDownloadTask <952771EC-E5EA-4572-88D5-FEF0DF6E9969>.<4>, NSURLSessionDownloadTaskResumeData=<62706c69 73743030 d4010203 04050608 09582476 65727369 6f6e5824 6f626a65 63747359 24617263 68697665 72542474 6f701200 0186a0a1 0755246e 756c6c5f 100f4e53 4b657965 64417263 68697665 72d10a0b 5f101b4e 534b6579 65644172 63686976 65526f6f 744f626a 6563744b 65798000 08111a23 2d323739 3f515472 00000000 00000101 00000000 0000000c 00000000 00000000 00000000 00000074>, NSLocalizedDescription=cancelled} [-999]
URLSession:task:didCompleteWithError:
HTTP status code: 200
Download completed with error: cancelled

and when i use resume:
flutter: not found resume data, this task cannot be resume

so，what`s wrong with it? is there something wrong on server? please help me. and i`m sorry to my english is poor

**Comment by Lyoona** [comment]
and when the network is not good, download a few time later, the pause can`t work . restart the app still can`t solve it

**Comment by hnvn** [comment]
It's hard to say anything from these error logs. It's good to have codes that can reproduce this error.

**Comment by khduy1796** [comment]
When I pause a process download, I recieves this log:
```
"BackgroundDownloadTask <17669831-FE4C-4472-88F7-A80B5FCD1970>.<1>",
    "LocalDownloadTask <17669831-FE4C-4472-88F7-A80B5FCD1970>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=BackgroundDownloadTask <17669831-FE4C-4472-88F7-A80B5FCD1970>.<1>, NSURLSessionDownloadTaskResumeData=<62706c69 73743030 d4010203 04050608 09582476 65727369 6f6e5824 6f626a65 63747359 24617263 68697665 72542474 6f701200 0186a0a1 0755246e 756c6c5f 100f4e53 4b657965 64417263 68697665 72d10a0b 5f101b4e 534b6579 65644172 63686976 65526f6f 744f626a 6563744b 65798000 08111a23 2d323739 3f515472 00000000 00000101 00000000 00 [<decode: missing data>]
```
And when resume, I get the status of this task is DownloadTaskStatus(4) and this log:
```
    "BackgroundDownloadTask <9AC1E835-7336-4BAF-BA1A-9088199D41FA>.<2>"
), _NSURLErrorFailingURLSessionTaskErrorKey=BackgroundDownloadTask <9AC1E835-7336-4BAF-BA1A-9088199D41FA>.<2>} [-3003]
flutter: Download task (taskId) is in status (DownloadTaskStatus(2)) and process (22), true
flutter: Download task (taskId) is in status (DownloadTaskStatus(4)) and process (-1), true
```
What's happend?
