### ISSUE TITLE
the mincompilesdk (31) specified in a [ ] dependency's aar metadata (meta-inf/com/android/build/gradle/aar-metadata.properties) [ ]

### ISSUE THREAD

**Issue by kennest** [fluttercommunity/flutter_downloader#552]
Please i got this error when i try to add flutter_downloader to my app:
`the mincompilesdk (31) specified in a [ ] dependency's aar metadata (meta-inf/com/android/build/gradle/aar-metadata.properties) [ ] is greater than this module's compilesdkversion (android-30).`
Help me.

**Comment by Rontu22** [comment]
I tried both of the above ways , but it couldnot resolve the issue above. Can anyone suggest solution for this ?
After changing compileSDKVersion to 31 , it is showing the following error :
`LocationProvider in android.location has been deprecated
[  ] import android.location.LocationProvider;
[  ] error: warnings found and -Werror specified`
