### ISSUE TITLE
flutter_downloader: ^1.7.1 NOT WORKING SUDDENLY 

### ISSUE THREAD

**Issue by MdSarfarazAlam** [fluttercommunity/flutter_downloader#559]
flutter_downloader: ^1.7.1
When I am Triggering EVENT  "FlutterDownloader.enqueue"

the below method is not getting invoke.
 _receivePort.listen((msg)){
});

i am getting "task id" from "FlutterDownloader.enqueue"  method  but  _receivePort.listen((msg)){
}); is not getting invoked.
it was working before but suddenly it stopped working.

**Comment by bartekpacia** [comment]
No reproducible sample.
