### ISSUE TITLE
Manifest merger failed : android:exported needs to be explicitly specified for <service>. 

### ISSUE THREAD

**Issue by alexaung** [fluttercommunity/flutter_downloader#562]
flutter_downloader: ^1.7.1
Manifest merger failed : android:exported needs to be explicitly specified for <service>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

    `<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="org.thitsarparami.thitsarparami"
    xmlns:tools="http://schemas.android.com/tools" >
       <uses-permission android:name="android.permission.WAKE_LOCK"/>
       <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
      <uses-permission android:name="android.permission.INTERNET" /> 
      <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
      <application
        android:label="Thitsarparami"
        android:usesCleartextTraffic="true"
        android:allowBackup="false"
        android:fullBackupOnly="false"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name="com.ryanheise.audioservice.AudioServiceActivity"
            android:exported="false"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            
            
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        
        <service android:name="com.ryanheise.audioservice.AudioService">
          <intent-filter>
            <action android:name="android.media.browse.MediaBrowserService" />
          </intent-filter>
        </service>
        
        <receiver android:name="com.ryanheise.audioservice.MediaButtonReceiver" >
          <intent-filter>
            <action android:name="android.intent.action.MEDIA_BUTTON" />
          </intent-filter>
        </receiver> 
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />

        <provider
            android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider"
            android:authorities="${applicationId}.flutter_downloader.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>
        <provider
            android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider"
            android:authorities="${applicationId}.flutter_downloader.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>

        
        
        <provider
            android:name="androidx.startup.InitializationProvider"
            android:authorities="${applicationId}.androidx-startup"
            android:exported="false"
            tools:node="merge">
            <meta-data
                android:name="androidx.work.WorkManagerInitializer"
                android:value="androidx.startup"
                tools:node="remove" />
        </provider>

        
        <provider
            android:name="vn.hunghd.flutterdownloader.FlutterDownloaderInitializer"
            android:authorities="${applicationId}.flutter-downloader-init"
            android:exported="false">
            <meta-data
                android:name="vn.hunghd.flutterdownloader.MAX_CONCURRENT_TASKS"
                android:value="3" />
        </provider>
        

        <meta-data
            android:name="vn.hunghd.flutterdownloader.NOTIFICATION_ICON"
            android:resource="@drawable/ic_stat_logo" />
    </application>
</manifest>
`

**Comment by alexaung** [comment]
It solved adding android:exported attribute to intents and receivers

**Comment by 76765357** [comment]
> 
same problem
how do you resolve this? please help :)
can you tell the detail?

**Comment by hnvn** [comment]
it is the problem of Android 12, you need to add `android:exported` android your AndroidManifest

**Comment by alexaung** [comment]
add android:exported in instent-filter of AndroidManifest.xml as follow. 

`<intent-filter android:exported="false">`
