### ISSUE TITLE
suddenly dead when I tap requestDownload, only in android

### ISSUE THREAD

**Issue by Immovable-maker** [fluttercommunity/flutter_downloader#564]
I use 1.7.1 version and it suddenly dead in android, not iOS

D/PathProviderPlugin( 5436): Don't use TaskQueues.
W/FlutterEngineCxnRegstry( 5436): Attempted to register plugin (io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry$ShimRegistrarAggregate@691e1b0) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.FlutterEngine@d00e829).
D/AndroidRuntime( 5436): Shutting down VM
E/AndroidRuntime( 5436): FATAL EXCEPTION: main
E/AndroidRuntime( 5436): Process: com.example.dev, PID: 5436
E/AndroidRuntime( 5436): kotlin.NotImplementedError: An operation is not implemented: Not yet implemented
E/AndroidRuntime( 5436): 	at com.example.Application.registerWith(Application.kt:15)
E/AndroidRuntime( 5436): 	at vn.hunghd.flutterdownloader.DownloadWorker.startBackgroundIsolate(DownloadWorker.java:140)
E/AndroidRuntime( 5436): 	at vn.hunghd.flutterdownloader.DownloadWorker.access$000(DownloadWorker.java:67)
E/AndroidRuntime( 5436): 	at vn.hunghd.flutterdownloader.DownloadWorker$1.run(DownloadWorker.java:111)
E/AndroidRuntime( 5436): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 5436): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 5436): 	at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime( 5436): 	at android.app.ActivityThread.main(ActivityThread.java:8059)
E/AndroidRuntime( 5436): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5436): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/AndroidRuntime( 5436): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
D/OOMEventManagerFK( 5436): checkEventAndDumpForJE: 0
I/Process ( 5436): Sending signal. PID: 5436 SIG: 9
Lost connection to device.

**Comment by Immovable-maker** [comment]
resolve by delete v1 embedding code in DownloadWorker

**Comment by abbas2501** [comment]
> resolve by delete v1 embedding code in DownloadWorker

Hey, Can you help me do that as well ?

**Comment by abbas2501** [comment]
> I use 1.7.1 version and it suddenly dead in android, not iOS
> 
> D/PathProviderPlugin( 5436): Don't use TaskQueues. W/FlutterEngineCxnRegstry( 5436): Attempted to register plugin (io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry$ShimRegistrarAggregate@691e1b0) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.FlutterEngine@d00e829). D/AndroidRuntime( 5436): Shutting down VM E/AndroidRuntime( 5436): FATAL EXCEPTION: main E/AndroidRuntime( 5436): Process: com.example.dev, PID: 5436 E/AndroidRuntime( 5436): kotlin.NotImplementedError: An operation is not implemented: Not yet implemented E/AndroidRuntime( 5436): at com.example.Application.registerWith(Application.kt:15) E/AndroidRuntime( 5436): at vn.hunghd.flutterdownloader.DownloadWorker.startBackgroundIsolate(DownloadWorker.java:140) E/AndroidRuntime( 5436): at vn.hunghd.flutterdownloader.DownloadWorker.access$000(DownloadWorker.java:67) E/AndroidRuntime( 5436): at vn.hunghd.flutterdownloader.DownloadWorker$1.run(DownloadWorker.java:111) E/AndroidRuntime( 5436): at android.os.Handler.handleCallback(Handler.java:938) E/AndroidRuntime( 5436): at android.os.Handler.dispatchMessage(Handler.java:99) E/AndroidRuntime( 5436): at android.os.Looper.loop(Looper.java:236) E/AndroidRuntime( 5436): at android.app.ActivityThread.main(ActivityThread.java:8059) E/AndroidRuntime( 5436): at java.lang.reflect.Method.invoke(Native Method) E/AndroidRuntime( 5436): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656) E/AndroidRuntime( 5436): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) D/OOMEventManagerFK( 5436): checkEventAndDumpForJE: 0 I/Process ( 5436): Sending signal. PID: 5436 SIG: 9 Lost connection to device.

Also would really really appreciate if you can share your flutter_downloader verison, both build.gradle, and android manifest. This has taken quite a bit of time for me to be resolved.

**Comment by abbas2501** [comment]
> resolve by delete v1 embedding code in DownloadWorker

Got it fixed, thanks a lot !!
