### ISSUE TITLE
how to dispose?

### ISSUE THREAD

**Issue by gitzhangliang** [fluttercommunity/flutter_downloader#57]
+--- project :flutter_downloader
|    +--- android.arch.work:work-runtime:1.0.0-beta05
|    |    +--- android.arch.lifecycle:extensions:1.1.0
|    |    |    +--- android.arch.lifecycle:runtime:1.1.0 (*)
|    |    |    +--- android.arch.core:common:1.1.0 -> 1.1.1 (*)
this    +--- android.arch.core:runtime:1.1.0 -> 1.1.1 (*)
|    |    |    +--- com.android.support:support-fragment:26.1.0 -> 27.1.1 (*)
|    |    |    +--- android.arch.lifecycle:common:1.1.0 (*)
|    |    |    +--- android.arch.lifecycle:livedata:1.1.0
this   |    |    +--- android.arch.core:runtime:1.1.0 -> 1.1.1 (*)
|    |    |    |    +--- android.arch.lifecycle:livedata-core:1.1.0 (*)
|    |    |    |    \--- android.arch.core:common:1.1.0 -> 1.1.1 (*)
|    |    |    \--- android.arch.lifecycle:viewmodel:1.1.0 (*)
|    |    \--- android.arch.persistence.room:runtime:1.1.1
|    |         +--- android.arch.persistence.room:common:1.1.1
|    |         |    \--- com.android.support:support-annotations:26.1.0 -> 27.1.1
|    |         +--- android.arch.persistence:db-framework:1.1.1
|    |         |    +--- com.android.support:support-annotations:26.1.0 -> 27.1.1
|    |         |    \--- android.arch.persistence:db:1.1.1
|    |         |         \--- com.android.support:support-annotations:26.1.0 -> 27.1.1
|    |         +--- android.arch.persistence:db:1.1.1 (*)
this        +--- android.arch.core:runtime:1.1.1 (*)
|    |         \--- com.android.support:support-core-utils:26.1.0 -> 27.1.1 (*)

**Comment by hnvn** [comment]
Sorry, what's the matter in your case?
