### ISSUE TITLE
Execution failed for task ':app:processDebugResources'

### ISSUE THREAD

**Issue by fliermanrw** [fluttercommunity/flutter_downloader#59]
Hi,

It seems that this package is not ready for Android X..could that be the case? My app works without this plugin activated. 

When running it produces the following error:
`Execution failed for task ':app:processDebugResources'.
Android resource linking failed
  Output:  ..mydirectory\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:29: error: resource android:attr/fontVariationSettings not found.
  ..mydirectory\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:29: error: resource android:attr/ttcIndex not found.
  error: failed linking references.`

if needed I can provide the full error response.

**Comment by hnvn** [comment]
https://github.com/fluttercommunity/flutter_downloader/issues/42#issuecomment-464291366. I see many questions like this, have you tried to look for it in closed issues yet?
