### ISSUE TITLE
Custom download function

### ISSUE THREAD

**Issue by Hassico** [fluttercommunity/flutter_downloader#594]
So my app is a comics reader. What I want to achieve is to download chapters one by one. To do that, I have to call the image urls from the api for each chapter. When a chapter is done, it moves to the next chapter. I do not want to fetch all images of all chapters to be downloaded at once to avoid hitting my limit on API calls in a short period. I fetch each chapters' images when the previous chapter is done. 

In this plugin, is it possible to customize all this in the function working in the background? I am not able to achieve this desired behavior, please help.

Thank you.

**Comment by bartekpacia** [comment]
Looks like this is not a problem with the plugin. 

If you have a general "programming question", please ask it on StackOverflow :)
