### ISSUE TITLE
File not shown in Android Downloads app after download complete

### ISSUE THREAD

**Issue by tobytraylor** [fluttercommunity/flutter_downloader#60]
Not sure if this is a defect or a user error.  After the file is downloaded it doesn't show up in the Downloads application on android.  It does show up as a download (down arrow) in the tasks list in the android top bar and i can see it as a notification that it completed successfully when i drag down the notification list.  Is there something that needs to be done to make it show up in the Downloads app?

**Comment by tobytraylor** [comment]
Looks like additional calls are needed: 
https://developer.android.com/reference/android/app/DownloadManager.html#addCompletedDownload(java.lang.String,%20java.lang.String,%20boolean,%20java.lang.String,%20java.lang.String,%20long,%20boolean)

**Comment by hnvn** [comment]
It's not this case. I don't use [DownloadManager](https://developer.android.com/reference/android/app/DownloadManager.html) in this plugin. I think your problem comes from where you save your files

**Comment by tobytraylor** [comment]
Right.  What i'm saying is that in order for the file to show up in the download app you have to invoke the DownloadManager.addCompletedDownload() method.  Maybe you can add a download parameter for this similar to showNotification and openFileFromNotification.  Something like "addToDownloadmanager" or something like that and then invoke the addCompletedDownload() method when that flag is set.  Also it says

"It is helpful to make the file scannable by MediaScanner by setting the param isMediaScannerScannable to true. It makes the file visible in media managing applications such as Gallery App, which could be a useful purpose of using this API."

So maybe adding a flag for whether to scan it using the media scanner would be good?

**Comment by hnvn** [comment]
My opinion is to keep this plugin simple, I don't have intention of doing support this feature. You can easily get it worked in your application by providing `Download` folder path as value of `saveDir`. This [plugin ](https://pub.dartlang.org/packages/downloads_path_provider) will give you the path of `Download` folder

**Comment by tobytraylor** [comment]
Oh!  I'd definitely mention this in the readme.  There might be more people that don't understand the inner workings of android download and don't know that that particular folder is required for the desired functionality.

**Comment by ohjs88** [comment]
I have the same issue. The downloaded image file does not appear in the gallery.

**Comment by hnvn** [comment]
it would bed fixed in v1.2.1
