### ISSUE TITLE
App Crash ( Fatal Exception : java.lang.NoSuchMethodError. )

### ISSUE THREAD

**Issue by brijeshbodariya** [fluttercommunity/flutter_downloader#608]
**com.ryanheise.audioservice.AudioService.createAction**

Fatal Exception: java.lang.NoSuchMethodError
No static method o(Landroid/content/res/Resources;Ljava/lang/String;I)Landroidx/core/graphics/drawable/IconCompat; in class Landroidx/core/graphics/drawable/IconCompat; or its super classes (declaration of 'androidx.core.graphics.drawable.IconCompat' appears in /data/app/androidx.test.tools.crawler-gnkfS0-G06JvHCkDLf-ehA==/base.apk)
androidx.core.app.NotificationCompat$Action.<init> (NotificationCompat.java:6)
com.ryanheise.audioservice.AudioService.createAction (AudioService.java:10)
com.ryanheise.audioservice.AudioService.setState (AudioService.java:60)
com.ryanheise.audioservice.AudioServicePlugin$AudioHandlerInterface.onMethodCall (AudioServicePlugin.java:467)
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage (MethodChannel.java:17)
io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart (DartMessenger.java:57)
io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage (FlutterJNI.java:4)

**Issue occurred in device:**

Model:Galaxy S9
Orientation: Portrait
OS Version: Android 8

Cannot reproduce, but appears on Firebase.

![Screenshot 2022-02-21 at 9 54 30 AM](https://user-images.githubusercontent.com/30180952/154888974-7a9c7fa1-ade9-43aa-b4f1-94febefdc2a0.png)

**Comment by joshoconnor89** [comment]
a
