### ISSUE TITLE
No opening File

### ISSUE THREAD

**Issue by Conquistardo** [fluttercommunity/flutter_downloader#62]
Hi there, I'm having a problem opening a downloaded file, I do not know if I'm missing something or have some logical error, my code is as follows:
```
final _download = await FlutterDownloader.enqueue(
        url: _link,
        savedDir: _downloadRoot,
        showNotification: true, // show download progress in status bar (for Android)
        openFileFromNotification: true, // click on notification to open downloaded file (for Android)
        fileName: _name
      ).then((taskId) async{
        String query = "SELECT * FROM task WHERE status=3";
        final tasks = await FlutterDownloader.loadTasksWithRawQuery(query: query);
        FlutterDownloader.open(taskId: tasks[1].taskId);
      });
```

When the download ends, the log shows me the following message:

> There's no application that can open the file  "file name"

but they are "xlsx" and "pdf", and I have applications installed to open them

**Comment by hnvn** [comment]
I've just tried to use this link: http://mtskheta.gov.ge/public/img/1530793528.xlsx in example project. It works well. I have Microsoft Excel in my Android phone and when I click on the downloaded file, it is opened in Excel as expected.

**Comment by hnvn** [comment]
I'm going to close this issue. Feel free to reopen it if you still need more help.

**Comment by AndroidNils** [comment]
Same Code and Same problem...

**Comment by parasthekoder** [comment]
Same issue, I have tried with `  savedDir: (await getExternalStorageDirectory()).path,` but still problem persists with exception.

`Failed to handle method call
E/MethodChannel#vn.hunghd/downloader(10179): java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/in.uneva.hms/app_flutter/Report200330-200330.pdf
E/MethodChannel#vn.hunghd/downloader(10179):    at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:744)
E/MethodChannel#vn.hunghd/downloader(10179):    at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:418)
E/MethodChannel#vn.hunghd/downloader(10179):    at vn.hunghd.flutterdownloader.IntentUtils.buildIntent(IntentUtils.java:23)
E/MethodChannel#vn.hunghd/downloader(10179):    at vn.hunghd.flutterdownloader.IntentUtils.validatedFileIntent(IntentUtils.java:35)
E/MethodChannel#vn.hunghd/downloader(10179):    at vn.hunghd.flutterdownloader.FlutterDownloaderPlugin.open(FlutterDownloaderPlugin.java:295)
E/MethodChannel#vn.hunghd/downloader(10179):    at vn.hunghd.flutterdownloader.FlutterDownloaderPlugin.onMethodCall(FlutterDownloaderPlugin.java:93)
E/MethodChannel#vn.hunghd/downloader(10179):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#vn.hunghd/downloader(10179):    at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#vn.hunghd/downloader(10179):    at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#vn.hunghd/downloader(10179):    at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#vn.hunghd/downloader(10179):    at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#vn.hunghd/downloader(10179):    at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#vn.hunghd/downloader(10179):    at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#vn.hunghd/downloader(10179):    at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#vn.hunghd/downloader(10179):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
E/MethodChannel#vn.hunghd/downloader(10179):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915)
I/flutter (10179): Failed to find configured root that contains /data/data/in.uneva.hms/app_flutter/Report200330-200330.pdf`

**Comment by kartikdrag** [comment]
**Same issue : check with android api level > 31**

D/DownloadWorker(  371): DownloadWorker{url=http://mtskheta.gov.ge/public/img/1530793528.xlsx,filename=null,savedDir=/storage/emulated/0/Download,header={"auth":"test_for_sql_encoding"},isResume=false,status=1
D/DownloadWorker(  371): Update notification: {notificationId: 7, title: http://mtskheta.gov.ge/public/img/1530793528.xlsx, status: 2, progress: 0}
I/flutter (  371): Callback on background isolate: task (75ffda14-c1e9-40d3-b6df-8656b1477bdd) is in status (DownloadTaskStatus(2)) and process (0)
I/flutter (  371): Callback on UI isolate: task (75ffda14-c1e9-40d3-b6df-8656b1477bdd) is in status (DownloadTaskStatus(2)) and process (0)
D/DownloadWorker(  371): Open connection to http://mtskheta.gov.ge/public/img/1530793528.xlsx
D/DownloadWorker(  371): Headers = {"auth":"test_for_sql_encoding"}
D/DownloadWorker(  371): Content-Type = application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
D/DownloadWorker(  371): Content-Length = -1
D/DownloadWorker(  371): Charset = null
D/DownloadWorker(  371): Content-Disposition = null
D/DownloadWorker(  371): fileName = 1530793528.xlsx
D/DownloadWorker(  371): Update notification: {notificationId: 7, title: 1530793528.xlsx, status: 2, progress: -366100}
I/flutter (  371): Callback on background isolate: task (75ffda14-c1e9-40d3-b6df-8656b1477bdd) is in status (DownloadTaskStatus(2)) and process (-366100)
I/flutter (  371): Callback on UI isolate: task (75ffda14-c1e9-40d3-b6df-8656b1477bdd) is in status (DownloadTaskStatus(2)) and process (-366100)
**D/DownloadWorker(  371): There's no application that can open the file /storage/emulated/0/Download/1530793528.xlsx**
D/DownloadWorker(  371): Update notification: {notificationId: 7, title: 1530793528.xlsx, status: 3, progress: 100}
I/flutter (  371): Callback on background isolate: task (75ffda14-c1e9-40d3-b6df-8656b1477bdd) is in status (DownloadTaskStatus(3)) and process (100)
I/flutter (  371): Callback on UI isolate: task (75ffda14-c1e9-40d3-b6df-8656b1477bdd) is in status (DownloadTaskStatus(3)) and process (100)
D/DownloadWorker(  371): File downloaded
I/WM-WorkerWrapper(  371): Worker result SUCCESS for Work [ id=75ffda14-c1e9-40d3-b6df-8656b1477bdd, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]
