### ISSUE TITLE
download error if file exists

### ISSUE THREAD

**Issue by chenhucxc** [fluttercommunity/flutter_downloader#620]
```java
/**
     * Create a file using java.io API
     */
    private File createFileInAppSpecificDir(String filename, String savedDir) {
        File newFile = new File(savedDir, filename);
        try {
            boolean rs = newFile.createNewFile();
            if (rs) {
                return newFile;
            } else {
                logError("It looks like you are trying to save file in public storage but not setting 'saveInPublicStorage' to 'true'");
            }
        } catch (IOException e) {
            e.printStackTrace();
            logError("Create a file using java.io API failed ");
        }
        return null;
    }
```
should add this
```java
if (newFile.exists()) {
            return newFile;
}
```

**Comment by Faaatman** [comment]
This error is also happening on Android when the file is there in the directory but I'm trying to download it using the downloader.
Can we get this fixed please?

**Comment by MirzaUkas** [comment]
> This error is also happening on Android when the file is in the directory but I'm trying to download it using the downloader.
> 
> @hnvn do you think there's a better solution for this? I think it's better to append a duplication number to the file name `ex(photo.png, photo(1).png)` since different files can have the same file name and rewriting or retrieving the file with the same name isn't the best solution IMO. I can work on a PR for this fix, I just need your input. :)

Same problem here, sound nice if you fix this. I am agree to about append a duplication number when filename is same

**Comment by FaKenKoala** [comment]
Create unique locale file with the remote file name: [gist](https://gist.github.com/58467c8bd16159ed63d79d400e28f1e9.git)


```dart
import 'dart:io';
import 'package:path/path.dart' as path;

class FileUtil {
  static File getUniqueFile(String folderName, final String? fileName) {
    int num = 1;

    String destFileName =
        fileName ?? '${DateTime.now().millisecondsSinceEpoch}';

    String extension = path.extension(destFileName);
    String baseName = path.basenameWithoutExtension(destFileName);

    File file = File(folderName + path.separator + destFileName);
    while (file.existsSync()) {
      destFileName = '$baseName (${num++})$extension';
      file = File(folderName + path.separator + destFileName);
    }
    return file;
  }

  static Future<File> createUniqueFile(
      String folderName, final String? name) async {
    File uniqueFile = FileUtil.getUniqueFile(folderName, name);
    if (!uniqueFile.existsSync()) {
      await uniqueFile.create();
    }
    return uniqueFile;
  }
}
```

**Comment by Kishan-Somaiya** [comment]
any updates on this ? facing the same issue it fails alternately if file exists.

**Comment by arthas1888** [comment]
Same problem form me

**Comment by bartekpacia** [comment]
@Faaatman Would be great to see your PR fixing this :)

**Comment by bartekpacia** [comment]
This is worked on in #708 :)

**Comment by IlyaMax** [comment]
you all have this open failed: EACCES (Permission denied) error? I'm not sure that I have the same issue as you but it seems like that
