### ISSUE TITLE
In the release version, it crashes

### ISSUE THREAD

**Issue by sh4msi** [fluttercommunity/flutter_downloader#629]
hi,
Everything is correct in debug and profile mode and works well, but in the release version, after hitting the download button, the program crashes and that's it!

**Comment by J-Dark** [comment]
Same issue for me on Android.
It works in debug mode but not in release builds where it crashes after hitting the download button.
Works fine on iOS

**Comment by J-Dark** [comment]
I missed this in the new readme file:
`@pragma('vm:entry-point') must be placed above the callback function to avoid tree shaking in release mode for Android.`
Now, for me, it's working even in obfuscated release builds.

**Comment by d9media** [comment]
I have pragma present (latest version flutter_downloader) and it still crashes

**Comment by bartekpacia** [comment]
@J-Dark's [solution](https://github.com/fluttercommunity/flutter_downloader/issues/629#issuecomment-1110603778) is correct.

Closing :)

**Comment by Shubham-Narkhede** [comment]
> I missed this in the new readme file: `@pragma('vm:entry-point') must be placed above the callback function to avoid tree shaking in release mode for Android.` Now, for me, it's working even in obfuscated release builds.

Can you please add any screenshot exactly where to put this line?

@bartekpacia @J-Dark @d9media @sh4msi

**Comment by bartekpacia** [comment]
@Shubham-Narkhede Let me know if the below snippet helps you:

```dart
@pragma('vm:entry-point')
void downloadCallback(String id, DownloadTaskStatus status, int progress) {
  debugPrint(
    'DatafilesScreen: downloader callback on background isolate: '
    'task: $id, '
    'status: $status, '
    'progress $progress',
  );

  final send = ui.IsolateNameServer.lookupPortByName('downloader_send_port');
  send?.send([id, status, progress]);
}

FlutterDownloader.registerCallback(downloadCallback);
```

**Comment by Shubham-Narkhede** [comment]
> @Shubham-Narkhede Let me know if the below snippet helps you:
> 
> ```dart
> @pragma('vm:entry-point')
> void downloadCallback(String id, DownloadTaskStatus status, int progress) {
>   // body can be anything, this is just copy-paste from my project
>   debugPrint(
>     'DatafilesScreen: downloader callback on background isolate: '
>     'task: $id, '
>     'status: $status, '
>     'progress $progress',
>   );
> 
>   final send = ui.IsolateNameServer.lookupPortByName('downloader_send_port');
>   send?.send([id, status, progress]);
> }
> 
> FlutterDownloader.registerCallback(downloadCallback);
> ```

T

> @Shubham-Narkhede Let me know if the below snippet helps you:
> 
> ```dart
> @pragma('vm:entry-point')
> void downloadCallback(String id, DownloadTaskStatus status, int progress) {
>   // body can be anything, this is just copy-paste from my project
>   debugPrint(
>     'DatafilesScreen: downloader callback on background isolate: '
>     'task: $id, '
>     'status: $status, '
>     'progress $progress',
>   );
> 
>   final send = ui.IsolateNameServer.lookupPortByName('downloader_send_port');
>   send?.send([id, status, progress]);
> }
> 
> FlutterDownloader.registerCallback(downloadCallback);
> ```

Thanks
