### ISSUE TITLE
WorkManager is not initialized properly

### ISSUE THREAD

**Issue by wuyugege** [fluttercommunity/flutter_downloader#63]
hi,here,i have something wrong after run the app

**my code is here:**
```
void executeDownloadAndInstall(String platform, String versionName) async {
    final Directory directory = await getExternalStorageDirectory();
    final String saveDir = '${directory.path}';
    print(saveDir);
    final String taskId = await FlutterDownloader.enqueue(
        url:
            'http://www.nionco.com:7001/api/smth/downloadApp?platform=$platform&versionName=$versionName',
        savedDir: saveDir,
        showNotification: true,
        openFileFromNotification: true);
    print(taskId);
    FlutterDownloader.registerCallback((id, status, progress) async {
      if (id == taskId && status == DownloadTaskStatus.complete) {
        const MethodChannel methodChannel =
            MethodChannel('com.nionco.flowersm/install');
        try {
          await methodChannel.invokeMethod(
              'install', {'path': '$saveDir/${platform}_$versionName.apk'});
        } catch (e) {
          print(e);
        }
      }
    });
  }

```
**the AndroidManifest.xml is here**
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.flowersm">

    
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="flowersm"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <provider
            android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider"
            android:authorities="${applicationId}.flutter_downloader.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>
        <provider
            android:name="androidx.work.impl.WorkManagerInitializer"
            android:authorities="${applicationId}.workmanager-init"
            android:enabled="false"
            android:exported="false" />

        <provider
            android:name="vn.hunghd.flutterdownloader.FlutterDownloaderInitializer"
            android:authorities="${applicationId}.flutter-downloader-init"
            android:exported="false">
            
            <meta-data
                android:name="vn.hunghd.flutterdownloader.MAX_CONCURRENT_TASKS"
                android:value="5" />
        </provider>
    </application>
</manifest>

**and the error info is here**
```
E/MethodChannel#vn.hunghd/downloader(27144): Failed to handle method call
E/MethodChannel#vn.hunghd/downloader(27144): java.lang.IllegalStateException: WorkManager is not initialized properly.  The most likely cause is that you disabled WorkManagerInitializer in your manifest but forgot to call WorkManager#initialize in your Application#onCreate or a ContentProvider.
E/MethodChannel#vn.hunghd/downloader(27144): 	at androidx.work.WorkManager.getInstance(WorkManager.java:141)
E/MethodChannel#vn.hunghd/downloader(27144): 	at vn.hunghd.flutterdownloader.FlutterDownloaderPlugin.enqueue(FlutterDownloaderPlugin.java:175)
E/MethodChannel#vn.hunghd/downloader(27144): 	at vn.hunghd.flutterdownloader.FlutterDownloaderPlugin.onMethodCall(FlutterDownloaderPlugin.java:73)
E/MethodChannel#vn.hunghd/downloader(27144): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MethodChannel#vn.hunghd/downloader(27144): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(FlutterNativeView.java:188)
E/MethodChannel#vn.hunghd/downloader(27144): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/MethodChannel#vn.hunghd/downloader(27144): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#vn.hunghd/downloader(27144): 	at android.os.MessageQueue.next(MessageQueue.java:379)
E/MethodChannel#vn.hunghd/downloader(27144): 	at android.os.Looper.loop(Looper.java:144)
E/MethodChannel#vn.hunghd/downloader(27144): 	at android.app.ActivityThread.main(ActivityThread.java:7529)
E/MethodChannel#vn.hunghd/downloader(27144): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#vn.hunghd/downloader(27144): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/MethodChannel#vn.hunghd/downloader(27144): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
I/flutter (27144): Download task is failed with reason(WorkManager is not initialized properly.  The most likely cause is that you disabled WorkManagerInitializer in your manifest but forgot to call WorkManager#initialize in your Application#onCreate or a ContentProvider.)
```

whats wrong with my code?

**Comment by hnvn** [comment]
Have you tried to run the example project yet? Does it work?

**Comment by fenghonghei** [comment]
I have the same problem，example works well

**Comment by hnvn** [comment]
So, try to follow the gradle configuration in `android` folder of example project.

**Comment by fenghonghei** [comment]
I checked configuration and tried again,but it can't fix.

**Comment by hnvn** [comment]
I have no idea, Can you give me a project to reproduce this matter?

**Comment by Ayush1325** [comment]
I'm having the same issue as well. Did anyone get a solution?

**Comment by debasiskoley** [comment]
I'm having the same issue after replicating git repo example. Please help to resolve the issue.

**Comment by hnvn** [comment]
Someone can give me a project that I can reproduce this error? I can't reproduce it in the `example` project

**Comment by Ayush1325** [comment]
Okay, solved that particular issue by adding the following in manifest. That tools:node thing is required for at least android P. Can't say which other versions:

`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace" />`

Now getting the following error

```
W/System.err(17817): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
W/System.err(17817): 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:605)
W/System.err(17817): 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
W/System.err(17817): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
W/System.err(17817): 	at vn.hunghd.flutterdownloader.IntentUtils.getOpenFileIntent(IntentUtils.java:23)
W/System.err(17817): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:221)
W/System.err(17817): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:104)
W/System.err(17817): 	at androidx.work.Worker$1.run(Worker.java:85)
W/System.err(17817): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(17817): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(17817): 	at java.lang.Thread.run(Thread.java:764)
I/WM-WorkerWrapper(17817): Worker result FAILURE for Work [ id=e859f550-78c9-4139-95de-79beeb53b670, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]

```
Here is the url to the demo project.
[demo](https://github.com/Ayush1325/temp)

**Comment by epenli** [comment]
the same...

**Comment by lib-javascript** [comment]
the gradle configuration in android folder of example project.  com.android.tools.build:gradle:3.4.2

**Comment by hnvn** [comment]
Does anyone try v1.2.2 and has this issue still happened yet?

**Comment by ErikMagnetto** [comment]
check permission of your app on device to solved this issue

**Comment by mgmanav91** [comment]
Hi,

I am facing the same problem. Example is working fine. my build.gradle, androidmanifest.xml, mainactivit.kt files have same config as that of example.

Can anyone let me know what owuld be the issue?

**Comment by abhihasabe** [comment]
Hello I am also facing same issue. Please check androidmanifest.xml, mainactivity.kt & build file.

Please help what me what is issue.


// mainactivity.kt

package worldjobsnews.com.video_hub

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}

//Manifest File

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="worldjobsnews.com.video_hub">
    
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
       <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace" />
    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />


    <application
        android:name="io.flutter.app.FlutterApplication"
        android:icon="@mipmap/ic_launcher"
        android:label="video_hub">
        <activity
            android:name=".MainActivity"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/NormalTheme" />
            
            <meta-data
                android:name="io.flutter.embedding.android.SplashScreenDrawable"
                android:resource="@drawable/launch_background" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />

        <provider
            android:name="androidx.work.impl.WorkManagerInitializer"
            android:authorities="${applicationId}.workmanager-init"
            android:enabled="false"
            android:exported="false" />

        <provider
            android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider"
            android:authorities="${applicationId}.flutter_downloader.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>


    </application>
</manifest>

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}


//build.gradle

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "worldjobsnews.com.video_hub"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
}
