### ISSUE TITLE
Why register twice？

### ISSUE THREAD

**Issue by yimao009** [fluttercommunity/flutter_downloader#630]
**FIrst**
void registerPlugins(NSObject<FlutterPluginRegistry>* registry) {
  if (![registry hasPlugin:@"FlutterDownloaderPlugin"]) {
     [FlutterDownloaderPlugin registerWithRegistrar:[registry registrarForPlugin:@"FlutterDownloaderPlugin"]];
  }
}

**Second**
+ (void)registerWithRegistry:(NSObject<FlutterPluginRegistry>*)registry {
  [FlutterDownloaderPlugin registerWithRegistrar:[registry registrarForPlugin:@"FlutterDownloaderPlugin"]];
}

As a result, there are two engines, and the flutter engine cannot be released in the add-to-app mode.

memory leaks

**Comment by bartekpacia** [comment]
Could you specify what's the exact problem?
