### ISSUE TITLE
Not work properly without REQUEST_INSTALL_PACKAGES

### ISSUE THREAD

**Issue by shinewanna** [fluttercommunity/flutter_downloader#636]
First of all, thanks for ur plugin. I just download video, I don't need install packages permission, but ur plugin not work properly without that permission like downloaded videos can't play to end, downloads are repeated twice, I just added to work well, but currently play store force me to remove the permission in manifest, if I don't use the feature. Please fix it at ur earliest convenience bro.
<uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />

**Comment by bartekpacia** [comment]
I'm gonna close this because of the lack of a reproducible example.

Please create a new bug report using the new [issue_template](https://github.com/fluttercommunity/flutter_downloader/issues/new/choose).
