### ISSUE TITLE
Handing over plugin maintainer

### ISSUE THREAD

**Issue by hnvn** [fluttercommunity/flutter_downloader#645]
Hi Flutter developers and contributors of FlutterDownloader plugin,

I am author and current maintainer of this plugin. I create this issue to introduce new maintainer of the plugin.

First at all, I want to say thank you guys, who trusted and used the plugin in your projects, who gave feedbacks, issues and created many PRs to contribute, fix bugs and enhance the plugin together, thanks you so much. 

For personal reason, I cannot continue being maintainer of this plugin. After asking help from contributors, @bartekpacia contacted me and willing to become new maintainer of this repository. He is an excellent mobile dev with experiences in Android and Flutter. 

I believe that FlutterDownloader will continue going forward and supports more platforms in future. Thank you.

**Comment by bartekpacia** [comment]
Thanks @hnvn for your hard work on the plugin! I'll do my best :)

**Comment by mhadaily** [comment]
welcome @bartekpacia to Flutter_downloader package maintainer team. can I have your email on pub.dev?

**Comment by bartekpacia** [comment]
Hi @mhadaily! Thanks for helping us with the transition :) My email is `barpac02@gmail.com`

**Comment by bartekpacia** [comment]
I've just now published first release :) So I'm gonna close this issue :) thank you to both of you again!
