### ISSUE TITLE
Stream download not supporting

### ISSUE THREAD

**Issue by sathya4code** [fluttercommunity/flutter_downloader#654]
Hi,

I cannot download file from stream. i have just changed the download url in example project.

 Facing following issue.
` Background Isolate Callback: task (115d3b48-3ef0-4b3c-b343-b5222e99bd04) is in status (DownloadTaskStatus(2)) and process (100)
W/System.err(29379): java.io.FileNotFoundException: /storage/emulated/0/Download/pdf (5): open failed: EACCES (Permission denied)
W/System.err(29379): 	at libcore.io.IoBridge.open(IoBridge.java:496)
W/System.err(29379): 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
W/System.err(29379): 	at java.io.FileInputStream.<init>(FileInputStream.java:115)
W/System.err(29379): 	at vn.hunghd.flutterdownloader.IntentUtils.validatedFileIntent(IntentUtils.java:42)
W/System.err(29379): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:453)
W/System.err(29379): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:235)
W/System.err(29379): 	at androidx.work.Worker$1.run(Worker.java:86)
W/System.err(29379): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(29379): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(29379): 	at java.lang.Thread.run(Thread.java:919)
W/System.err(29379): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err(29379): 	at libcore.io.Linux.open(Native Method)
W/System.err(29379): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(29379): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
W/System.err(29379): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(29379): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7460)
W/System.err(29379): 	at libcore.io.IoBridge.open(IoBridge.java:482)
W/System.err(29379): 	... 9 more`

But when i am download the file from url, it is working fine.

**Comment by bartekpacia** [comment]
Please follow bug report template (mainly, attach reproducible code sample).

**Comment by sathya4code** [comment]
> Please create a new issue that follows bug report template (mainly, attach reproducible code sample).

As i mentioned, i used example project from [flutter_downloader ](https://github.com/fluttercommunity/flutter_downloader) repo. I just changed the single url which need dynamic Authorization header which will change every hour.

**Comment by bartekpacia** [comment]
As much as I'd like to help you, I really don't know. I've just started maintaining this project this week because the old maintainer is moving away from mobile development.

Please share the URL which you changed. Maybe we can work something out then.
