### ISSUE TITLE
Progress value to be specific.

### ISSUE THREAD

**Issue by krypticallusion** [fluttercommunity/flutter_downloader#66]
The progress value changes from 0 if it's running to 100 when complete, can we get double at specific details about how much it has progressed?

**Comment by hnvn** [comment]
The plugin only updates progress value each step of 10 units, this will prevent MethodChannel flood by calling to update progress values.

**Comment by krypticallusion** [comment]
Okay.

**Comment by jain-aayush1123** [comment]
> There is no progress shown when downloading some files from google drive. only a blank progress and an error "value should be 0.0 to 1.0 "but still it downloads the file.

Hi how were you able to download files from google drive using flutter_downloader? passing in the sharable link is giving me error
`ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp`
