### ISSUE TITLE
App Crash in ios while terminating the app.

### ISSUE THREAD

**Issue by agrajparashar** [fluttercommunity/flutter_downloader#663]
Hey,
i have seen one issue when we terminate the app during download process, the crash is seen reason the code written in applicationWillTerminate function line 856.

    databaseQueue = nil;
   
    
    so you databaseQueue is set null which is causing the crash you can remove above code from applicationWillTerminate function in FlutterDownloaderPlugin.m line 856
    
    Thread crash is seen in line number 874

Incident Identifier: 500BE04C-5ED4-46CF-8BC6-D6B5CD891F9B
Hardware Model:      iPhone13,1
Process:             Runner [17714]
Path:                /private/var/containers/Bundle/Application/7D21F992-BF26-4A74-8C1E-9DD0B4587D7A/Runner.app/Runner
Identifier:          com.iamplus.productivity
Version:             2.0.0 (865)
AppStoreTools:       13E114
AppVariant:          1:iPhone13,1:15
Beta:                YES
Code Type:           ARM-64 (Native)
Role:                Non UI
Parent Process:      launchd [1]
Coalition:           com.iamplus.productivity [3233]

Date/Time:           2022-03-30 13:00:56.8058 +0530
Launch Time:         2022-03-30 12:59:30.3803 +0530
OS Version:          iPhone OS 15.1 (19B74)
Release Type:        User
Baseband Version:    2.11.02
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000050
Exception Codes: 0x0000000000000001, 0x0000000000000050
VM Region Info: 0x50 is not in any region.  Bytes before following region: 4340891568
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                   102bcc000-102bd4000 [   32K] r-x/r-x SM=COW  ...er.app/Runner
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: SIGNAL 11 Segmentation fault: 11
Terminating Process: exc handler [17714]

Triggered by Thread:  35

Thread 35 name:
Thread 35 Crashed:
0   libdispatch.dylib             	0x0000000180880968 _dispatch_sync_f + 4 (queue.c:1863)
1   flutter_downloader            	0x00000001058635c0 -[FlutterDownloaderPlugin URLSession:downloadTask:didWriteData:totalBytesWritten:totalBytesExpectedToWrite:] + 544 (FlutterDownloaderPlugin.m:869)
2   CFNetwork                     	0x00000001814128cc __123-[__NSCFURLSessionDelegateWrapper downloadTask:didWriteData:totalBytesWritten:totalBytesExpectedToWrite:completionHandler:]_block_invoke + 48 (SessionDelegateWrapper.mm:743)
3   libdispatch.dylib             	0x0000000180879914 _dispatch_call_block_and_release + 32 (init.c:1517)
4   libdispatch.dylib             	0x000000018087b660 _dispatch_client_callout + 20 (object.m:560)
5   libdispatch.dylib             	0x0000000180882de4 _dispatch_lane_serial_drain + 672 (inline_internal.h:2601)
6   libdispatch.dylib             	0x000000018088398c _dispatch_lane_invoke + 444 (queue.c:3937)
7   libdispatch.dylib             	0x000000018088e1a8 _dispatch_workloop_worker_thread + 656 (queue.c:6727)
8   libsystem_pthread.dylib       	0x00000001f17920f4 _pthread_wqthread + 288 (pthread.c:2541)
9   libsystem_pthread.dylib       	0x00000001f1791e94 start_wqthread + 8

Binary Images:
0x102bcc000 - 0x10366ffff Runner arm64  <3f090b210ba0315195776ace3c8bf65a> /private/var/containers/Bundle/Application/7D21F992-BF26-4A74-8C1E-9DD0B4587D7A/Runner.app/Runner
0x103a64000 - 0x103abbfff dyld arm64e  <c21dba379df93fc7b286734030e18bb1> /usr/lib/dyld
0x1047ac000 - 0x1047ebfff FirebaseCrashlytics arm64  <dc1cdb6a882b304b969c6b8ba083e2b7> /private/var/containers/Bundle/Application/7D21F992-BF26-4A74-8C1E-9DD0B4587D7A/Runner.app/Frameworks/FirebaseCrashlytics.framework/FirebaseCrashlytics
0x105858000 - 0x105867fff flutter_downloader arm64  <b056f29a9a753211a46710357d9ff3af> /private/var/containers/Bundle/Application/7D21F992-BF26-4A74-8C1E-9DD0B4587D7A/Runner.app/Frameworks/flutter_downloader.framework/flutter_downloader
0x106ac4000 - 0x1074f7fff omegaml arm64  <b85149df584736469575bae9af572e77> /private/var/containers/Bundle/Application/7D21F992-BF26-4A74-8C1E-9DD0B4587D7A/Runner.app/Frameworks/omegaml.framework/omegaml
0x10817c000 - 0x1088f7fff Flutter arm64  <ee2318acb95d3027b5ca9a5809a7281a> /private/var/containers/Bundle/Application/7D21F992-BF26-4A74-8C1E-9DD0B4587D7A/Runner.app/Frameworks/Flutter.framework/Flutter
0x180877000 - 0x1808bdfff libdispatch.dylib arm64e  <a5cbaab3e3893548baacfab18411b94a> /usr/lib/system/libdispatch.dylib
0x180b70000 - 0x180fc3fff CoreFoundation arm64e  <b2d21cfd378c36d5baf73f70599cfefc> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
0x181389000 - 0x18184dfff CFNetwork arm64e  <1f9e80ee1df136acbdfe22afb9a1b82e> /System/Library/Frameworks/CFNetwork.framework/CFNetwork
0x18184e000 - 0x182313fff libnetwork.dylib arm64e  <89d4751493fa3195a9534d9c7523d460> /usr/lib/libnetwork.dylib
0x182392000 - 0x182697fff Foundation arm64e  <d59c69755af237bc93be43b80b4293a5> /System/Library/Frameworks/Foundation.framework/Foundation
0x183016000 - 0x18489afff UIKitCore arm64e  <8388eb03002b3b35a78a6a022894292e> /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
0x189f1d000 - 0x189f46fff AudioSession arm64e  <99ff741f34943edf82b7c03c916ebad3> /System/Library/PrivateFrameworks/AudioSession.framework/AudioSession
0x189f47000 - 0x18a158fff AVFCore arm64e  <e512425122a4333b8508b8fa2846b2e1> /System/Library/PrivateFrameworks/AVFCore.framework/AVFCore
0x18b467000 - 0x18b580fff CoreMedia arm64e  <10c0691640343042acf78d99ee385d4d> /System/Library/Frameworks/CoreMedia.framework/CoreMedia
0x18bafe000 - 0x18cdbefff JavaScriptCore arm64e  <488fd070baee3b55ac28cee0d299f2b2> /System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore
0x18e656000 - 0x18e99dfff MediaRemote arm64e  <e7ca46bd13743c3483a84b5e9ff1daec> /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
0x1926d7000 - 0x192782fff FrontBoardServices arm64e  <6fdec0c3e5003e06948ee34bda520801> /System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices
0x19930e000 - 0x199371fff libc++.1.dylib arm64e  <255864c483d93bac8c7aad1b2d8a60cc> /usr/lib/libc++.1.dylib
0x19b02d000 - 0x19b1c7fff MediaExperience arm64e  <c3c570dae1863d5284ad0aad64c640c9> /System/Library/PrivateFrameworks/MediaExperience.framework/MediaExperience
0x19c51e000 - 0x19c526fff GraphicsServices arm64e  <44e4515eb18737f18fe028e7b087daf5> /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
0x1b7ba7000 - 0x1b7bdafff libsystem_kernel.dylib arm64e  <b1b942de75903c61980a19d80ed4da37> /usr/lib/system/libsystem_kernel.dylib
0x1ec444000 - 0x1ec46bfff caulk arm64e  <b86c5a3c323d36d296bd55a29eeebad2> /System/Library/PrivateFrameworks/caulk.framework/caulk
0x1f1791000 - 0x1f179cfff libsystem_pthread.dylib arm64e  <1a4a45fd1bb639df84140590ce103717> /usr/lib/system/libsystem_pthread.dylib
0x1f17ac000 - 0x1f17e3fff libxpc.dylib arm64e  <c4b164ee546f365786ee230d897ef6a0> /usr/lib/system/libxpc.dylib

EOF

**Comment by bartekpacia** [comment]
Should be fixed in #678.
