### ISSUE TITLE
download http source err with cast to https failure in Android 

### ISSUE THREAD

**Issue by WoodJim** [fluttercommunity/flutter_downloader#666]
ERROR MSG :
W/System.err: java.lang.ClassCastException: com.android.okhttp.internal.huc.HttpURLConnectionImpl cannot be cast to javax.net.ssl.HttpsURLConnection
W/System.err:     at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:317)
W/System.err:     at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:235)

________

see the source code fo DownloadWorker,found that "        ignoreSsl = getInputData().getBoolean(ARG_IGNORESSL, false);"  ignoreSsl is always false

**Comment by bartekpacia** [comment]
> see the source code fo DownloadWorker,found that " ignoreSsl = getInputData().getBoolean(ARG_IGNORESSL, false);" ignoreSsl is always false

It falls back to `false`. It is not always `false`. I'm currently very busy but will try to take a look at it in a few weeks.

**Comment by rivetingpeppermint** [comment]
I still have this issue too. Any updates? I'm using `flutter_downloader: ^1.7.4` on flutter `2.10.5`.

**Comment by sirkalmi** [comment]
Is there a solution for this?

**Comment by bartekpacia** [comment]
Seems like a fix should be fairly simple, if anyone's willing to do it I'll be happy to merge and release a new version.
