### ISSUE TITLE
Runs Flutter Downloader on WorkManager

### ISSUE THREAD

**Issue by rizkyputrapb** [fluttercommunity/flutter_downloader#670]
Hi, sorry if this has already questioned before. Is it possible to run this library in the background since this library itself runs in the background? The scenario is I want to download a file from a link but the link needs to be retrieved from an API call (which takes a long time). I already implement this code on the WorkManager but it keeps throwing `IOException: Permission Denied`

Here is the code: 
![image](https://user-images.githubusercontent.com/43906521/173807142-e2923d2b-fe0b-401d-99c5-fdd45b29a0f0.png)
![image](https://user-images.githubusercontent.com/43906521/173807358-358fc7e8-c749-4c84-9d0d-ea31d6b3a1e4.png)
![image](https://user-images.githubusercontent.com/43906521/173807936-12efa709-15d4-4c6f-977b-666d5d04a3dd.png)

The exception thrown:
![image](https://user-images.githubusercontent.com/43906521/173808159-9311dffe-2d63-47a8-9557-d38085830937.png)

**Comment by bartekpacia** [comment]
Hi, please don't paste images, but text. As per your question:

> Is it possible to run this library in the background since this library itself runs in the background?

TBH, I don't know. This is an unusual use case that I'm seeing for the first time.

**Comment by rizkyputrapb** [comment]
> Hi, please don't paste images, but text. As per your question:
> 
> > Is it possible to run this library in the background since this library itself runs in the background?
> 
> TBH, I don't know. This is an unusual use case that I'm seeing for the first time.

Well, I want to download a pretty large file. the link to download the file is generated from the backend (by calling an API) and the generation process takes a long time to finish. So, I decided to put the API call on the backend and when it's finished it downloads the file from the link generated. Is there any workaround for this?

**Comment by bartekpacia** [comment]
I don't think so. You'll have do to in on your own.
