### ISSUE TITLE
D/DownloadWorker( 7340): Content-Type = application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

### ISSUE THREAD

**Issue by Lazizbek97** [fluttercommunity/flutter_downloader#671]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Device information:**

- Device: [e.g. iPhone 13]
- OS: [e.g. iOS 15.4]
- plugin version [e.g. v1.8.0]

**Additional context**

**Comment by bartekpacia** [comment]
The issue template is here to be filled out...
