### ISSUE TITLE
应用重签名后location无法移动文件,提示没有权限

### ISSUE THREAD

**Issue by jsleishen** [fluttercommunity/flutter_downloader#685]
BUG: 
应用重签名后location提示无法移动文件,提示没有权限; 
类似此问题: [点击](https://github.com/Danie1s/Tiercel/issues/106)

提示: 
重签名修改了Bundle ID

系统: 
iOS 13.4以上设备

提示信息:
Info : 111copyItem error: Error Domain=NSCocoaErrorDomain Code=257 "The file “CFNetworkDownload_5PkQxo.tmp” couldn’t be opened because you don’t have permission to view it." UserInfo={NSFilePath=/private/var/mobile/Containers/Data/Application/ADF58A39-24DC-4D78-83BC-283615B7DD61/Library/Caches/com.apple.nsurlsessiond/Downloads/com.git.forme/CFNetworkDownload_5PkQxo.tmp, NSUnderlyingError=0x2815c1890 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}Source : DownloadTask.swift[361]

**Comment by bartekpacia** [comment]
Please use English.
