### ISSUE TITLE
ios: savedDir is outdated, as Document path changes on rebuild

### ISSUE THREAD

**Issue by divan** [fluttercommunity/flutter_downloader#69]
On iOS app is [sandboxed every time it's rebuilt](https://stackoverflow.com/questions/47864143/document-directory-path-change-when-rebuild-application), and so the absolute path of `Documents` directory is changed. Seems like current design of `flutter_downloader` doesn't play well with it, assuming `savedDir` to be absolute and correct across relaunches and rebuilds.

There is a workaround when using only root of the "Documents" directory – just take a "filename" field and append to the actual Documents path. But if files are downloaded into subfolders (i.e. "Documents/folder1"), this workaround doesn't work.

I see two options:
 1) store relative path in `savedDir`
 2) add another field ('path'?) with relative path to the file ('foder1/file.pdf')

Maybe I'm missing something, but it looks like there is no other workaround for this problem.
Any thoughts?

**Comment by hnvn** [comment]
My time is quite tight this time. I will come back to this issue when I have a bit spare time
