### ISSUE TITLE
Debug mode work well,release mode "flutterdownload class" not found

### ISSUE THREAD

**Issue by shipinbaoku** [fluttercommunity/flutter_downloader#691]
`E/flutter (16667): [ERROR:flutter/shell/common/shell.cc(93)] Dart Error: Class 'FlutterDownloadClass' not found in library ''.
E/flutter (16667): [ERROR:flutter/shell/common/shell.cc(93)] Dart Error: Class 'FlutterDownloadClass' not found in library ''.
E/flutter (16667): [ERROR:flutter/shell/common/shell.cc(93)] Dart Error: Class 'FlutterDownloadClass' not found in library ''.
E/flutter (16667): [ERROR:flutter/shell/common/shell.cc(93)] Dart Error: Class 'FlutterDownloadClass' not found in library ''.
`

**Comment by bartekpacia** [comment]
Not matching issue template, sorry.
