### ISSUE TITLE
[Isolate] - Problem with flutter beta 3.3+

### ISSUE THREAD

**Issue by koga187** [fluttercommunity/flutter_downloader#698]
Hi there,

I updated my flutter Beta from 3.1.0-9.0.pre to channel Beta 3.3+ and suddenly my app is crashing when using isolates.

You could reproduce the error following the issue bellow already opened on the flutter repository.

https://github.com/flutter/flutter/issues/109248

**Comment by bartekpacia** [comment]
Hi, thanks for this report. I hope to find some time to look into this soon.

**Comment by atrope** [comment]
@bartekpacia I've send the PR for the fix

**Comment by P-B1101** [comment]
I still get the error :(
`flutter_downloader: ^1.8.3`
