### ISSUE TITLE
All the task in task table is deleted after upgrade from v1.8.1 to v1.8.2

### ISSUE THREAD

**Issue by alexaung** [fluttercommunity/flutter_downloader#705]
Upgrade from v1.8.1 to v1.8.2

1. download some file at v1.8.1
2. download download_tasks.db (at v1.8.1)
3. Upgrade from v1.8.1 to v1.8.2
4. download download_tasks.db again (at v1.8.2)
5. all the download records are deleted.

**Expected behavior**

Existing records should not deleted

**Device information:**

[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-x64, locale en-GB)
    • Flutter version 3.0.5 at /Users/aungmyooo/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/aungmyooo/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • SM N975F (mobile) • RF8M82Y3K9A • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos       • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by bartekpacia** [comment]
On what platform does this bug occurs?

**Comment by alexaung** [comment]
I have tested on Android

**Comment by bartekpacia** [comment]
Thanks. Looks like [this PR](https://github.com/fluttercommunity/flutter_downloader/pull/437) caused the issue – it changed the database schema and bumped the version, but didn't provide any migrations. I'm gonna revert this PR in v1.8.3 and bring it back but with migrations added.

Sorry for problems, I'm going to be more cautious in the future.
