### ISSUE TITLE
app crashes after after download from play store

### ISSUE THREAD

**Issue by draz26648** [fluttercommunity/flutter_downloader#706]
everything was fine before uploading the app on the app store after upload when i download the app, the app gets a hard crashed and when i run the app i get this error in console 

E/AndroidRuntime(12836): FATAL EXCEPTION: main
E/AndroidRuntime(12836): Process: com.app.bimaristaan, PID: 12836
E/AndroidRuntime(12836): java.lang.RuntimeException: Unable to get provider vn.hunghd.flutterdownloader.DownloadedFileProvlider: java.lang.ClassNotFoundException: Didn't find class "vn.hunghd.flutterdownloader.DownloadedFileProvlider" on path: DexPathList[[zip file "/data/app/~~SDFRjygIpeILGeeDdVLNTQ==/com.app.bimaristaan-65VGI5t_IkG0iNj3hMe_gg==/base.apk"],nativeLibraryDirectories=[/data/app/~~SDFRjygIpeILGeeDdVLNTQ==/com.app.bimaristaan-65VGI5t_IkG0iNj3hMe_gg==/lib/x86_64, /data/app/~~SDFRjygIpeILGeeDdVLNTQ==/com.app.bimaristaan-65VGI5t_IkG0iNj3hMe_gg==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]

**Comment by bartekpacia** [comment]
"vn.hunghd.flutterdownloader.DownloadedFileProvlider" – don't you have a typo here?

**Comment by draz26648** [comment]
@bartekpacia no

**Comment by demrebicer** [comment]
You got your answer on stackoverflow. https://stackoverflow.com/questions/73407968/flutter-downloader-app-crashes-after-after-download-from-play-store

This issue can be closed. @bartekpacia
