### ISSUE TITLE
Extension has been changed when download

### ISSUE THREAD

**Issue by tungakanui** [fluttercommunity/flutter_downloader#711]
I have a url download of a .xls file
After downloading, the extension of file has been changed to .xlsx
How can I keep the original extension of file?

I'm using Flutter 2.10.5
flutter_downloader: 1.7.4

**Comment by bartekpacia** [comment]
I'm sorry but without a reproducible code sample, there's nothing I can help you with except saying that I don't know what could be causing your issue :|
