### ISSUE TITLE
FlutterDownloader.open is always returning false

### ISSUE THREAD

**Issue by danielns1982** [fluttercommunity/flutter_downloader#725]
Version 1.8.3 was `return await _channel.invokeMethod('open', {'task_id': taskId});`
Version 1.8.3+1 onwards is: 

> final result = await _channel.invokeMethod<bool>('open', {'task_id': taskId},);
> return false;

**Comment by Kundan-Android** [comment]
I am also facing the same issue. Can we expect a quick fix? Earlier it was working properly.

**Comment by Kundan-Android** [comment]
static Future<bool> open({required String taskId}) async {
    assert(_initialized, 'plugin flutter_downloader is not initialized');

    try {
      final result = await _channel.invokeMethod<bool>(
        'open',
        {'task_id': taskId},
      );

      if (result == null) {
        throw const FlutterDownloaderException(message: '`open` returned null');
      }
    } on PlatformException catch (err) {
      _log('Failed to open downloaded file. Reason: ${err.message}');
      return false;
    }

    return false;
  }

The open method is like the above. Irrespective of _channel.invokeMethod<bool> returns, Its always returning false. which is wrong.

**Comment by bartekpacia** [comment]
Thanks for reporting and sorry for the bug. Should be fixed in `v1.8.4`.
