### ISSUE TITLE
Is it possible to configure the download task not to start automatically

### ISSUE THREAD

**Issue by axis0093** [fluttercommunity/flutter_downloader#758]
Hi, I am developing a file download function, this plugin is very powerful. But during development , a problem occurred to me.
Below are my steps

1. I start a download task by FlutterDownloader.enqueue. It returns a task id, which I then put into my sqlite database with some extra info. 
2. I query (using await) a list of all downloading task with extra info from my sqlite database and display them on UI. Since the download task is running in isolate, sometimes the download callback will be executed before the query. 

This causes two problems

1. When the download callback is executed, there is no data of this download task on my UI, because the query statement has not been executed yet. I can fix this by doing an extra query in the download callback.
2. But if the above 1 was followed, the download progress would go directly from 0 to 100.

Is it possible to add a configuration so that the download task does not execute automatically, so that I can start it manually?
Or when queuing a download, let me input the download task id (instead of autogenerating ) would also solve this

Thank you.

**Comment by bartekpacia** [comment]
Hi @axis0093, this is not possible currently.
