### ISSUE TITLE
How can I execute a function after the end of the download process ?

### ISSUE THREAD

**Issue by AbdallahZidano** [fluttercommunity/flutter_downloader#797]
How can I execute a function after the end of the download process after the user exits the application and deletes it from the memory and reopens it again ?

Note: The download process is stopped when the application is deleted from the memory, and the download process is completed again when the application is opened automatically

**Comment by ash2osh** [comment]
+1

**Comment by bartekpacia** [comment]
You have to listen for `DownloadStatus`es coming from FlutterDownloader and once some status becomes `success`, this means it has completed and you can start your function.
