### ISSUE TITLE
Links to changelog in release notes are broken

### ISSUE THREAD

**Issue by rekire** [fluttercommunity/flutter_downloader#798]
I just want to mention that in the releases the links "[See changelog on pub.dev](https://github.com/fluttercommunity/flutter_downloader/blob/v1.10.1)" point to a 404, that is for all [releases](https://github.com/fluttercommunity/flutter_downloader/releases) I checked so far

**Comment by bartekpacia** [comment]
Fixed in #799. I also fixed broken links in all the older releases.
