### ISSUE TITLE
Database creation not create task table

### ISSUE THREAD

**Issue by SpaceXM** [fluttercommunity/flutter_downloader#802]
There is a problem with database creation on latest release in iOS, the database created from the package is missing of task table
So you can't retrive all task status and data. This happen only in Apple device, Android is not affected by this bug.

- Device: Any IOS Device
- plugin version 1.10.1+2

**Comment by 781flyingdutchman** [comment]
Hi, I've found the flutter_downloader to be comprehensive, but also a bit buggy, so I wrote a much simpler download package [background_downloader](https://github.com/781flyingdutchman/background_downloader).  Have a look and see if it serves your needs.

**Comment by ginhoor** [comment]
work for me

`if (Platform.isIOS) {
    var dir = await getApplicationSupportDirectory();
    if (!dir.existsSync()) {
      await dir.create();
    }
    await FlutterDownloader.initialize(debug: true, ignoreSsl: true);
  } else {
    await FlutterDownloader.initialize(debug: true, ignoreSsl: true);
  }`

**Comment by SpaceXM** [comment]
> work for me
> 
> `if (Platform.isIOS) { var dir = await getApplicationSupportDirectory(); if (!dir.existsSync()) { await dir.create(); } await FlutterDownloader.initialize(debug: true, ignoreSsl: true); } else { await FlutterDownloader.initialize(debug: true, ignoreSsl: true); }`

Still this error
 "no such table: task" UserInfo={NSLocalizedDescription=no such table: task}) sql 'SELECT * FROM task WHERE url=? ' args......"

**Comment by dhavalshah007** [comment]
I am getting following error: 
E/SQLiteLog(10901): (1) table task has no column named save_in_public_storage in "INSERT OR REPLACE  INTO task(open_file_from_notification,resumable,save_in_public_storage,task_id,file_name,progress,status,time_created,mime_type,url,

Do I manually need to create a table?
flutter_downloader: ^1.11.4

**Comment by dhavalshah007** [comment]
> I am getting following error: E/SQLiteLog(10901): (1) table task has no column named save_in_public_storage in "INSERT OR REPLACE INTO task(open_file_from_notification,resumable,save_in_public_storage,task_id,file_name,progress,status,time_created,mime_type,url,
> 
> Do I manually need to create a table? flutter_downloader: ^1.11.4

When I upgraded the plugin, it didn't update the `task` table with new columns. 
I manually deleted the databases using the [geeksforgeeks](https://www.geeksforgeeks.org/how-to-view-and-locate-sqlite-database-in-android-studio/) link

Find the code for the same at [Flutter_downloader code](https://github.com/fluttercommunity/flutter_downloader/blob/master/android/src/main/kotlin/vn/hunghd/flutterdownloader/TaskDbHelper.kt#L14)

PS: I don't have much knowledge on; how these methods will be invoked on Upgrade or Downgrade
