### ISSUE TITLE
[Android] ReceivePort listen is not invoked on the latest Flutter versions (from 3.7 onwards)

### ISSUE THREAD

**Issue by huynguyennovem** [fluttercommunity/flutter_downloader#807]
**Describe the bug**

ReceivePort listen callback is not invoked on the latest Flutter version (stable, beta and master channels) but it works on Flutter `3.3.10`. Looks like a regression issue.

**To Reproduce**

1. Run example code at https://github.com/fluttercommunity/flutter_downloader/tree/master/example on the latest Flutter beta or master channels.

    - Flutter stable: `3.7.1`
    - Flutter beta: `3.7.0-1.5.pre`
    - Flutter master: `3.8.0-1.0.pre.32`

2. Start downloading a file from the list
3. Check the console log. There are only logs for `Callback on background isolate`. `Callback on UI isolate` log does not exist.

**Expected behavior**

ReceivePort listen callback should be invoked.

**Device information:**

- Device: `Realme 6`, `Pixel 3a`
- OS: `Realme 6, Android 11`, `Pixel 3a, Android 12`
- plugin version: `flutter_downloader: ^1.10.1+2`

**Comment by J-Dark** [comment]
I have the same issue on iOS

**Comment by huynguyennovem** [comment]
@spkersten Great! Thanks for pointing out this. Actually, this issue is a duplicate of https://github.com/fluttercommunity/flutter_downloader/issues/804.

Close this as solved with the workaround.

**Comment by huynguyennovem** [comment]
Even though we can work around this but it's just temporary. It still does not work when `hot restart`. It might be a Flutter Engine issue as linked above.
