### ISSUE TITLE
Callback on UI isolate: doesn't work

### ISSUE THREAD

**Issue by abdulbosit209** [fluttercommunity/flutter_downloader#808]
I have everything working fine download notification and file opening but there is one problem.
Callback on UI isolate doesn't work at all, I want to listen for progress and downloadtaskSatus in ui but it doesn't work at all

 void bindBackgroundIsolate() {
    FlutterDownloader.registerCallback(downloadCallback, step: 1);

    final isSuccess = IsolateNameServer.registerPortWithName(
      _port.sendPort,
      'downloader_send_port',
    );
    if (!isSuccess) {
      _unbindBackgroundIsolate();
      bindBackgroundIsolate();
      return;
    }
    _port.listen((dynamic data) {
      final taskId = data[0] as String;
      final status = data[1] as DownloadTaskStatus;
      final progress = data[2] as int;

      print(
        'Callback on UI isolate: '
            'task ($taskId) is in status ($status) and process ($progress)',
      );
      emit(state.copyWith(taskId: taskId, progress: progress, taskStatus: status));
    });
  }

even print('Callback on UI isolate: ''task ($taskId) is in status ($status) and process ($progress)')   function is also not working, only print('Callback on background isolate: ' 'task ($id) is in status ($status) and process ($progress)'); inside the downloadCallback function is working

**Comment by albinpk** [comment]
**+1**

**Comment by AbdallahNassar** [comment]
same issue here

**Comment by daviinjuguna** [comment]
This seem to have a problem with the new flutter version (3.7.0 - 3.7.1). In the old version it works (3.3.10) 
Check #807

**Comment by daviinjuguna** [comment]
try this

```
IsolateNameServer.lookupPortByName('downloader_send_port')
        ?.send([id, status.value, progress]);

...
final taskId = data[0] as String;
  final status = DownloadTaskStatus(data[1] as int);
  final progress = data[2] as int;

  print(
    'Callback on UI isolate: '
        'task ($taskId) is in status ($status) and process ($progress)',
  );
```

**Comment by abdulbosit209** [comment]
@daviinjuguna it worked thanks man
