### ISSUE TITLE
images in Readme not loading for iOS steps

### ISSUE THREAD

**Issue by ayaanpathan** [fluttercommunity/flutter_downloader#810]
images in Readme not loading for iOS steps
![Screenshot 2023-02-09 at 11 07 19 AM](https://user-images.githubusercontent.com/48903105/217727371-1839ec0c-a8e3-4c9b-8a5b-1f6f20a5cb22.png)

**Comment by bartekpacia** [comment]
Works just fine for me:

![Screenshot 2023-03-12 at 5 10 35 PM](https://user-images.githubusercontent.com/40357511/224557393-46a91173-839b-41d2-8231-710a838f5e46.png)

Maybe disable adblockers?
