### ISSUE TITLE
db ios  

### ISSUE THREAD

**Issue by changkuanlai** [fluttercommunity/flutter_downloader#814]
db addNewTask  Could not execute the query.

 FlutterDownloader.loadTasks() size=0;

**Comment by changkuanlai** [comment]
![image](https://user-images.githubusercontent.com/22167353/218999644-cae78085-a405-4e54-815e-ef0efceb073b.png)

**Comment by changkuanlai** [comment]
open db error

**Comment by felipecastrosales** [comment]
What is your Flutter version, @changkuanlai? 
After `3.7.0`, has others issues relateds to iOS in this package. 
I imagine that (however unlikely), there may be relationships.

**Comment by changkuanlai** [comment]
App support dirctory  no
