### ISSUE TITLE
Progressbar listen not exactly as: 1%, 2%... procress return -374300,... not number percent

### ISSUE THREAD

**Issue by nguyenthao1988** [fluttercommunity/flutter_downloader#826]
I/flutter ( 4199): Callback on UI isolate: task (70a4f7c1-a948-4d21-8e20-1df1e70e0e57) is in status (DownloadTaskStatus(2)) and process (0)
I/flutter ( 4199): Callback on UI isolate: task (70a4f7c1-a948-4d21-8e20-1df1e70e0e57) is in status (DownloadTaskStatus(2)) and process (-374300)

**Comment by bartekpacia** [comment]
Can't help you without a reproducible example.
