### ISSUE TITLE
android wrong notification icon color

### ISSUE THREAD

**Issue by moodstubos** [fluttercommunity/flutter_downloader#83]
Device: SM-P605
Android 5.1.1

flutter_downloader uses wrong notification icon color on this device

![Unbenannt](https://user-images.githubusercontent.com/5072232/60800555-b582bb00-a175-11e9-8cda-b398e8bef504.JPG)

> [√] Flutter (Channel dev, v1.8.0, on Microsoft Windows [Version 10.0.17763.557], locale de-DE)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [√] Android Studio (version 3.4)
> [√] VS Code (version 1.34.0)
> [√] Connected device (2 available)
> 
> • No issues found!

**Comment by hnvn** [comment]
This would be fixed in v1.1.9
