### ISSUE TITLE
UI state not changed , flutter latest version

### ISSUE THREAD

**Issue by dghub-founder** [fluttercommunity/flutter_downloader#831]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Device information:**

- Device: [e.g. iPhone 13]
- OS: [e.g. iOS 15.4]
- plugin version [e.g. v1.8.0]

**Additional context**

**Comment by subhash279** [comment]
there seems to be some issue in communication between isolates.

**Comment by dghub-founder** [comment]
> there seems to be some issue in communication between isolates.

How to fix?

**Comment by bartekpacia** [comment]
make sure to update your apps as described [here](https://github.com/fluttercommunity/flutter_downloader/pull/817).

Closing because this issue doesn't have any information about an issue.

**Comment by dghub-founder** [comment]
Not working for me 
Please come telegram
t.me/dghub-founder
