### ISSUE TITLE
 _port.listen not working it not listen callback data

### ISSUE THREAD

**Issue by iresolveservices** [fluttercommunity/flutter_downloader#838]
@pragma('vm:entry-point')
   static void downloadCallback(String id, DownloadTaskStatus status, int progress) {
    debugPrint('Callback progress ${progress} status.value ${status.value}  id ${id}');

    IsolateNameServer.lookupPortByName('downloader_send_port')
        ?.send([id, status, progress]);
  } 

void bind() {

    final isSuccess =  IsolateNameServer.registerPortWithName(_port.sendPort, 'downloader_send_port');
    if (!isSuccess) {
      unBind();
      bind();
      debugPrint('_bindBackgroundIsolate Callback progress ssds');
      return;
    }
    debugPrint('_bindBackgroundIsolate Callback progress ssdsaa $isSuccess');
    _port.listen((dynamic data) {
      String id = data[0];
      DownloadTaskStatus status = data[1];
      int progress = data[2];

      debugPrint('_bindBackgroundIsolate Callback progress ${progress} status.value ${status.value}  id ${id}');
      print(
        'Callback on UI isolate: '
            'task ($id) is in status ($status) and process ($progress)',
      );
    });

  }
[log.pdf](https://github.com/fluttercommunity/flutter_downloader/files/11007921/log.pdf)

**Comment by iresolveservices** [comment]
pls check and revert asap

**Comment by hkhatuwal** [comment]
i have the solution. instead of passing `status `directly pass the `status.value` because I think it's not accepting an enum value so pass the int value

**Before**
` IsolateNameServer.lookupPortByName('downloader_send_port')?.send([id, status, progress]);`


**After**
` IsolateNameServer.lookupPortByName('downloader_send_port')?.send([id, status.value, progress]);`

**Comment by QiPg** [comment]
have same problem

**Comment by flying-wizzy** [comment]
> i have the solution. instead of passing `status `directly pass the `status.value` because I think it's not accepting an enum value so pass the int value
> 
> **Before** ` IsolateNameServer.lookupPortByName('downloader_send_port')?.send([id, status, progress]);`
> 
> **After** ` IsolateNameServer.lookupPortByName('downloader_send_port')?.send([id, status.value, progress]);`

worked for me. But I didn't have this problem until now. What has changed?

**Comment by bartekpacia** [comment]
If you submit a PR with the updates, I'll be happy to review it.

**Comment by fanuelal** [comment]
> If you submit a PR with the updates, I'll be happy to review it.

    _port.listen((dynamic data) {
      print('... listening');
      _taskId = data[0] as String;
      _status = DownloadTaskStatus(data[1] as int);
      _progress = data[2] as int;

      print(
        'Callback on UI isolate: '
        'task ($_taskId) is in status ($_status) and process ($_progress)',
      );
    });
    
    
    
     @pragma('vm:entry-point')
  static downloadCallback(String id, DownloadTaskStatus status, int progress) {
    IsolateNameServer.lookupPortByName('downloader_send_port')
        ?.send([id, status.value, progress]);
  }
  
  
I have corrected in this way but can't fix the error please

**Comment by abdullah432** [comment]
It's working in debug mode but not working in release mode for me.

**Comment by nadeemabualarayes** [comment]
> It's working in debug mode but not working in release mode for me.

also me does not working in release 
how can fix it ?

**Comment by annd22** [comment]
is there any update on this, not working on release mode

**Comment by sanalkv** [comment]
_port.listen only works in debug and not in release? Any solutions ?
