### ISSUE TITLE
FlutterDownloader.registerCallback() have a external class reference？

### ISSUE THREAD

**Issue by liuyasss** [fluttercommunity/flutter_downloader#84]
There is such a callback,

FlutterDownloader.registerCallback();

I will leave the page during the process of downloading the file. Does this function hold a reference to the external class? What should I do if I hold it?

thanks

`class _DictOfflineDownloadPageState extends BasePageState<DictOfflineDownloadPage> {
  OfflineDictsHandle _offlineDictsHandle;
  StreamSubscription _subscription;

  List<DownLoadItem> _downLoads = <DownLoadItem>[];
  bool _isLoading = true;
  MyLocalizations _localizations;

  @override
  String pageTag() => _tag;

  @override
  void initState() {
    super.initState();
    _localizations = widget._localizations;

    OfflineDictsHandle.create().then((_h) {
      _offlineDictsHandle = _h;
      _subscription = _offlineDictsHandle.onDictsUpdate.listen(_init);
      _offlineDictsHandle.start();
    });

    FlutterDownloader.registerCallback((String id, DownloadTaskStatus status, int progress) {
      DownLoadItem dItem = _downLoads.firstWhere((item) => item.taskId == id);
      if (dItem != null) {
        if (progress < 0) {
          progress = 0;
          status = DownloadTaskStatus.undefined;
        }

        dItem.progress = progress;
        dItem.status = status;

        if (status == DownloadTaskStatus.complete) {
          dItem.initDescription();
          FlutterDownloader.loadTasksWithRawQuery(
                  query: "SELECT * FROM task WHERE task_id = '${dItem.taskId}'")
              .then((tasks) {
            if (tasks.length > 0) {
              OfflineDictsHandle.SetDownloaded(
                  dItem.meta.id, '${dItem.localPath}/${tasks[0].filename}', dItem.meta.version);
              dItem.delete();
            }
          });
          _removeDownloadCallback();
        }

        if (mounted) {
          setState(() {});
        }
      }
    });
  }
}`

**Comment by hnvn** [comment]
fixed v1.3.0
