### ISSUE TITLE
First of all, thanks for ur plugin. I just download video, I don't need install packages permission, but ur plugin not work properly without that permission like downloaded videos can't play to end, downloads are repeated twice, I just added to work well, but currently play store force me to remove the permission in manifest, if I don't use the feature. Please fix it at ur earliest convenience bro.

### ISSUE THREAD

**Issue by amansoni599** [fluttercommunity/flutter_downloader#841]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Device information:**

- Device: [e.g. iPhone 13]
- OS: [e.g. iOS 15.4]
- plugin version [e.g. v1.8.0]

**Additional context**

**Comment by bartekpacia** [comment]
Please follow the issue template. This is not actionable.
