### ISSUE TITLE
Not showing progress while downloading

### ISSUE THREAD

**Issue by vuthasothea** [fluttercommunity/flutter_downloader#844]
There were no progress showing when user clicked download.

### Screenshot

https://user-images.githubusercontent.com/10680557/229976838-67fe17b0-a5ed-4739-a728-973d88ac82fc.mov

**Comment by riverscuomo** [comment]
We were able to fix this with the solution here:  [fluttercommunity/flutter_downloader#807](https://github.com/fluttercommunity/flutter_downloader/issues/807)

**Comment by vuthasothea** [comment]
> We were able to fix this with the solution here: [fluttercommunity/flutter_downloader#807](https://github.com/fluttercommunity/flutter_downloader/issues/807)

It works. Many thank for supporting me
