### ISSUE TITLE
Android build failed with duplicate class error

### ISSUE THREAD

**Issue by algodave** [fluttercommunity/flutter_downloader#86]
I'm getting the [duplicate classes](https://developer.android.com/studio/build/dependencies#duplicate_classes) error on Android build:

```
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: ... 
  Program type already present: android.support.v4.os.ResultReceiver$1
```

I have `compileSdkVersion 29` in my `build.gradle`.

I've been reading a couple past "build failed" issues (#76 and #47) but wasn't able to find a solution for my case there (and it might be because I'm not an Android developer!)

Could someone please help?

**Comment by algodave** [comment]
@hnvn I noticed your https://github.com/fluttercommunity/flutter_downloader/issues/76#issuecomment-502331043 and it seems that the Medium article you linked there could help in my case, however I don't have enough Android knowledge to figure out a solution based on it. It would be great if you could share some detailed settings for a successful build 🙂 

At the same time I'm wondering: maybe `flutter_downloader` is not (yet) ready for AndroidX? in Flutter's [AndroidX Compatibility](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility) page I read:

> If your app depends on plugins that use the old `android.support` packages, you’ll need to avoid using AndroidX.

According to Readme, this plugin needs `android.support.FILE_PROVIDER_PATHS` so shall I [avoid AndroidX](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility#avoiding-androidx) in my project if I want to use `flutter_downloader`?

**Comment by hnvn** [comment]
Have you configured your project with AndroidX yet?
```
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by algodave** [comment]
@hnvn Thanks for helping!

I just realized that I actually can't migrate my project to AndroidX because my customer wants our app to also work on older Android versions.

So my question now is: can you point me to a previous version of `flutter_downloader` that would work on a non-AndroidX Flutter project? Thank you!

**Comment by hnvn** [comment]
v1.1.5, check the `CHANGELOG.md` for detail
