### ISSUE TITLE
namespace

### ISSUE THREAD

**Issue by AlejandroRodriguezO** [fluttercommunity/flutter_downloader#860]
i have an error when compiling in android with version 1.10.3 and it is the following Could not find method namespace() for arguments [vn.hunghd.example] on extension 'android' of type com.android.build.gradle.internal.dsl.BaseAppModuleExtension. i can't find anything about it in the documentation.

**Comment by bartekpacia** [comment]
Make sure you're using latest Gradle and Android Gradle Plugin in your app.
