### ISSUE TITLE
Multiple downloads limitation

### ISSUE THREAD

**Issue by JoseP-97** [fluttercommunity/flutter_downloader#864]
Hey there!

I'd like to limit the num of download tasks to 1. Reading the docs I found that the way to make this happen is to add a new key/value in the info.plist file:
<key>FDMaximumConcurrentTasks</key>
<integer>1</integer>

However, this is not working.

Besides, the docs mentions that it is limited in 3 by default, but it feels like it is not limited.

**Comment by bartekpacia** [comment]
Duplicate of #332
