### ISSUE TITLE
_port.listen not working it not listen callback data in ios

### ISSUE THREAD

**Issue by nadeemabualarayes** [fluttercommunity/flutter_downloader#867]
in release mode 

###    IsolateNameServer.registerPortWithName(
          _port.sendPort, 'downloader_send_port');

      _port.listen((dynamic data) async {
        print('UI Isolate Callback: $data');
        int status = data[1];
        print(status);
        final DownloadTaskStatus _status = DownloadTaskStatus(data[1] as int);
        print(_status);
        print("---------status---------");
        if (status == 3) {
          Navigator.pop(context);
          print('success' + _localMusicDirectoryPath);
          _audioPlayer = AudioPlayer();
          isMusicSelect = true;
          _localMusicPath = _localMusicDirectoryPath + '/' + soundFileName;
          setState(() {});
        }
      });

      FlutterDownloader.registerCallback(downloadCallback);

 static void downloadCallback(
      String id, DownloadTaskStatus status, int progress) {
    print(
        'Background Isolate Callback: task ($id) is in status ($status) and process ($progress)');
    try {
      final SendPort send =
          IsolateNameServer.lookupPortByName('downloader_send_port');
      send?.send([id, status.value, progress]);
    } catch (e) {
      print(e);
    }
  }

**Comment by bartekpacia** [comment]
Not reproducible.
