### ISSUE TITLE
download task fails

### ISSUE THREAD

**Issue by Sushil787** [fluttercommunity/flutter_downloader#868]
it download the file and in notification panel it's show download status completed on download complete while adding directory as getExternalStorageDirectory() while enqeueing task.
But while enqueing task if i add dir as getApplicationSupportDirectory()
it download file but show the download status as failed. 

![Screenshot from 2023-06-22 16-49-27](https://github.com/fluttercommunity/flutter_downloader/assets/63179543/cf455fbd-8959-4405-8af1-289daae48dbd)

**Comment by bartekpacia** [comment]
Not reproducible.

**Comment by giroskii** [comment]
me too

**Comment by Sushil787** [comment]
> 

did you used getApplicationSupportDirectory ?

**Comment by giroskii** [comment]
> > 
> 
> did you used getApplicationSupportDirectory ?

Yes. The code is similar to yours.

```
final Directory _appDocDir = await getApplicationDocumentsDirectory();
final Directory _appDocDirFolder = Directory('${_appDocDir.path}/exams/');

await FlutterDownloader.enqueue(
  url: some.url, // file url
  savedDir: _appDocDirFolder.path, 
  fileName: 'navigation.json', 
  showNotification: false,
  saveInPublicStorage: false,
  allowCellular: true);
```

**Comment by Sushil787** [comment]
> > > 
> > 
> > 
> > did you used getApplicationSupportDirectory ?
> 
> Yes. The code is similar to yours.
> 
> ```
> final Directory _appDocDir = await getApplicationDocumentsDirectory();
> final Directory _appDocDirFolder = Directory('${_appDocDir.path}/exams/');
> 
> await FlutterDownloader.enqueue(
>   url: some.url, // file url
>   savedDir: _appDocDirFolder.path, 
>   fileName: 'navigation.json', 
>   showNotification: false,
>   saveInPublicStorage: false,
>   allowCellular: true);
> ```

@bartekpacia  is this reproducible?

**Comment by giroskii** [comment]
> > > > 
> > > 
> > > 
> > > getApplicationSupportDirectory를 사용하셨습니까?
> > 
> > 
> > 예. 코드는 귀하와 유사합니다.
> > ```
> > final Directory _appDocDir = await getApplicationDocumentsDirectory();
> > final Directory _appDocDirFolder = Directory('${_appDocDir.path}/exams/');
> > 
> > await FlutterDownloader.enqueue(
> >   url: some.url, // file url
> >   savedDir: _appDocDirFolder.path, 
> >   fileName: 'navigation.json', 
> >   showNotification: false,
> >   saveInPublicStorage: false,
> >   allowCellular: true);
> > ```
> 
> @bartekpacia 이것이 재현 가능합니까?

url은 http이다. example에 있는 pdf를 기준으로 외부디렉토리(download)에는 정상적으로 작동 되지만 getApplicationDocumentsDirectory()은 progress가 100이 되자마자 status가 -1로 되고 download가 failed이 된다. 실제 경로에 가면 파일은 저장이 되어 있다. 나는 현재 Dio로 다운로드를 하고 있지만, 백그라운드 작업이 필요하다.

**Comment by giroskii** [comment]
> > > > 
> > > 
> > > 
> > > did you used getApplicationSupportDirectory ?
> > 
> > 
> > Yes. The code is similar to yours.
> > ```
> > final Directory _appDocDir = await getApplicationDocumentsDirectory();
> > final Directory _appDocDirFolder = Directory('${_appDocDir.path}/exams/');
> > 
> > await FlutterDownloader.enqueue(
> >   url: some.url, // file url
> >   savedDir: _appDocDirFolder.path, 
> >   fileName: 'navigation.json', 
> >   showNotification: false,
> >   saveInPublicStorage: false,
> >   allowCellular: true);
> > ```
> 
> @bartekpacia is this reproducible?

url is http. Based on the pdf in the example, it works normally for the external directory (download), but in getApplicationDocumentsDirectory(), as soon as the progress reaches 100, the status becomes -1 and the download becomes failed. If you go to the actual path, the file is saved. I'm currently downloading on Dio, but I need background work.

**Comment by m-hamza-tanbits** [comment]
@giroskii @bartekpacia 
any update on it 
while below 13 its working fine 
above 13 when it goes 100 percent and status goes to failed,
while file has been saved on location
