### ISSUE TITLE
1.1.8+ causes google_sign_in to crash when signing in

### ISSUE THREAD

**Issue by nemoryoliver** [fluttercommunity/flutter_downloader#87]
I've confirmed this is the package that's causing my app to crash. specifically version **1.1.8** - **1.1.9** of **flutter_downloader**

**Error Details**

> D/AndroidRuntime( 8860): Shutting down VM
> E/AndroidRuntime( 8860): FATAL EXCEPTION: main
> E/AndroidRuntime( 8860): Process: com.stackwares.android.storysaver.facebook, PID: 8860
> E/AndroidRuntime( 8860): java.lang.IncompatibleClassChangeError: Class 'com.google.android.gms.auth.api.signin.internal.SignInHubActivity' does not implement interface 'androidx.lifecycle.LifecycleOwner' in call to 'androidx.lifecycle.Lifecycle androidx.lifecycle.LifecycleOwner.getLifecycle()' (declaration of 'androidx.lifecycle.LiveData' appears in /data/app/com.stackwares.android.storysaver.facebook-S-ECUReU-GPlSZDYDLuGuw==/base.apk!classes2.dex)
> E/AndroidRuntime( 8860): 	at androidx.lifecycle.LiveData.observe(LiveData.java:172)
> E/AndroidRuntime( 8860): 	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setCallback(LoaderManagerImpl.java:100)
> E/AndroidRuntime( 8860): 	at androidx.loader.app.LoaderManagerImpl.createAndInstallLoader(LoaderManagerImpl.java:400)
> E/AndroidRuntime( 8860): 	at androidx.loader.app.LoaderManagerImpl.initLoader(LoaderManagerImpl.java:421)
> E/AndroidRuntime( 8860): 	at com.google.android.gms.auth.api.signin.internal.SignInHubActivity.zzn(Unknown Source:80)
> E/AndroidRuntime( 8860): 	at com.google.android.gms.auth.api.signin.internal.SignInHubActivity.onActivityResult(Unknown Source:68)
> E/AndroidRuntime( 8860): 	at android.app.Activity.dispatchActivityResult(Activity.java:7523)
> E/AndroidRuntime( 8860): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4307)
> E/AndroidRuntime( 8860): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4355)
> E/AndroidRuntime( 8860): 	at android.app.ActivityThread.-wrap19(Unknown Source:0)
> E/AndroidRuntime( 8860): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1680)
> E/AndroidRuntime( 8860): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> E/AndroidRuntime( 8860): 	at android.os.Looper.loop(Looper.java:164)

**Flutter Doctor**

> [✓] Flutter (Channel dev, v1.8.1, on Mac OS X 10.14.5 18F132, locale en-US)
>     • Flutter version 1.8.1 at /Users/nemory/Development/flutter
>     • Framework revision d3eee57c0b (13 days ago), 2019-07-08 11:04:24 -0700
>     • Engine revision 3c51a7bfff
>     • Dart version 2.5.0 (build 2.5.0-dev.0.0 b5aeaa6796)
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /Users/nemory/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 10.2.1, Build version 10E1001
>     • CocoaPods version 1.7.0
> 
> [✓] iOS tools - develop for iOS devices
>     • ios-deploy 1.9.4
> 
> [✓] Android Studio (version 3.3)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 32.0.1
>     • Dart plugin version 182.5124
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
> 
> [✓] VS Code (version 1.36.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.2.0
> 
> [✓] Connected device (1 available)
>     • BBE100 5 • 5000238111 • android-arm64 • Android 8.1.0 (API 27)

**Comment by nihar1024** [comment]
I can also confirm, version **1.1.8 and above** of **flutter_downloader** causes my app to crash when using **google_sign_in**. I receive the exact same error mentioned above.

**Comment by hnvn** [comment]
That's own issue of Google Sign Plugin when migrating to AndroidX: https://stackoverflow.com/questions/53899751/google-auth-migrating-to-androidx-signinhubactivity-does-not-implement-lifecycl

By the way, The newest version of GoogleAuth library is 17.0.0, but google_sign_in plugin is still using 16.0.1

**Comment by nemoryoliver** [comment]
Fixed the crashing issue by adding `implementation 'androidx.core:core-ktx:1.2.0-alpha03'` to the **project > app > build.gradle**

Thanks a lot @hnvn
