### ISSUE TITLE
Can't download file from link with url redirection, Android, v1.1.9.

### ISSUE THREAD

**Issue by VladimirMitso** [fluttercommunity/flutter_downloader#88]
I need to downalod some videos from Vimeo.
Here is simple example:
```
  Future<String> downloadFile() async {
    String dirPath = (await getExternalStorageDirectory()).path;
    Directory dir = Directory(dirPath);
    if (!await dir.exists()) {
      await dir.create();
    }
    String taskId = await FlutterDownloader.enqueue(
      fileName: 'vimeo_video.mp4',
      url:
          'https://player.vimeo.com/play/194935659?s=76233122_1563893921_fcd6451b93c394a5908e72a32d13608c&loc=external&context=Vimeo%5CController%5CClipController.main&download=1',
      savedDir: dirPath,
      showNotification: true,
      openFileFromNotification: true,
    );
    return taskId;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('test'),),
      body: Padding(
        padding: const EdgeInsets.all(24),
        child: Center(
          child: FutureBuilder(
            future: downloadFile(),
            builder: (BuildContext context, AsyncSnapshot<String> snapshot) {
              switch (snapshot.connectionState) {
                case ConnectionState.none:
                  return Text('nothing');
                case ConnectionState.active:
                case ConnectionState.waiting:
                  return Text('waiting');
                case ConnectionState.done:
                  if (snapshot.hasError) return Text('error: ${snapshot.error}');
                  return Text('result: ${snapshot.data}');
              }
              return null;
            },
          ),
        ),
      ),
    );
  }
```
And the logs are:
```
W/WM-WorkSpec( 3578): Backoff delay duration less than minimum value
I/flutter ( 3578): Download task is enqueued with id(6ccbe3b0-d783-41b8-b2f4-f00531b5bd9f)
D/libc-netbsd( 3578): getaddrinfo: player.vimeo.com get result from proxy >>
I/System.out( 3578): propertyValue:true
I/System.out( 3578): [CDS]connect[player.vimeo.com/151.101.0.217:443] tm:15
I/System.out( 3578): gba_cipher_suite:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
I/System.out( 3578): [OkHttp] sendRequest>>
I/System.out( 3578): [OkHttp] sendRequest<<
I/System.out( 3578): [CDS]close[45025]
I/NetworkManagementSocketTagger( 3578): untagSocket(67)
I/WM-WorkerWrapper( 3578): Worker result SUCCESS for Work [ id=6ccbe3b0-d783-41b8-b2f4-f00531b5bd9f, tags={ vn.hunghd.flutterdownloader.DownloadWorker, flutter_download_task } ]
```
I don't need permission handler in this example because I test on API 21 device.

I already tried with different `.jpg` pictures and `.mp3` audios, everything works.

Chrome can download this video, but this plugin can't.

Here is link to original Vimeo video, there is a downalod button:
[https://vimeo.com/76233122?cjevent=f1bfb9f9ad5711e9834604f30a18050d](url)

**Comment by hnvn** [comment]
Your download link is not correct, it should be: https://gcs-vimeo.akamaized.net/exp=1563947759~acl=%2A%2F194935651.mp4%2A~hmac=f5d3acea8bdb11a01447702dbe1d70bbee4eed626e16c29121cbc138bb81e5d7/vimeo-prod-skyfire-std-us/01/246/3/76233122/194935651.mp4?download=1&filename=Journey+from+Assen+to+Groningen+with+David+Hembrow.mp4

**Comment by VladimirMitso** [comment]
No, the link is correct.

I have dozens of these links and they all start with `https://player.vimeo.com ...`
But then while donwloading it redirects to links like `https://gcs-vimeo ...`

Put this link or any othe similar to in Chrome and it will download it: 
[https://player.vimeo.com/play/194935657?s=76233122_1563963116_b42003c4e6620036272ad2de650930ed&loc=external&context=Vimeo%5CController%5CClipController.main&download=1](https://player.vimeo.com/play/194935657?s=76233122_1563963116_b42003c4e6620036272ad2de650930ed&loc=external&context=Vimeo%5CController%5CClipController.main&download=1)

**Comment by VladimirMitso** [comment]
@hnvn
I was even able to download these videos with `HttpClient`.
There can be no mistake, links are correct.

**Comment by VladimirMitso** [comment]
And also this library can downalod videos using these links 
[https://github.com/flutterchina/dio](https://github.com/flutterchina/dio)
`response = await dio.download(urlPath, savePath);`

**Comment by GyuriMajercsik** [comment]
I confirm, redirection is not supported. 

```
D/DownloadWorker(24972): Server replied HTTP code: 308
I/WM-WorkerWrapper(24972): Worker result SUCCESS for Work [ id=92003c29-0446-48f8-9f2d-0910d55b3250, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]
```

**Comment by reynaldots** [comment]
I created a PR correcting this problem, allowing the download of URLs that have 307 and 308 redirect on android: #511 

For me I also created a version of 1.5.2 with commits up to version 1.6.1 without the nullsafety changes: https://github.com/reynaldots/flutter_downloader/tree/allow_download_307_308_redirects
