### ISSUE TITLE
How to get the value of DownloadTaskStatus？

### ISSUE THREAD

**Issue by SpanishOnion** [fluttercommunity/flutter_downloader#885]
[https://github.com/fluttercommunity/flutter_downloader/pull/835/commits/dd7c81254160d51c9ddc9c7bd57e24a8e9399d02](url)

This update affected the code of my project.

`
if (status == DownloadTaskStatus.running.value) 

status = DownloadTaskStatus.enqueued.value
`

The above code hints: The getter 'value' isn't defined for the type 'DownloadTaskStatus'.

How to get the value of DownloadTaskStatus in the new version?

**Comment by ggmanuilov** [comment]
@SpanishOnion Hi!
Try it:

```dart

  Future<void> _prepare() async {
    _port.listen((dynamic data) async {
      String id = data[0];
      final DownloadTaskStatus status = DownloadTaskStatus.values[data[1] as int];
      if (status == DownloadTaskStatus.complete) {
        // your code here!!!
      }
    });

    FlutterDownloader.registerCallback(downloadCallback);
  }
```

Work on `flutter_downloader: ^1.11.1` version.
