### ISSUE TITLE
Error unresolved reference after upgrading to 1.11.2

### ISSUE THREAD

**Issue by widiasa** [fluttercommunity/flutter_downloader#892]
After upgrading to 1.11.2, I can't build my project.

e: file:///home/diaz/.pub-cache/hosted/pub.dev/flutter_downloader-1.11.2/android/src/main/kotlin/vn/hunghd/flutterdownloader/DownloadWorker.kt:62:27 Unresolved reference: TaskDbHelper
e: file:///home/diaz/.pub-cache/hosted/pub.dev/flutter_downloader-1.11.2/android/src/main/kotlin/vn/hunghd/flutterdownloader/DownloadWorker.kt:136:20 Unresolved reference: TaskDbHelper
e: file:///home/diaz/.pub-cache/hosted/pub.dev/flutter_downloader-1.11.2/android/src/main/kotlin/vn/hunghd/flutterdownloader/DownloadWorker.kt:148:20 Unresolved reference: TaskDbHelper
e: file:///home/diaz/.pub-cache/hosted/pub.dev/flutter_downloader-1.11.2/android/src/main/kotlin/vn/hunghd/flutterdownloader/DownloadWorker.kt:446:38 Unresolved reference: IntentUtils
e: file:///home/diaz/.pub-cache/hosted/pub.dev/flutter_downloader-1.11.2/android/src/main/kotlin/vn/hunghd/flutterdownloader/FlutterDownloaderPlugin.kt:49:27 Unresolved reference: TaskDbHelper
e: file:///home/diaz/.pub-cache/hosted/pub.dev/flutter_downloader-1.11.2/android/src/main/kotlin/vn/hunghd/flutterdownloader/FlutterDownloaderPlugin.kt:49:42 Unresolved reference: TaskDbHelper
e: file:///home/diaz/.pub-cache/hosted/pub.dev/flutter_downloader-1.11.2/android/src/main/kotlin/vn/hunghd/flutterdownloader/FlutterDownloaderPlugin.kt:369:13 Unresolved reference: IntentUtils
e: file:///home/diaz/.pub-cache/hosted/pub.dev/flutter_downloader-1.11.2/android/src/main/kotlin/vn/hunghd/flutterdownloader/TaskDao.kt:8:37 Unresolved reference: TaskDbHelper
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 1100 bytes (99.9% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_downloader:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

**Comment by widiasa** [comment]
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.4, on Ubuntu 20.04.6 LTS 5.15.0-83-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.82.2)
[✓] Connected device (2 available)
[✓] Network resources

**Comment by salmaahhmed** [comment]
@widiasa could be related to you using the package in pubspec.yaml eg: x.x.x (older version) and you want to update to the latest version, So you update pubspec.yaml. Still inside the code, when referring to the plugin, it still points to the old version from pub-cache. Internally, pub-cache still has both old and new versions. So I recommend cleaning the pub cache by either running the `flutter pub cache clean ` (keep in mind this deletes the pub cache for all your previous packages) or by manually deleting ` /Users/xxxxxxx/development/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_downloaderxx/ `

**Comment by widiasa** [comment]
Got it. Successfully fixed.
