### ISSUE TITLE
Downloading failing in android

### ISSUE THREAD

**Issue by TheArslan** [fluttercommunity/flutter_downloader#897]
After reaching progress to 100 status changes to failed and progress become -1 in android
I am attaching the picture of printed logs below

<img width="1379" alt="Screenshot 2023-09-28 at 12 26 21 AM" src="https://github.com/fluttercommunity/flutter_downloader/assets/46085373/11117efd-4f03-4f4e-9d52-f7e174c67fea">

**Comment by TesteurManiak** [comment]
Got a similar issue, adding the [`provider` to open downloaded file](https://pub.dev/packages/flutter_downloader#open-downloaded-file-from-notification) to the `AndroidManifest.xml` fixed it:
```xml
<provider
    android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider"
    android:authorities="${applicationId}.flutter_downloader.provider"
    android:exported="false"
    android:grantUriPermissions="true">
    <meta-data
        android:name="android.support.FILE_PROVIDER_PATHS"
        android:resource="@xml/provider_paths"/>
</provider>
```
