### ISSUE TITLE
Notification not showing on android device status bar

### ISSUE THREAD

**Issue by shajedul-bdfare** [fluttercommunity/flutter_downloader#902]
```
await FlutterDownloader.enqueue(
            headers: headers,
            url: baseUrl + url,
            fileName: !isNull(fileName) ? "$fileName.pdf" : null,
            savedDir: saveDirectory.path,
            showNotification: true,
            openFileFromNotification: true,
            saveInPublicStorage: true,
   );
```

 Notification icon when downloading/downloaded is not showing in status bar but its showing on notification panel. Any idea whats wrong?

**Comment by shajedul-bdfare** [comment]
Note: it seems the flutter_downloader package's notification is set to Silent by default. If I change it from app settings it works. How can I achieve this in code?

**Comment by salmaahhmed** [comment]
@shajedul-bdfare hey thanks! i will take a look on it.

**Comment by salmaahhmed** [comment]
@shajedul-bdfare  can you please add this in your manifest file and let me know how it goes? 
 <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>

**Comment by shajedul-bdfare** [comment]
@salmaahhmed Nop its not working.

I think while creating notification, setting 'importance' to default/high will help. I am not sure. Just my thought.

**Comment by houcemzenakhra** [comment]
same here

**Comment by salmaahhmed** [comment]
@houcemzenakhra @shajedul-bdfare according to[ android permission documentation ](https://developer.android.com/develop/ui/views/notifications/notification-permission#new-apps ) for targeting android 13 (API Level 33) notifications are off by default and we need to show a permission dialog. You can use the package permission_handler at the moment until I take a look into possible solutions for this plugin. 

You will have to add in your manifest `<uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>`
and then use  `Permission.notification.request()`

**Comment by jaythakkarBAPS** [comment]
same issue facing not showing media control above android 13

**Comment by handkerchief333** [comment]
> @houcemzenakhra @shajedul-bdfare according to[ android permission documentation ](https://developer.android.com/develop/ui/views/notifications/notification-permission#new-apps) for targeting android 13 (API Level 33) notifications are off by default and we need to show a permission dialog. You can use the package permission_handler at the moment until I take a look into possible solutions for this plugin.
> 
> You will have to add in your manifest `<uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>` and then use `Permission.notification.request()`

the notifications appear, but silently and you can only see them if you open the notification center separately. I also think that the notifications need to be marked as Important. That way the user hardly sees them.
