### ISSUE TITLE
Issue with Spaces and Parentheses in File Names

### ISSUE THREAD

**Issue by shohidul-metatude** [fluttercommunity/flutter_downloader#904]
I've come across a problem where file names containing spaces and parentheses are being replaced with underscores after downloading. It used to be fine before. What could be the reason now for this behavior?

**Comment by salmaahhmed** [comment]
@shohidul-metatude hi do you provide a custom fileName ?

**Comment by shohidul-metatude** [comment]
> @shohidul-metatude hi do you provide a custom fileName ?

`    await FlutterDownloader.enqueue(
        url: url.toString(),
        savedDir: appDocPath.path,
        fileName: requestFilename,
        headers: {
          HttpHeaders.connectionHeader: 'keep-alive',
          HttpHeaders.cookieHeader: cookiesString,
        },
        saveInPublicStorage: true,
        showNotification: true,
        openFileFromNotification: true,
        requiresStorageNotLow: true);
  }`

Yes. If file name is "document (1).pdf" it changes to "document__1_.pdf"

**Comment by salmaahhmed** [comment]
@shohidul-metatude ok please use previous version until this one is fixed

**Comment by salmaahhmed** [comment]
@shohidul-metatude can you update to  1.11.4. and confirm the issue is fixed ?

**Comment by shohidul-metatude** [comment]
It is working now. Thank you @salmaahhmed.
