### ISSUE TITLE
iOS. Incorrect filename in latest download task

### ISSUE THREAD

**Issue by Shkryabminer** [fluttercommunity/flutter_downloader#923]
iOS 14.8.1
When started FlutterDownloader.enque(...,
filename: test.mp4 (for example),
...) download task save filename _______ . I see this in var tasks = await FlutterDownloader.loadTasks(); and logs , incorrect name is put to DB table. Then when new task added previous task has correct name but the new one has _______ file name. I use Bloc and do port subscription and listening in Bloc

**Comment by waihanko** [comment]
Did you find solution for this bug?

**Comment by Shkryabminer** [comment]
Just rolled back to 1.11.4 for now

**Comment by waihanko** [comment]
@Shkryabminer For me, version 1.11.4 still showing this _____________. in IOS

**Comment by salmaahhmed** [comment]
@Shkryabminer can you tell me what's the file name ?

**Comment by Shkryabminer** [comment]
@salmaahhmed "Test", "dwsample%20mp4%201080p.mp4" - both

**Comment by Shkryabminer** [comment]
![IMG_2155](https://github.com/fluttercommunity/flutter_downloader/assets/31506603/d6cfca43-dd3e-4b20-bf3b-f212fa6fd9db)
![IMG_2159](https://github.com/fluttercommunity/flutter_downloader/assets/31506603/981c06db-2888-45d3-b18d-7563611e0c88)

**Comment by Shkryabminer** [comment]
See timestamps of 2 last downloads

**Comment by salmaahhmed** [comment]
@Shkryabminer please use the latest version it will be fixed.

**Comment by Shkryabminer** [comment]
@salmaahhmed do you mean 1.11.6?

**Comment by salmaahhmed** [comment]
@Shkryabminer yeah did u check ?

**Comment by Shkryabminer** [comment]
@salmaahhmed Yes, seems it works). Closing issue
