### ISSUE TITLE
My app crashed when adding await FlutterDownloader.initialize

### ISSUE THREAD

**Issue by TungQuan** [fluttercommunity/flutter_downloader#924]
My app crashed when adding await FlutterDownloader.initialize(
      debug:
          true, // optional: set to false to disable printing logs to console (default: true)
      ignoreSsl:
          true // option: set to false to disable working with http links (default: false)
      );
![Screenshot 2023-12-08 at 23 02 29](https://github.com/fluttercommunity/flutter_downloader/assets/35253200/66ce0b5d-4c0d-49a8-8472-90ec22e7a818)
![Screenshot 2023-12-08 at 23 08 51](https://github.com/fluttercommunity/flutter_downloader/assets/35253200/9a747013-3e3f-4d63-bf69-3e83a9c8a859)
![Screenshot 2023-12-08 at 23 12 47](https://github.com/fluttercommunity/flutter_downloader/assets/35253200/47304ec3-12d2-418c-96ee-51480e2533ba)

**Comment by jdk-21** [comment]
How did you solve the problem?
