### ISSUE TITLE
httpConn.contentType must not be null error when download file

### ISSUE THREAD

**Issue by uzair-ird** [fluttercommunity/flutter_downloader#936]
**Descri java.lang.NullPointerException: getContentType(...) must not be null
W/System.err( 7202): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.kt:343)
W/System.err( 7202): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.kt:206)
W/System.err( 7202): 	at androidx.work.Worker$1.run(Worker.java:82)
W/System.err( 7202): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
W/System.err( 7202): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
W/System.err( 7202): 	at java.lang.Thread.run(Thread.java:1012)
I/WM-WorkerWrapper( 7202): Worker result FAILURE for Work [ id=fc17e316-6f48-48ae-9c4d-80293d740396, tags={ vn.hunghd.flutterdownloader.DownloadWorker, flutter_download_task } ]be the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Device information:**

- Device: [e.g. iPhone 13]
- OS: [e.g. iOS 15.4]
- plugin version [e.g. v1.8.0]

**Additional context**

**Comment by uzair-ird** [comment]
I am using flutter_downloader: ^1.11.5 this version

**Comment by bartekpacia** [comment]
should be resolved by #966
