### ISSUE TITLE
Flutter Download CallBack Not Working At first time

### ISSUE THREAD

**Issue by balajiks-dev** [fluttercommunity/flutter_downloader#937]
In Flutter Android App, Once click on the download. 

The download starts in the background while the port listener is not listening the status of the download from the Android. Hence, the progress and completion of the task status can't be retrieved in the flutter. 

This happens only at the first time of download once the app is newly installed.

Issue: Callback on background isolate: task (*******) is in status (1) and process (0) not getting called.

In the First time file download, I'm getting this console output but the callback listeners are not working. 

I/WM-WorkerWrapper( 3706): Worker result SUCCESS for Work [ id=1736fab4-b28d-427a-a3a1-807eb2fcd350, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]

At the second time file download, getting this console output.

Callback on background isolate: task (fd96843f-2c35-4c9a-bf38-*****) is in status (2) and process (0)
I/flutter ( 3706): Callback on UI isolate: task (fd96843f-2c35-4c9a-bf38-****) is in status (DownloadTaskStatus.running) and process (0)

Please let us know any solution for this.

**Comment by bagusandrewijaya** [comment]
same bro

**Comment by sathya4code** [comment]
I am also facing the same issue in Android.

**Comment by sathya4code** [comment]
is this package still maintained?
