### ISSUE TITLE
Work Manager not initialized properly

### ISSUE THREAD

**Issue by Tunga12** [fluttercommunity/flutter_downloader#94]
E/MethodChannel#vn.hunghd/downloader(29039): 	at androidx.work.WorkManager.getInstance(WorkManager.java:161)
E/MethodChannel#vn.hunghd/downloader(29039): 	at vn.hunghd.flutterdownloader.FlutterDownloaderPlugin.enqueue(FlutterDownloaderPlugin.java:176)
E/MethodChannel#vn.hunghd/downloader(29039): 	at vn.hunghd.flutterdownloader.FlutterDownloaderPlugin.onMethodCall(FlutterDownloaderPlugin.java:73)
E/MethodChannel#vn.hunghd/downloader(29039): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#vn.hunghd/downloader(29039): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#vn.hunghd/downloader(29039): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/MethodChannel#vn.hunghd/downloader(29039): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#vn.hunghd/downloader(29039): 	at android.os.MessageQueue.next(MessageQueue.java:138)
E/MethodChannel#vn.hunghd/downloader(29039): 	at android.os.Looper.loop(Looper.java:123)
E/MethodChannel#vn.hunghd/downloader(29039): 	at android.app.ActivityThread.main(ActivityThread.java:5356)
E/MethodChannel#vn.hunghd/downloader(29039): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/MethodChannel#vn.hunghd/downloader(29039): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/MethodChannel#vn.hunghd/downloader(29039): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
E/MethodChannel#vn.hunghd/downloader(29039): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
E/MethodChannel#vn.hunghd/downloader(29039): 	at dalvik.system.NativeStart.main(Native Method)
I/flutter (29039): Download task is failed with reason(WorkManager is not initialized properly.  The most likely cause is that you disabled WorkManagerInitializer in your manifest but forgot to call WorkManager#initialize in your Application#onCreate or a ContentProvider.)

**Comment by hnvn** [comment]
#63

**Comment by Tunga12** [comment]
The solution in #63 was the following:
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace" />

I added that statement to the manifest but the error still persists?

**Comment by ZOROsrk** [comment]
@Tunga12  yes it does

**Comment by Moonwing** [comment]
have anyone solve the problem?

**Comment by nazdream** [comment]
I have a similar issue with the latest plugin version - 1.7.1. Are there any solutions?
```
E/AndroidRuntime(10597): Process: com.cleansmarts.appv2, PID: 10597
E/AndroidRuntime(10597): java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.IllegalStateException: WorkManager is already initialized.  Did you try to initialize it manually without disabling WorkManagerInitializer? See WorkManager#initialize(Context, Configuration) or the class level Javadoc for more information.
E/AndroidRuntime(10597): 	at android.app.ActivityThread.installProvider(ActivityThread.java:7222)
E/AndroidRuntime(10597): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6694)
E/AndroidRuntime(10597): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6589)
E/AndroidRuntime(10597): 	at android.app.ActivityThread.access$1400(ActivityThread.java:227)
E/AndroidRuntime(10597): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1890)
E/AndroidRuntime(10597): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(10597): 	at android.os.Looper.loop(Looper.java:224)
E/AndroidRuntime(10597): 	at android.app.ActivityThread.main(ActivityThread.java:7590)
E/AndroidRuntime(10597): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10597): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(10597): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime(10597): Caused by: androidx.startup.StartupException: java.lang.IllegalStateException: WorkManager is already initialized.  Did you try to initialize it manually without disabling WorkManagerInitializer? See WorkManager#initialize(Context, Configuration) or the class level Javadoc for more information.
E/AndroidRuntime(10597): 	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:162)
E/AndroidRuntime(10597): 	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:198)
E/AndroidRuntime(10597): 	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:42)
E/AndroidRuntime(10597): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2117)
E/AndroidRuntime(10597): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2091)
E/AndroidRuntime(10597): 	at android.app.ActivityThread.installProvider(ActivityThread.java:7211)
E/AndroidRuntime(10597): 	... 10 more
E/AndroidRuntime(10597): Caused by: java.lang.IllegalStateException: WorkManager is already initialized.  Did you try to initialize it manually without disabling WorkManagerInitializer? See WorkManager#initialize(Context, Configuration) or the class level Javadoc for more information.
E/AndroidRuntime(10597): 	at androidx.work.impl.WorkManagerImpl.initialize(WorkManagerImpl.java:185)
E/AndroidRuntime(10597): 	at androidx.work.WorkManager.initialize(WorkManager.java:210)
E/AndroidRuntime(10597): 	at androidx.work.WorkManagerInitializer.create(WorkManagerInitializer.java:39)
E/AndroidRuntime(10597): 	at androidx.work.WorkManagerInitializer.create(WorkManagerInitializer.java:30)
E/AndroidRuntime(10597): 	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:155)
E/AndroidRuntime(10597): 	... 15 more

```

**Comment by akkalbhor** [comment]
@nazdream Did you find the solution?

**Comment by Kishan-Somaiya** [comment]
@nazdream I'm getting the same issue with 1.7.0, did you find the solution ?

**Comment by Kishan-Somaiya** [comment]
@nazdream @akkalbhor I'm getting the same issue with 1.7.0, did you find the solution ? @hnvn can you help us here ?

**Comment by HeyRonak** [comment]
anyone found solution ? @akkalbhor  @Kishan-Somaiya @Moonwing
