### ISSUE TITLE
下载进度到达100后又返回错误

### ISSUE THREAD

**Issue by wengxianxun** [fluttercommunity/flutter_downloader#943]
I/flutter ( 5528): Callback on background isolate: task (b6905e0f-6884-4f53-ac2c-0256b1c81f85) is in status (2) and process (97)
I/flutter ( 5528): Callback on UI isolate: task (b6905e0f-6884-4f53-ac2c-0256b1c81f85) is in status (DownloadTaskStatus.running) and process (95)
I/flutter ( 5528): Callback on UI isolate: task (b6905e0f-6884-4f53-ac2c-0256b1c81f85) is in status (DownloadTaskStatus.running) and process (97)
D/DownloadWorker( 5528): Update too frequently!!!!, this should be dropped
I/flutter ( 5528): Callback on background isolate: task (b6905e0f-6884-4f53-ac2c-0256b1c81f85) is in status (2) and process (99)
D/DownloadWorker( 5528): Update too frequently!!!!, this should be dropped
I/flutter ( 5528): Callback on background isolate: task (b6905e0f-6884-4f53-ac2c-0256b1c81f85) is in status (2) and process (100)
D/DownloadWorker( 5528): Update too frequently!!!!, but it is the final update, we should sleep a second to ensure the update call can be processed
I/flutter ( 5528): Callback on background isolate: task (b6905e0f-6884-4f53-ac2c-0256b1c81f85) is in status (4) and process (-1)
I/flutter ( 5528): Callback on UI isolate: task (b6905e0f-6884-4f53-ac2c-0256b1c81f85) is in status (DownloadTaskStatus.running) and process (99)
I/flutter ( 5528): Callback on UI isolate: task (b6905e0f-6884-4f53-ac2c-0256b1c81f85) is in status (DownloadTaskStatus.running) and process (100)
I/flutter ( 5528): Callback on UI isolate: task (b6905e0f-6884-4f53-ac2c-0256b1c81f85) is in status (DownloadTaskStatus.failed) and process (-1)
D/DownloadWorker( 5528): Update notification: {notificationId: 2, title: http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4, status: FAILED, progress: -1}

**Comment by bartekpacia** [comment]
Use English.
