### ISSUE TITLE
Can we avoid to decode Location header value, or make decoding optional?

### ISSUE THREAD

**Issue by algodave** [fluttercommunity/flutter_downloader#95]
I have a Ruby on Rails backend that uses [ActiveStorage](https://edgeguides.rubyonrails.org/active_storage_overview.html) to accept and serve files. For downloading a file, the Rails backend exposes a URL; on request received, it responds with 302 and sets the actual download URL in the `Location` header, which targets an external storage service (in my case Google Cloud Storage).

I'm not succeeding in using `flutter_downloader` in my app. It does send the request to Google Cloud Storage backend, but it responds with `Signature was not base64 encoded`. I realized that this occurs because `URLDecoder.decode()` is performed on the value of `Location` header - see [this line](https://github.com/fluttercommunity/flutter_downloader/blob/master/android/src/main/java/vn/hunghd/flutterdownloader/DownloadWorker.java#L201)

As I see in the [URLDecoder.decode](https://developer.android.com/reference/java/net/URLDecoder.html#decode(java.lang.String,%20java.lang.String)) docs, it expects an `application/x-www-form-urlencoded` String. However, [Location header specs](https://tools.ietf.org/html/rfc7231#section-7.1.2) do not seem to enforce such encoding. 

I think the above mentioned `URLDecoder.decode()` call could be removed, or at least made optional. As a side note, I also spotted [this usage](https://github.com/fluttercommunity/flutter_downloader/blob/master/android/src/main/java/vn/hunghd/flutterdownloader/DownloadWorker.java#L227) of `URLDecoder.decode()` and was wondering why is `ISO-8859-1` used in that case, instead of `UTF-8`.

Thank you!

**Comment by hnvn** [comment]
I don't have much knowledge about World Wide World specifications, but I found something about header encoding here: https://www.w3.org/International/articles/http-charset/index#charset

**Comment by algodave** [comment]
@hnvn `Content-Type` is used to specify type and charset of an HTTP *payload* (aka body). Whereas, Location is an HTTP *header*

**Comment by hnvn** [comment]
I've just updated the codes which handles `Location` header, just give it a try
