### ISSUE TITLE
java.io.FileNotFoundException: /storage/emulated/0/Pictures/abc.jpg (Permission denied)

### ISSUE THREAD

**Issue by harpreetsi9h** [fluttercommunity/flutter_downloader#96]
I have defined Read & Write Storage permissions in manifest then asked and allowed storage permissions but whenever I trying to download the image then this error comes every time

W/WM-WorkSpec: Backoff delay duration less than minimum value
I/flutter: Download task is enqueued with id(96240761-55c8-479a-a285-d6d1767d10da)
**W/System.err: java.io.FileNotFoundException: /storage/emulated/0/Pictures/abc.jpg (Permission denied)**
W/System.err:     at java.io.FileOutputStream.open0(Native Method)
 W/System.err:     at java.io.FileOutputStream.open(FileOutputStream.java:308)
W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:151)
W/System.err:     at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:244)
 W/System.err:     at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:108)
W/System.err:     at androidx.work.Worker$1.run(Worker.java:85)
 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 W/System.err:     at java.lang.Thread.run(Thread.java:764)
I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=96240761-55c8-479a-a285-d6d1767d10da, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]

**Comment by hnvn** [comment]
Have you handled permission request at runtime yet? Adding permissions in Manifest is not enough with some permissions marked as sensitive. You might have a look at the example project for example codes

**Comment by mehul425** [comment]
https://github.com/fluttercommunity/flutter_downloader/issues/492#issuecomment-891578558
