### ISSUE TITLE
When the app is downloading the task, I close the app and then re-open the app

### ISSUE THREAD

**Issue by dmlzj** [fluttercommunity/flutter_downloader#97]
When the app is downloading the task, I close the app and then re-open the app. The task status is still being downloaded. Actually, there is no download. I clicked the pause button and the task did not respond.

![hk8os-njfcv](https://user-images.githubusercontent.com/3021601/62748649-f713c800-ba8b-11e9-97f7-8cda5eeda658.gif)

**Comment by dannyCaiHaoming** [comment]
I also have this problem, it seems that `flutter_downloader` didn't save the progress when app quit, so when I came in again, the task was still in the queue and could not be resumed

**Comment by hnvn** [comment]
What do you mean about **quit** action? Do you press home button or terminate the application from background list?

**Comment by dannyCaiHaoming** [comment]
I'm writing code in vscode,so I can just press **F5** to **exit** the program.But this is the equivalent of killing apps in iOS by sliding them through the app list.

**Comment by dannyCaiHaoming** [comment]
> What do you mean about **quit** action? Do you press home button or terminate the application from background list?

**Comment by dannyCaiHaoming** [comment]
> I'm writing code in vscode,so I can just press **F5** to **exit** the program.But this is the equivalent of killing apps in iOS by sliding them through the app list.

I'm writing code in vscode,so I can just press F5 to exit the program.But this is the equivalent of killing apps in iOS by sliding them through the app list.

**Comment by dannyCaiHaoming** [comment]
> What do you mean about **quit** action? Do you press home button or terminate the application from background list?

I'm writing code in vscode,so I can just press F5 to exit the program.But this is the equivalent of killing apps in iOS by sliding them through the app list.

**Comment by dannyCaiHaoming** [comment]
> What do you mean about **quit** action? Do you press home button or terminate the application from background list?

I'm writing code in vscode,so I can just press F5 to exit the program.But this is the equivalent of killing apps in iOS by sliding them through the app list.

I just tried to kill the program in the simulator and found that the problem was not reproduced.

**Comment by dannyCaiHaoming** [comment]
> What do you mean about **quit** action? Do you press home button or terminate the application from background list?

When I do this download function in iOS, even after the forced exit of the app in the middle of the download, the next time I come in, I can still retrieve the previous progress and continue to download. I wonder if this can be done?

**Comment by dmlzj** [comment]
> > What do you mean about **quit** action? Do you press home button or terminate the application from background list?
> 
> I'm writing code in vscode,so I can just press F5 to exit the program.But this is the equivalent of killing apps in iOS by sliding them through the app list.
> 
> I just tried to kill the program in the simulator and found that the problem was not reproduced.

I am using vscode killed the progress too, so I have this problem.

**Comment by hnvn** [comment]
> When I do this download function in iOS, even after the forced exit of the app in the middle of the download, the next time I come in, I can still retrieve the previous progress and continue to download. I wonder if this can be done?

Currently, my iOS codes will set all unfinished tasks to *canceled* status when the application is terminated (by OS or users). It happens in `applicationWillTerminate:` function. I am not sure but I think that killing the application from vscode doesn't do the same as iOS system does.

**Comment by dannyCaiHaoming** [comment]
> > I'm writing code in vscode,so I can just press F5 to exit the program.But this is the equivalent of killing apps in iOS by sliding them through the app list.
> > I just tried to kill the program in the simulator and found that the problem was not reproduced.
> 
> Currently, my iOS codes will set all unfinished tasks to _canceled_ status when the application is terminated (by OS or users). It happens in `applicationWillTerminate:` function. I am not sure but I think that killing the application from vscode doesn't do the same as iOS system does.

I think so too. So according to your design, exiting the app does not cause other problems at present. But I was wondering if you would update the status of the task before the app exits.

**Comment by dmlzj** [comment]
> > I'm writing code in vscode,so I can just press F5 to exit the program.But this is the equivalent of killing apps in iOS by sliding them through the app list.
> > I just tried to kill the program in the simulator and found that the problem was not reproduced.
> 
> Currently, my iOS codes will set all unfinished tasks to _canceled_ status when the application is terminated (by OS or users). It happens in `applicationWillTerminate:` function. I am not sure but I think that killing the application from vscode doesn't do the same as iOS system does.

Yes, so the problem caused by ending the app process via vscode can be ignored.

**Comment by 1232209** [comment]
> > I'm writing code in vscode,so I can just press F5 to exit the program.But this is the equivalent of killing apps in iOS by sliding them through the app list.
> > I just tried to kill the program in the simulator and found that the problem was not reproduced.
> 
> Currently, my iOS codes will set all unfinished tasks to _canceled_ status when the application is terminated (by OS or users). It happens in `applicationWillTerminate:` function. I am not sure but I think that killing the application from vscode doesn't do the same as iOS system does.

when task become canceld status,the download progress is lost?Can keep the progress of the last download？

**Comment by 1232209** [comment]
> this

Can you retrieve the previous progress and continue to download? Why does my last task status change to cancelled as soon as I open it? And then I can only download it from scratch. Where did I get it wrong?

**Comment by 1232209** [comment]
This plug-in is perfect, but the current restart of the app can not keep the progress, which makes me very passive

**Comment by pachecotatih** [comment]
I have the same problem... #993
