### ISSUE TITLE
Files download working in the Android version 12 and 13 emulators, but not working in real devices.

### ISSUE THREAD

**Issue by HarishBirlangi242** [fluttercommunity/flutter_downloader#971]
I am able to download files to local storage of android version 12 and 13 emulators, but i am unable to download the files to the real devices. It's working till the task id generation, I am able to generate the task id. below is my manifest file and download service files. I am using flutter_inappwebview: ^5.7.2+2, permission_handler: ^11.3.1,   path_provider: ^2.0.11, flutter_downloader: ^1.8.4.

I am able to get below prints, but not getting any errors
I/flutter (30343): DownloadPath: /storage/emulated/0/Download/
I/flutter (30343): Task Id = 1bc57f3e-4607-49ca-a730-c1fe22e80a41

Android.xml file:
`
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.GoGridlex">
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.AUDIO_CAPTURE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="32" />
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>
    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO"/>
    <uses-permission android:name="android.permission.READ_MEDIA_AUDIO"/>

  <provider
              android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider"
              android:authorities="${applicationId}.flutter_downloader.provider"
              android:exported="false"
              android:grantUriPermissions="true">
              <meta-data
                  android:name="android.support.FILE_PROVIDER_PATHS"
                  android:resource="@xml/provider_paths"/>
          </provider>
`
Main.dart file:

`
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await FlutterDownloader.initialize(
      debug:
          true, // optional: set to false to disable printing logs to console (default: true)
      ignoreSsl:
          true // option: set to false to disable working with http links (default: false)
      );
  runApp(myApp());
}

@override
  void initState() {
    super.initState();
    IsolateNameServer.registerPortWithName(
        _port.sendPort, 'downloader_send_port');
    _port.listen((dynamic data) {
      String id = data[0];
      DownloadTaskStatus status = data[1];
      int progress = data[2];
      if (status.toString() == "DownloadTaskStatus(3)" && progress == 100) {
        String query = "SELECT * FROM task WHERE task_id='$id'";
        FlutterDownloader.loadTasksWithRawQuery(query: query);
        FlutterDownloader.open(taskId: id);
      }
    });

    FlutterDownloader.registerCallback(downloadCallback);
  }

  @override
  void dispose() {
    IsolateNameServer.removePortNameMapping('downloader_send_port');
    super.dispose();
  }

  @pragma('vm:entry-point')
  static void downloadCallback(
      String id, DownloadTaskStatus status, int progress) {
    final SendPort? send =
        IsolateNameServer.lookupPortByName('downloader_send_port');
    send?.send([id, status, progress]);
  }

if (allPermissionsAccepted == true) {
      fileNameToDownload = await getFileName(url);
      String cookiesString = await updateCookies(url.url);
      String downloadPath = await getDownloadPath();
      print('DownloadPath: $downloadPath');
      final taskId = await FlutterDownloader.enqueue(
        headers: {
          HttpHeaders.connectionHeader: 'keep-alive',
          HttpHeaders.cookieHeader: cookiesString
        },
        url: url.url.toString(),
        savedDir: downloadPath,
        fileName: fileNameToDownload,
        saveInPublicStorage: true,
        showNotification: true,
        openFileFromNotification: true,
      );
      print("Task Id = $taskId");
      Helper().showSnackBar("Downloading...");
    } else {
      print('Permission Denied');
    }

`

**Comment by HarishBirlangi242** [comment]
It's the notification issue, download is working fine.

**Comment by itstiemoko** [comment]
> It's the notification issue, download is working fine.

Hello there, I have the same problem. Did you solve it (notification issue on android 12 and above) ?
