### ISSUE TITLE
It is better to not use this package, instead write your own code using WorkManager or native platform-specific code

### ISSUE THREAD

**Issue by SteelTitan247** [fluttercommunity/flutter_downloader#972]
I have faced a thousand issues while using this package, more than any other. It is better to use workmanager, flutter_foreground_service, and any other required package for this or write platform specific code. Downloads don't work properly, there is no one by one download process, I had to change native files for that. Whoever wrote this package, I highly request you to remove it, or shift it to beta, at least our time will not be wasted trying to debug this package's native files.

**Comment by ulisseshen** [comment]
This package was bandoned by the fluttercommunity. So sad.
